### ISSUE TITLE
403 Forbidden when calling extractSensitivityLabels API with Application permission

### ISSUE THREAD

**Issue by jformacek** [microsoftgraph/microsoft-graph-docs#17397] opened 2022-06-22 13:08 UTC
Hello,
Seems that it's not possible to call this API with Application permission. I always get 403 Forbidden error with message "Cannot call this API using the current App Id." Calling with delegated permissions works fine.

Please either update Permissions section to mention accessibility only with Delegated permissions, or update content to explain prerequisites for calling this API with Application permission.

Thank you,
Jiri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf32c036-ebb2-584f-bf58-6be54e1d8251
* Version Independent ID: add94c0c-ce07-77a8-7754-a3f08e36c573
* Content: [driveItem: extractSensitivityLabels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-extractsensitivitylabels?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/driveitem-extractsensitivitylabels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/driveitem-extractsensitivitylabels.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @jaLuthra
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mszorc** [comment] 2022-07-19 07:03
Hello,

Are there any plans to change this behaviour? I've been having the same issue.

Thank you
Michał

**Comment by jaLuthra** [comment] 2022-07-19 22:38
The API is intended to work with App only mode as well. We have recorded a bug internally on engineering side to fix the API, and PR is already in Review. I will update and close this bug when the changes are checked in.

**Comment by jaLuthra** [comment] 2022-08-19 10:16
The issue is resolved now

**Closed by jaLuthra** 2022-08-19 10:16 UTC
Labels: subarea: files
