### ISSUE TITLE
File facet MimeType only works on OneDrive Personal

### ISSUE THREAD

**Issue by TomGroeneboer** [microsoftgraph/microsoft-graph-docs#968] opened 2017-03-16 13:06 UTC
Issue:
I'm currently working on a project that uses the Microsoft Graph API. I've noted that the `MimeType` in the `file facet` of a `DriveItem` is not present on requests to OneDrive for Business. Could you please update the documentation to explicitly note this behavior?

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/file.md

Thanks

**Comment by isvargasmsft** [comment] 2021-03-29 18:42
Hello, 

My deepest apologies for the delays. 

I tried to reproduce the error from my end but it looks like this has been resolved, as the response shows the proper information. Command:
`GET https://graph.microsoft.com/v1.0/me/drive/items/{itemID}`

The file facet in the response will contain both hashes and mimeType. Details [here](https://docs.microsoft.com/en-us/graph/api/resources/file?view=graph-rest-1.0).

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

Kind regards, 

Isaac Vargas

**Closed by isvargasmsft** 2021-03-29 18:42 UTC
Labels: area: onedrive, bug: documentation
