### ISSUE TITLE
Document is missing from menu

### ISSUE THREAD

**Issue by BenWhite27** [microsoftgraph/microsoft-graph-docs#4292] opened 2019-04-01 16:10 UTC
This document seems to be missing from the side Navigation menu.  I've checked under Files&gt;DriveItems and couldn't find as link to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13c0408-7bbe-485f-aeef-b9dd14fd7ae3
* Version Independent ID: 53548df3-7d53-bc9d-a2e1-5eb0298132cb
* Content: [Check In Files - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-checkin?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveitem-checkin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-checkin.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by FaithOmbongi** [comment] 2021-02-12 17:04
Closing as a duplicate of #4291

**Closed by FaithOmbongi** 2021-02-12 17:04 UTC
