### ISSUE TITLE
Response not returning allowCreatePrivateChannels property

### ISSUE THREAD

**Issue by markgort86** [microsoftgraph/microsoft-graph-docs#6245] opened 2019-11-07 13:54 UTC
When using the Graph API within a Logic App not all property's are returned. The following property allowCreatePrivateChannels is missing. But when using this property the setting is applied to the newly created team. 

I make this comment on this article because of this sentence "All the properties will be returned from an actual call"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-msft** [comment] 2021-01-04 07:37
allowCreatePrivateChannels is now returned in PUT /groups/{id}/team response. Closing this issue, in case you feel the issue is not resolved either reopen this issue or create a new issue.

**Closed** 2021-01-19 18:48 UTC
Labels: area: teams, bug: documentation, teams: TACO
