### ISSUE TITLE
Issue with extension case sensitive/insensitive

### ISSUE THREAD

**Issue by PawelKaczanowski7N** [microsoftgraph/microsoft-graph-docs#16908] opened 2022-05-16 15:26 UTC
Example scenario:
Create extension 'Test' = `extension_[AppID]_Test`
'targetObjects' = User.

Assign value for this extension for user_1:
`Update-MgUser -UserId user_1 -AdditionalProperties @{extension_[AppID]_Test = '1'}`

Assign value for this extension for user_2:
`Update-MgUser -UserId user_1 -AdditionalProperties @{extension_[AppID]_test = '2'}`

:information_source: Look on case 'T' / 't' in test word.

And now try to retrieve those values.
When you use `?select=extension_[AppID]_Test` you will get value only for User_1

When you use `?select=extension_[AppID]_test` you will get value only for User_2 , but what is also interesting attribute name will be returned as `extension_[AppID]_Test`

In conclusion, when you assign extension, case characters in extension name doesn't matter, all will be accepted. :open_mouth:

But when you want to retrieve them you must use select in exact case as you assign them.

For now we found two temporary solutions:
1. Use beta api with empty select. It will return them all.
2. Use multi select: `?select=extension_[AppID]_Test, extension_[AppID]_test`

I think it is worth to mention this in documentation, it will save a lot of investigations :wink:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad2fa0a-381e-efd5-2030-b76fcdbc2436
* Version Independent ID: 04a78b65-ca47-9cdd-26a0-ab854fd33b51
* Content: [Create extensionProperty - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-extensionproperty?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-extensionproperty.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2022-05-19 12:19
Thank you @PawelKaczanowski7N for raising this issue. I've managed to replicate the same behavior. Let me raise this internally so it can be investigated and resolved.

Cc @dkershaw10 for visibility.

**Comment by dkershaw10** [comment] 2022-06-28 12:19
Sorry for the delayed response here @PawelKaczanowski7N 

This seems to be a bug in our service which processes extension values. The issue is that the service treats the extension definition names as case insensitive but when the actual extension value is written to corresponding object (user/group/company etc), the name used is what is supplied by the caller instead of actual name from the extension definition.

The workaround is to use the exact same casing in the payload when modifying/creating extension property values as the casing in the name defined in the extension property definition.

I'm looking into whether we can get this issue properly fixed

**Comment by FaithOmbongi** [comment] 2022-08-02 10:14
The bug is tracked internally via 2005541.

**Comment by FaithOmbongi** [comment] 2022-08-15 11:27
Closing this issue here and tracking it internally via bug report 2005541.

**Closed by FaithOmbongi** 2022-08-15 11:27 UTC
Labels: area: Azure AD, bug: product, area: extensions
