### ISSUE TITLE
How to Invite Federated User?

### ISSUE THREAD

**Issue by Schenz** [microsoftgraph/microsoft-graph-docs#6928] opened 2020-01-28 19:35 UTC
This sample works exactly as I would expect for sending an invitation that creates a user and a Microsoft account for them, but how do I send an invitation to a user to use their federated account to log into my application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/invitation-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Schenz** [comment] 2020-01-29 17:46
Found this, but it does not work: https://docs.microsoft.com/en-us/azure/active-directory-b2c/migrate-social-identities

When I try to POST to https://graph.microsoft.com/v1.0/Users, it does not like the userIdentities object.
When I try to POST to https://graph.windows.net/{tenant}.onmicrosoft.com/users?api-version=1.6 my access_token never works.

**Comment by elisolMS** [comment] 2020-04-14 00:21
@Schenz Can you clarify what's not working?  A B2B invitation creates a "shadow" account for the user in your directory and that should be enough for the user to use their own credentials to access your app rather than creating a new account.

**Comment by elisolMS** [comment] 2020-04-27 16:59
Closing as it's not clear what the issue is here.

**Closed by elisolMS** 2020-04-27 16:59 UTC
