### ISSUE TITLE
China Office 365 cannot call this APi return 400 error

### ISSUE THREAD

**Issue by leapyear1969** [microsoftgraph/microsoft-graph-docs#5458] opened 2019-08-16 08:39 UTC
China Office 365 cannot call this APi return 400 error
refer to this link:
https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http 

**Request:**
GET https://microsoftgraph.chinacloudapi.cn/v1.0/me/licenseDetails HTTP/1.1

**Response:**

HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
request-id: 7e1af626-ebdb-4386-8932-a915ad1c1be4
client-request-id: 7e1af626-ebdb-4386-8932-a915ad1c1be4
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"China East","Slice":"SliceC","Ring":"6","ScaleUnit":"000","RoleInstance":"AGSFE_IN_2","ADSiteName":"CNE"}}
Duration: 71.2818
Strict-Transport-Security: max-age=31536000
Date: Fri, 16 Aug 2019 08:31:49 GMT
Content-Length: 305
{
  "error": {
    "code": "Request_BadRequest",
    "message": "Could not find a property named 'businessPhones' on type 'Microsoft.DirectoryServices.LicenseDetail'.",
    "innerError": {
      "request-id": "7e1af626-ebdb-4386-8932-a915ad1c1be4",
      "date": "2019-08-16T08:31:49"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47a77f89-96d9-7272-3fac-eede08243fff
* Version Independent ID: 297600a1-2f38-1e7a-c86f-425b8c7b28e1
* Content: [licenseDetails resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/licensedetails?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/licensedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/licensedetails.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @PatAltimore
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment] 2020-01-10 23:29
@davidmu1 who owns this page from an identity side?

**Comment by davidmu1** [comment] 2020-02-25 00:07
Not able to reproduce the error. Closing the issue. If there is a change identified for the contents of the page, please reopen the issue and list the change.

**Closed by davidmu1** 2020-02-25 00:07 UTC

**Comment by leapyear1969** [comment] 2020-02-26 04:50
@davidmu1 thanks, i think this issue has been fixed.
