### ISSUE TITLE
MeetingAttendanceReport returns 403 forbidden

### ISSUE THREAD

**Issue by ainaravo** [microsoftgraph/microsoft-graph-docs#13371] opened 2021-07-05 08:48 UTC
Hi,

I would be interested in using the MeetingAttendanceReport endpoint but am systematically getting a 403 forbidden error. I have provided https://graph.microsoftonline.com/ as resource when generating my OAuth token. Curiously when I provide 00000003-0000-0000-c000-000000000000 as resource, the call succeeds.

- I have tested the call with delegated permissions
- The delegated permission OnlineMeetings.ReadWrite is set on the application
- I'm using a token that has been generated with the meeting organizer's credentials

Did I miss something in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9593d8-ed60-527f-c549-b22dce5adbd9
* Version Independent ID: cdf36bed-fd4f-8be7-918c-6cdf74258676
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http#example-6-retrieve-the-attendance-report-of-a-meeting)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ffactory-ofcl** [comment] 2021-07-05 09:07
"Only the meeting organizer can access meeting attendance reports." [Source](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http). Could that be the reason?

**Comment by ainaravo** [comment] 2021-07-05 09:13
> "Only the meeting organizer can access meeting attendance reports." [Source](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http). Could that be the reason?

Thanks for your reply. I have indeed used the meeting organizer credentials to generate the token.

**Comment by frankpeng7** [comment] 2021-07-07 17:33
Hi @ainaravo can you confirm when did this happen? It sounds like a duplicate of #12670 which should already have been fixed. If it still persists recently, please provide the following information from the response headers so that I can take a look:
1. response datetime
2. client-request-id

**Comment by ainaravo** [comment] 2021-07-08 13:21
> Hi @ainaravo can you confirm when did this happen? It sounds like a duplicate of #12670 which should already have been fixed. If it still persists, please provide the following information from the response headers so that I can take a look:
> 
> 1. response datetime
> 2. client-request-id

Hi,

The issue still persists for me.
Below the response headers:

403 : Forbidden
HTTP/1.1 403 Forbidden
Transfer-Encoding : chunked
Strict-Transport-Security : max-age=31536000
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"North Europe","Slice":"E","Ring":"4","ScaleUnit":"003","RoleInstance":"DB1PEPF000092F7"}}
client-request-id : 63227276-ed0c-46b0-9f3c-182e78933b2f
scenario-id : 6e9e1b7e-a34f-4938-8b1c-3eaf3fa0f536
request-id : 63227276-ed0c-46b0-9f3c-182e78933b2f
Date : Thu, 08 Jul 2021 13:18:35 GMT
Content-Type : application/json
{
  "error": {
    "code": "Forbidden",
    "message": "Forbidden",
    "innerError": {
      "date": "2021-07-08T13:18:35",
      "request-id": "63227276-ed0c-46b0-9f3c-182e78933b2f",
      "client-request-id": "63227276-ed0c-46b0-9f3c-182e78933b2f"
    }
  }
}

Thank you!

**Comment by frankpeng7** [comment] 2021-07-12 20:53
Hi @ainaravo the accepted audience is `https://graph.microsoftonline.com` (without the ending slash). Unfortunately this is a strict matching. Can you try and set the audience without the ending slash?

**Comment by ainaravo** [comment] 2021-07-12 21:21
Hi,

I confirm it works without the ending slash. Thank you!

So I'm a bit puzzled because the same token (with audience https://graph.microsoftonline.com/) works for all the other endpoints I'm calling.
example : 
GET https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$count=true&$filter=isRead+eq+false&$top=100&$select=id
Response code 200, OK

Should I assume that the correct audience is https://graph.microsoftonline.com for all other endpoints too?

**Comment by frankpeng7** [comment] 2021-07-12 21:24
@ainaravo thanks for bringing this up. In that case I've logged this issue in our backlog. It should be a quick fix (to support with ending slash). I'll update this thread when it's done.

**Comment by frankpeng7** [comment] 2021-07-27 07:07
The fix was deployed by the end of last week.

**Closed by frankpeng7** 2021-07-27 07:07 UTC
