### ISSUE TITLE
 Wrong response for the Creation of solo events in the past

### ISSUE THREAD

**Issue by jasondoong** [microsoftgraph/microsoft-graph-docs#6324] opened 2019-11-15 08:58 UTC
Steps to reproduce:
1. Create a solo event in the past in a calendar. 
2. Query calendarView/delta api

Result:
Shows @Removed in the response of calendarView/delta api

Expect result:
Should not indicate that an event was removed.
Instead, should indicate that an event was created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da37d83f-dd2b-dd85-eb5d-75208e26412d
* Version Independent ID: aa5f5279-bec8-fe6e-ab1b-8dc87f2ed688
* Content: [Get incremental changes to events in a calendar view  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http#feedback)
* Content Source: [concepts/delta-query-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-events.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by datenpol** [comment] 2019-12-04 11:14
I have the same Issue.

Steps to reproduce:
I use a delta-Call to sync all events between 2019-01-01 and 2019-12-13.
Now I create a new event on 2020-01-01.
Now I fetch the delta-Sync.

Result:
I reveice a "deleted" event.

Expected Result:
I do not get any event since it is outside my delta window.

**Comment by datenpol** [comment] 2020-04-14 13:14
is there any Update or an expected closing date for this ticket?

**Comment by Harini84** [comment] 2020-06-23 10:35
Please use updateEvent which accepts 'Attendee' collection in request body for update:
https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http

Thanks

**Comment by Harini84** [comment] 2020-09-30 03:57
Fix in delta related to the scenario where event is being created in the past is not prioritized.

**Closed by Harini84** 2020-09-30 03:57 UTC
Labels: area: outlook events
