### ISSUE TITLE
POST /roleManagement/directory/roleEligibilityScheduleRequests allows extension beyond a year

### ISSUE THREAD

**Issue by glennvanrymenant-tc** [microsoftgraph/microsoft-graph-docs#16359] opened 2022-03-30 21:23 UTC
I was able to extend an eligible assignment beyond a year which isn't possible in the Azure portal - I presume the API should also fail on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7358a7-bef5-a501-26b5-89052e95cc37
* Version Independent ID: 4164c086-118e-c3c5-bfca-78a3ccfa5f46
* Content: [Create unifiedRoleEligibilityScheduleRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests?view=graph-rest-beta&tabs=powershell)
* Content Source: [api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/unifiedroleeligibilityschedulerequest-post-unifiedroleeligibilityschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @japere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2022-04-12 09:10
Thank you @glennvanrymenant-tc for raising this issue. I'm repro'd the same scenario. Let me get back to you if this is intended as a workaround to the portal limitations.

**Comment by glennvanrymenant-tc** [comment] 2022-04-12 10:12
@FaithOmbongi great, let me know if there's anything I can assist with... - IMO allowing a bypass to the limitations in the portal would be a bad idea...  the reason a limitation was set is due to the sensitive nature of these assignments and they should be reviewed "frequently" rather than be assigned for prolonged periods of time.

**Comment by FaithOmbongi** [comment] 2022-04-13 11:01
Hi @glennvanrymenant-tc - I've confirmed that this behavior is the default setting defined for the specific role. You can change the setting to a 1-year maximum limit to suit your scenario. So the API behavior aligns with the role settings.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/14026935/163166129-18f61388-f2c0-4594-8fc9-52fa4f480458.png">

**Why a different behavior on the portal?** The Azure portal team is currently investigating why the portal limits the assignment/eligibility to 1 year when the default setting may be allowing permanent assignments.

**Next step: To update role settings:** Unfortunately, Microsoft Graph currently doesn't support Write operations for the settings (exposed through the [role management policies](https://docs.microsoft.com/en-us/graph/api/resources/unifiedrolemanagementpolicy?view=graph-rest-beta) and [rules](https://docs.microsoft.com/en-us/graph/api/resources/unifiedrolemanagementpolicyrule?view=graph-rest-beta) APIs). You can only change the setting via the Azure portal. Please see [Configure Azure AD role settings in PIM](https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-how-to-change-default-settings) for additional guidance.

Closing this issue here because it's no longer an issue about Microsoft Graph documentation.

**Closed by FaithOmbongi** 2022-04-13 11:01 UTC
Labels: area: Azure AD, area: governance
