### ISSUE TITLE
Unclear in which cases `id` is not available in `Identity`

### ISSUE THREAD

**Issue by mpsijm** [microsoftgraph/microsoft-graph-docs#10425] opened 2020-10-26 12:30 UTC
Quote from the docs:

> In some circumstances, the unique identifier for the actor may not be available. In this case, the **displayName** property for the identity will be returned, but the **id** property will be missing from the resource.

What "circumstances" cause the `id` property to be missing?

For example, patching a DriveItem returns the `lastModifiedBy.user` Identity _with_ the `id` field (and also `displayName` and an undocumented `email` field), but querying a delta link that fetches this exact same change (by the exact same user) does _not_ include the `id` field (only `displayName` and `email`). This feels inconsistent to me, and I would like to understand why. (In case this is a bug, please redirect me to where I can report this, because I couldn't find the right place to do so)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86c75f2-a9c8-af58-e9c1-30579417348a
* Version Independent ID: 0b0cd088-c182-de7c-7216-57027b118c46
* Content: [Identity - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/identity?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identity.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by FaithOmbongi** [comment] 2021-09-06 11:59
Thank you @mpsijm for raising this issue and my apologies for the delayed response. 

As shared in the linked thread, both `id `and `email `properties of identity resource are nullable so they might be set to `null` in an object. Each API implements this OpenType resource differently with others returning the standard properties (`id` and/or `displayName`) whether null or not, and other APIs adding more properties to the object for example, createdDateTime. So, the behavior is not a bug.

If you feel both `id `and `displayName `should be required, you may file a feature request at [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) for further consideration. Closing this issue here.

**Closed by FaithOmbongi** 2021-09-06 11:59 UTC
Labels: area: azure/AAD
