### ISSUE TITLE
Delta query data retention

### ISSUE THREAD

**Issue by lightupdifire** [microsoftgraph/microsoft-graph-docs#4317] opened 2019-04-04 08:10 UTC
Hello,
When run "https://graph.microsoft.com/v1.0/directoryRoles/delta";
We do see there was someone "**@removed": {"reason": "deleted"**";
How long this entry, that user was deleted from role, will stay here in this query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb132338-f8bd-96ea-a691-93522daf9d81
* Version Independent ID: 8606af9d-0bea-eabb-3555-df121fcb6e29
* Content: [directoryRole: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-delta?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/directoryrole-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryrole-delta.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment] 2020-01-30 22:28
Closing as a duplicate of #2962

**Closed by baywet** 2020-01-30 22:28 UTC
Labels: area: azure/AAD, area: delta query
