### ISSUE TITLE
Is there a methods table missing here?

### ISSUE THREAD

**Issue by Jimnar** [microsoftgraph/microsoft-graph-docs#21861] opened 2023-06-28 22:37 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3679a597-5d65-581f-dbb4-d88b7ff96218
* Version Independent ID: 037178d6-3623-c14e-fa57-49888cb251d7
* Content: [agreementFile resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/agreementfile?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/agreementfile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/agreementfile.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @raprakasMSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment] 2023-07-03 19:18
@FaithOmbongi FYI

**Comment by FaithOmbongi** [comment] 2023-07-05 09:08
Closing as a duplicate of #21862

**Comment by FaithOmbongi** [comment] 2023-07-05 09:08
Closing as a duplicate of #21862

**Closed by FaithOmbongi** 2023-07-05 09:08 UTC
Labels: area: Azure AD, area: governance
