### ISSUE TITLE
UnAuthorize using application

### ISSUE THREAD

**Issue by zur250** [microsoftgraph/microsoft-graph-docs#7387] opened 2020-03-15 13:04 UTC
Hi,
I am tring to query this API endpoint using azure application.
I gave the application the relevant permissions but I am getting the following error:
Failed to call the Web Api: Unauthorized
Content: {
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"GraphTokenValidationFail\",\"message\":\"MS Graph token validation fail\",\"target\":null,\"details\":null,\"innerError\":null,\"instanceAnnotations\":[]}",
    "innerError": {
  }
}
Any idea what I am doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96a6a4a5-3932-8412-8d76-6a4d14ffa4e6
* Version Independent ID: f007865b-fae1-e2fe-957f-d346888aa377
* Content: [List governanceResources - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceresource-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/governanceresource-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceresource-list.md)
* Product: **microsoft-identitiy-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by shauliu** [comment] 2020-04-09 19:04
On first look, it seems like the problem is associated with the graph token. However, if you provide correlation id and timestamp, we can help you look into this.

**Comment by zur250** [comment] 2020-04-12 09:36
Content: {
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"GraphTokenValidationFail\",\"message\":\"MS Graph token validation fail\",\"target\":null,\"details\":null,\"innerError\":null,\"instanceAnnotations\":[]}",
    "innerError": {
      "request-id": "de6e38d5-6ac6-4a32-b04b-e4b6986e4e1d",
      "date": "2020-04-12T09:35:28"
    }
  }
}

is this one better?

**Comment by flederflick** [comment] 2020-07-16 11:27
Hello, Did you ever get a response after your last post? I'm having the same issue.
Script works fine with a query like 
`https://graph.microsoft.com/v1.0/users/<email>`

but when I use, for instance, https://graph.microsoft.com/beta/privilegedAccess/azureResources I'm receiving the same error as you.

Best regards,

Sidney

`{
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"GraphTokenValidationFail\",\"message\":\"MS Graph token validation fail\",\"target\":null,\"details\":null,\"innerError
\":null,\"instanceAnnotations\":[],\"typeAnnotation\":null}",
    "innerError": {
      "date": "2020-07-16T11:24:49",
      "request-id": "c9c4edeb-889e-4985-944b-ed299293a6cb"
    }
  }
}`

**Comment by zur250** [comment] 2020-07-16 12:05
nope :(

**Comment by lin404** [comment] 2020-10-20 10:21
I had the same problem. I found it is because I was using application permission token. The PIM Graph APIs worked when I use delegated permission token by following [the document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow)

As mentioned [here](https://github.com/MicrosoftDocs/azure-docs/issues/54262#issuecomment-626530286), PIM Graph API only work with delegated permission actually.

**Comment by FaithOmbongi** [comment] 2021-02-23 17:40
No updates identified for the page. Closing the issue.

**Closed by FaithOmbongi** 2021-02-23 17:40 UTC
