### ISSUE TITLE
Possible zoom level values ?

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/microsoft-graph-docs#9736] opened 2020-09-01 14:16 UTC
What are possible zoom level values for the file preview api ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a29472-2a4e-11f5-7111-7aa1c1dbc273
* Version Independent ID: bdbaa1b9-f60a-4774-2ec6-8f0ec77c1850
* Content: [driveItem: preview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-preview.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vukasinpetrovic** [comment] 2020-09-08 11:37
This is troubling me also. I particularly need the 'Window width' option and I was experimenting with values for that, but couldn't find that. 
Also, interesting thing is when I pass 1.0 for zoom, it sets it to 'window size', when I pass 2.0 it sets zoom to 200%. I could not find the logic behind it. Also tried 0.75, 1.0, 1.25, 1.5 neither of those work, but 2.0, 3.0, 4.0 work respectively for 200%, 300%, 400%. 
Can someone help us with this?
 neither

**Comment by vukasinpetrovic** [comment] 2020-09-14 06:27
@JeremyKelley Any updates? I'm don't wanna be pushy but my clients expected me to finish last week and this is the only thing holding me back. Can anyone help us with info for this zoom parameter values?

**Comment by Gransi** [comment] 2020-12-01 14:22
Duplicate of https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/138?

**Closed** 2021-09-21 21:00 UTC
Labels: subarea: files, Q&A
