### ISSUE TITLE
Page missing in reference side navigation

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#6422] opened 2019-11-26 13:20 UTC
This page is missing in the side navigation; I found a link just be coincidence on the "accesspackageassignmentresourcerole" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d8b182-bc72-55ee-ef28-28535005441d
* Version Independent ID: 90aa4108-5ac2-0c47-90b6-4f9350d3c675
* Content: [accessPackageResourceScope resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcescope?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/accesspackageresourcescope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/accesspackageresourcescope.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment] 2019-11-26 19:56
Hi, thanks for your feedback. It's by design that we don't expose all types in the TOC and some are accessible only via links. Closing this issue; feel free to reopen if you have additional feedback.

**Closed by Lauragra** 2019-11-26 19:56 UTC
