### ISSUE TITLE
'isAllDay' and 'dateTime' in all day event are not consistent

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1802] opened 2017-10-11 19:55 UTC
I used a test account to create an all day meeting request at Pacific Time Zone, and sent to myself through mail.

For the mail I got
```
GET https://graph.microsoft.com/beta/me/messages
```

```js
{
  "meetingMessageType": "meetingRequest",
  "isAllDay": false,           // <- wrong(?), should be true
  "sender": {},
  "toRecipients": [],
  "startDateTime": {
    "dateTime": "2017-10-12T07:00:00.0000000",   // <- correct(?)
    "timeZone": "UTC"
  },
  "endDateTime": {
    "dateTime": "2017-10-13T07:00:00.0000000",   // <- correct(?)
    "timeZone": "UTC"
  },
  // ...
}
```

For the event I got

```
GET https://graph.microsoft.com/v1.0/me/calendarview?startdatetime=2017-10-11T00:00:00Z&enddatetime=2017-10-14T00:00:00Z
```

```js
{
  "isAllDay": true,           // <- correct(?)
  "seriesMasterId": null,
  "showAs": "free",
  "start": {
    "dateTime": "2017-10-12T00:00:00.0000000",   // <- wrong(?), should be 2017-10-12T07:00:00.0000000
    "timeZone": "UTC"
  },
  "end": {
    "dateTime": "2017-10-13T00:00:00.0000000",   // <- wrong(?), should be 2017-10-12T07:00:00.0000000
    "timeZone": "UTC"
  },
  // ...
}
```

**Comment by jasonjoh** [comment] 2017-10-12 14:49
This is by design. All day events always return midnight-to-midnight regardless of time zone. If you need to know what time zone the user created this event in, you can check the `originalStartTimeZone` property and convert as you wish.

**Comment by Hongbo-Miao** [comment] 2017-10-18 22:56
Hi @jasonjoh please check again, the thing is the mail I got the event `isAllDay` and `dateTime` are not consistent.

**Comment by mlafleur** [comment] 2017-10-20 19:26
The email looks 100% correct to me. 

This is an event running from Oct. 12th @ 7:00 AM until Oct. 13th @ 7:00 AM. While this is 24 hrs long, it isn't "all day".  You could in theory have an even on 10-12 @ 6:00 AM and another on 10-13 @ 7:30 AM. Neither of these could conflict with this event. 

The event record however is simply wrong. This event (as it is recorded)  _wouldn't_ conflict with an event on 10-13 @ 6:00 AM when it clearly would. You're Busy bit will flip to Free a full 7 hrs earlier than it should (and kick in a full 7 hrs early). 

To be fair, I don't believe this is an issue with the REST API. The  All Day logic has been confusing/broken for as long as I can remember (possibly from the beginning?).

**Comment by JuForan** [comment] 2017-12-08 02:51
As mentioned above this is by design. What's the action item for me?

**Comment by Hongbo-Miao** [comment] 2017-12-08 05:41
It would be great to change one of them and make the time consistent.

**Comment by JuForan** [comment] 2017-12-11 17:41
Hi Hongbo, you can make a request like this in the UserVoice page: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=101632

**Comment by Hongbo-Miao** [comment] 2017-12-11 18:14
That is for feature request. (might not to be implemented depends on resources)
Since the two API returns the different conflicting results, I would call it a bug. (has to be fixed)

**Comment by ElizabethSamuel-MSFT** [comment] 2017-12-12 22:07
Closing as issue is being tracked through UserVoice. Thanks.

**Closed by ElizabethSamuel-MSFT** 2017-12-12 22:07 UTC
Labels: area: outlook
