### ISSUE TITLE
Attachment example not correct

### ISSUE THREAD

**Issue by lkirchev** [microsoftgraph/microsoft-graph-docs#9977] opened 2020-09-18 07:16 UTC
The Message.attachments field is not of type List<Attachment>, as written in the example. It is of type AttachmentColleactionPage, so it is not possible to assign value List<Attachment> to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572e47b6-e504-0918-fc06-11217eea40a4
* Version Independent ID: c30fd8a1-e913-0192-7405-d55232ea3703
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment] 2021-09-21 20:26
@isvargasmsft could you please take a look at this issue? Thanks

**Comment by isvargasmsft** [comment] 2021-10-04 19:25
Hello @lkirchev, 

Would you be so kind to clarify where exactly are you seeing the error? Please indicate:
1. Which example:
2. Which language:
3. Which section of the example exactly:

I checked in the topic but couldn't find the error you mentioned. 

Awaiting for your response,

Isaac Vargas

**Comment by lkirchev** [comment] 2021-10-05 06:58
Hello @isvargasmsft,

Sorry for the lame report - I should have provided more details. I just checked the documentation and it is fixed now. The Java sample code in Example 3 on https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java one year ago tried to assign the attachmentsList directly to message.attachments, which was not possible.

Kind regards,
Lazar

**Comment by isvargasmsft** [comment] 2021-10-05 14:12
@lkirchev, 

I am glad the issue is now resolved. My deepest apologies on behalf of Microsoft for the delays in our response. 

Please keep sharing feedback with us, we'll do our best to improve the response time in the future. 

Kind regards,

Isaac Vargas

**Closed by isvargasmsft** 2021-10-05 14:12 UTC
Labels: subarea: mail
