### ISSUE TITLE
List users including their last sign-in time

### ISSUE THREAD

**Issue by chrisbues** [microsoftgraph/microsoft-graph-docs#6973] opened 2020-01-31 19:55 UTC
This doesn't currently work. The service returns an error:
{
    "error": {
        "code": "",
        "message": "No HTTP resource was found that matches the request URI 'https://reportingservice.activedirectory.windowsazure.com/auditLogs/userSignInActivity/Default.Microsoft.AAD.Reporting.getByIds'.",
        "innerError": {
            "request-id": "fcbb3985-2d71-40f0-9710-578c9ae2c358",
            "date": "2020-01-31T19:51:18"
        }
    }
}

Also, there's an extra space in the example:
https://graph.microsoft.com/beta/users?$select=displayName,userPrincipalName, signInActivity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc2099e-c474-a648-60bb-4520f9fa1d23
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http#example-3--list-users-including-their-last-sign-in-time)
* Content Source: [api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by misteriks** [comment] 2020-02-05 09:26
I'm seeing the same issue when using signInActivity as select parameter on the beta endpoint

**Comment by dkershaw10** [comment] 2020-04-04 19:33
This should be working properly now.  Please give it a spin.

**Comment by davidmu1** [comment] 2020-09-01 22:25
Cannot reproduce the issue. No change identified for the page. Closing the issue.

**Closed by davidmu1** 2020-09-01 22:25 UTC
Labels: area: azure/AAD
