### ISSUE TITLE
Filtering TeamChat in List Messages

### ISSUE THREAD

**Issue by RanjithVenkat** [microsoftgraph/microsoft-graph-docs#7202] opened 2020-02-26 07:36 UTC
Microsoft Team Chat messages are also returned in /me/messages. Also, couldnt get FolderName for the parentFolderId returned for TeamChat messages. 
Seems there is no option to filter messages only from Outlook. Can we have filter support for this case ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0169c1-e6e7-da8f-4158-5e721eae8b9a
* Version Independent ID: f2907cde-b9d7-4ba7-e813-047e5b938e50
* Content: [List messages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment] 2020-02-26 23:47
@svpsiva , can you please clarify the intended API design, and subsequently we can see if we can clarify the docs? Thanks.

**Comment by heinrich-ulbricht** [comment] 2020-03-05 10:06
I have the opposite requirement: I'd like to really get all messages from this endpoint `/me/messages` endpoint, including Teams.

I'd like to get this data from the API:
* Outlook messages (👍 works)
* Teams chat messages (👍 works)
* Teams channel mentions (👎 doesn't work)

Those filter I need:
* filter by source type: Outlook? Teams chat message? Teams channel message?
  * this could be used by @RanjithVenkat to get messages from Outlook only
* filter by mention for all message types (this is currently being introduced as preview using the `filter=MentionsPreview/IsMentioned` filter) - get all messages that explicitly mention me, oder are directly sent to me

The docs should make clear the current state:
* Which types of messages are returned by the endpoint? (apparently Outlook and Teams chat)
* How to filter for a specific source type (Outlook, Teams, ...)?
* Current state of the `MentionsPreview/IsMentioned` filter - this did not work for me at all, 
  * `MentionsPreview/IsMentioned` could be requested but was always empty
  * filtering for `MentionsPreview/IsMentioned` subsequently did not work

For the missing features (channel messages mentioning me) I might create a user voice. Depending on the updated documentation :)

**Comment by RanjithVenkat** [comment] 2020-03-11 06:05
@angelgolfer-ms @svpsiva : Any update on this request ?

**Comment by RanjithVenkat** [comment] 2020-03-11 06:06
Like @heinrich-ulbricht  mentioned, providing **filter by source** support the API solves the issue.

**Comment by ashoksubedi1** [comment] 2020-03-13 20:57
How are you guys getting messages in the Teams Chat with this API. All I am getting is OUtlook messages only. If someone could kindly suggest me the endpoint for getting Teams Chat Messages too or if not only Teams Chat Messages. https://graph.microsoft.com/beta/me/messages + ?

**Comment by angelgolfer-ms** [comment] 2020-03-14 00:43
@ashoksubedi1 , to get just chat messages in Microsoft Teams, please see [list chat messages](https://docs.microsoft.com/en-us/graph/api/chatmessage-list?view=graph-rest-beta). 

Per this [known issue](https://docs.microsoft.com/en-us/graph/known-issues?view=graph-rest-beta#get-messages-returns-chats-in-microsoft-teams), when one [gets user messages](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-beta), the user's Teams IM messages are included in the response, and these IM messages have "IM" in their subject.

Because this is documented as a "known issue", I'd let @svpsiva comment if anyone should rely on this behavior.

Please also note that Teams chats and chat messages are currently in preview available only in the beta endpoint. APIs in preview can change without prior notice, and therefore generally are not for production use.

@RanjithVenkat , @heinrich-ulbricht , I suggest you post your feature needs on [User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).

As for the problem with filter=MentionsPreview/IsMentioned filter, I'll try to identify and notify the current service owner.

**Comment by angelgolfer-ms** [comment] 2020-03-14 01:05
@simonhult , can you or someone on your team please take a look at the question @heinrich-ulbricht stated above about:
>>
Current state of the MentionsPreview/IsMentioned filter - this did not work for me at all,
I could request MentionsPreview/IsMentioned but this was always empty
filtering for MentionsPreview/IsMentioned subsequently did not work

For me, GET https://graph.microsoft.com/beta/me/messages?$filter=mentionsPreview/isMentioned eq true is returning HTTP 503

Thanks.

**Comment by angelgolfer-ms** [comment] 2020-03-17 22:09
Just an update - today, GET https://graph.microsoft.com/beta/me/messages?$filter=mentionsPreview/isMentioned eq true is working and returns HTTP 200.

**Comment by JefWight** [comment] 2020-03-17 22:21
To clarify and elaborate a bit more, mentionsPreview/isMentioned was only designed to support when a user is mentioned in an email, not any Teams scenarios.

@heinrich-ulbricht,
With regards to your previous comment:
> * Current state of the `MentionsPreview/IsMentioned` filter - this did not work for me at all,
>   
>   * I could request `MentionsPreview/IsMentioned` but this was always empty
>   * filtering for `MentionsPreview/IsMentioned` subsequently did not work

If you're having specific difficulty querying using this parameter, could you please provide further details?  What is the specific request / symptom of 'did not work'?

**Comment by heinrich-ulbricht** [comment] 2020-04-23 19:04
@JefWight 
"Did not work" means this:

> I could request MentionsPreview/IsMentioned but this was always empty

I never got any data back, even when requesting it and knowing there were mentions.

**Comment by ashoksubedi1** [comment] 2020-04-23 20:13
@angelgolfer-ms when you refer me to this list chat messages. It did not help, do you mind giving me the endpoint to get Team message  https://graph.microsoft.com/beta/me/messages + ?. If some how are able to filter only teams channel messages then all I want is the endpoint

**Comment by kumbhaj** [comment] 2020-05-07 08:37
**Here is the teams chat endpoint:**
https://graph.microsoft.com/beta/me/chats/***chat-id**/messages

**Comment by ashoksubedi1** [comment] 2020-05-07 15:18
@angelgolfer-ms  @svpsiva  @kumbhaj  same for me. Getting Subjet with "" response. Cannot filter the channel or team chat messages

**Comment by angelgolfer-ms** [comment] 2020-05-07 20:10
I see the few folks in this Github issue have questions on mail API, Teams API, @-mentions API, and some of them haven't got any traction; I apologize for the delay.

In general, FYI, Github issues are specifically for documentation-related problems, questions, or suggestions. I understand there's a fine line between docs being incomplete and not explaining the API behavior, and API behaving not as described by the docs. Nonetheless, for the latter type of issues, please open issues on Stackoverflow and tag them with "microsoft-graph", where the community, including external and Microsoft subject matter experts, can hopefully help and unblock you.

@ashoksubedi1 , @kumbhaj , if your purpose is to get all Teams messages, Teams chat messages, or Teams channel messages, and if your app finds that [list chat messages](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http) (of a user) and [list channel messages](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta) do not behave as you expect, please open a Stackoverflow issue. I wouldn't suggest relying on the behavior documented in the [known issue](https://docs.microsoft.com/en-us/graph/known-issues?view=graph-rest-beta#get-messages-returns-chats-in-microsoft-teams), as it's an unintended behavior which hopefully will be fixed at some point.

@RanjithVenkat , @heinrich-ulbricht , if you're not getting traction on the API behavior issues, I'd also suggest posting on Stackoverflow. 

And if folks have suggestions on how APIs should behave, please post your feature needs on [User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).

**Closed** 2021-10-01 22:28 UTC
Labels: subarea: mail, Q&A
