### ISSUE TITLE
Graph permissions

### ISSUE THREAD

**Issue by MichaelS4G** [microsoftgraph/microsoft-graph-docs#6248] opened 2019-11-07 16:33 UTC
The basic lookup of people seems to work with the permissions listed, but the headshot icons would disappear and the console was full of errors for graph calls to contacts. Giving permissions to Contacts.Read fixed the head shot issues and most of the errors, except those that are pulling from my personal contacts. They are still throwing errors. Tried Contacts.Read.Shared but that didn't help. So it seems the documentation should at least show the need for Contacts.Read, but may need more rights as well. Otherwise this looks really useful and much easier than manually building a people picker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20833be3-9f0c-0e13-b107-45df6f38944b
* Version Independent ID: 7aefbf92-5842-c84d-c38d-507495a9b970
* Content: [People-Picker component - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/components/people-picker#feedback)
* Content Source: [concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/components/people-picker.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @vogtn
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vogtn** [comment] 2020-01-10 19:13
Hi @MichaelS4G 

Sorry for not seeing this sooner! The issue you were experiencing at this time (Nov 7) seems to coincide with a issue we were having and have documented + fixed here: 

https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/217 

I'm not sure how the Contacts.Read permission would help, as the `people-picker` uses the `/me/people` Graph endpoint to query for users. This only requires `people.read`. 

[code here](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/master/src/Graph.ts#L106)


Can you retry with the latest microsoft-graph-toolkit updates? If the issue is persistent, I'd suggest we'd move to the issue to [Microsoft-Graph-Toolkit](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues) for better visibility. 

_P.S: Thanks for getting us to revisit this, found we needed to update the permissions [separate issue](https://github.com/microsoftgraph/microsoft-graph-docs/pull/6773)_

**Comment by lramosvea** [comment] 2021-09-14 17:39
@vogtn I see the documentation has been updated already but can you confirm if this issue has been fixed or if it is still open? Thanks.

**Comment by lramosvea** [comment] 2021-09-14 17:45
Closing this issue has documentation has been updated already.

**Closed by lramosvea** 2021-09-14 17:45 UTC
Labels: area: contacts
