### ISSUE TITLE
Resource property not found error

### ISSUE THREAD

**Issue by sumitmodi84** [microsoftgraph/microsoft-graph-docs#8063] opened 2020-05-05 15:45 UTC
I am trying to create subscription using application access token with Site.ReadWrite.All permission to the drive root endpoint. I am getting the following error for the same. Also, this is coming randomly. After trying multiple times, I am successfully able to create the subscription.

{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: BadRequest; Reason: The property 'Resource' does not exist on type 'oneDrive.subscription'. Make sure to only use property names that are defined by the type.]",
    "innerError": {
      "request-id": "baacc96d-de92-4ff4-a472-1a02d0d34faf",
      "date": "2020-05-05T13:57:24"
    }
  }
}

Following is the sample of the json i am using for creating notification
{
    "resource": "drives/{{driveid}}/root",
    "changeType": "updated",
    "clientState": "d8SmzUzgafh4R4QkWyWWQnNHQw2Hqgayrm2yde7J8yM=",
    "notificationUrl": "{{some valid url}}",
    "expirationDateTime": "2020-05-08T09:45:09.014Z"
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by caseypanzer** [comment] 2020-05-05 22:00
Same issue...the bot response is not helpful...

**Comment by sumitmodi84** [comment] 2020-05-06 04:27
Nope...going to raise to MS Support....Will post if something is found....
Also, caseypanzer please post if you find something

**Comment by baywet** [comment] 2020-05-06 12:15
reopening

**Comment by baywet** [comment] 2020-05-06 12:16
this seems to be an issue with the service, please keep raising support tickets, I'll try to raise something internally. 
For reference, similar issue on stack https://stackoverflow.com/questions/61624135/microsoft-graph-subscription-api-to-create-subscription-fails-with-status-code

**Comment by baywet** [comment] 2020-05-06 13:55
This is being investigated internally, please open support tickets if you haven't done so already and include the reference to ICM 187039005 in your ticket. This helps us understand the impact better :)

**Comment by baywet** [comment] 2020-05-06 16:20
The issue has been located in the service and the team is actively working to mitigate it!

**Comment by jessieli-ad** [comment] 2020-05-06 21:00
The issue has been mitigated by the service team.

**Comment by dbalve** [comment] 2020-05-06 22:54
I can confirm this issue appears to be resolved/mitigated.

**Comment by baywet** [comment] 2020-05-07 01:08
Thank you for confirming! Great community work everyone. Closing

**Closed** 2020-05-07 01:08 UTC
Labels: area: onedrive, area: webhooks, fixed, service, serviceissue
