### ISSUE TITLE
Unable to create a PLC Team via this method

### ISSUE THREAD

**Issue by ehussey** [microsoftgraph/microsoft-graph-docs#7234] opened 2020-02-28 19:15 UTC
This is the only way to have control over the group's email address (since it can't be specified during Team creation), but when I use the educationProfessionalLearningCommunity template in the POST to /teams, I get an error that says: 
"Team with template 'educationProfessionalLearningCommunity' can not be provisioned using a group missing the 'PLC' CreationOption."
I see no way to specify a CreationOption during group creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment] 2021-08-31 15:24
@ehussey - Could you please share the request body which you are sending in POST request.

I tried with below API call & request body and it's working fine for me:
https://graph.microsoft.com/beta/teams

Request body:
`{
    "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('educationProfessionalLearningCommunity')",
    "displayName": "My Class Team",
    "description": "My Class Team’s Description"
}`

Document link: [](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http#example-7-create-a-team-with-a-non-standard-base-template-type-with-extended-properties)

**Comment by v-chetsh** [comment] 2021-08-31 17:50
@ehussey -  Could you please close it as you are not able to reproduce this issue.

**Closed** 2021-08-31 17:52 UTC
Labels: bug: documentation, teams: TACO, MSTeams-Developer-Support
