### ISSUE TITLE
Clarify owners capability for different group types

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#10763] opened 2020-11-20 17:01 UTC
For DLs (Exchange managed) and on-premise managed...
There may be other topics that need updating too, and you might also consider putting this in known issues.

Comes from a customer support case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e98ce-6e59-6480-71a4-53065dfdad7b
* Version Independent ID: ad9de78d-b6e2-dd46-051c-d7d4de51ac0a
* Content: [List owners - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-owners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cpunella** [comment] 2020-12-04 16:18
Hi, 

we opened this bug due to Graph API is not correctly exposing owners from Distribution Lists. Talking with the support they said: 

"Exchange-mastered groups and on-prem synced groups use managedBy and coManagedBy and these fields are not mapped to owners when these groups are synced to AAD. "

Any thought or ETA about it? Do you need any additional info?

Thanks

**Comment by FaithOmbongi** [comment] 2021-02-11 20:49
Duplicate of #6481
Page updated via PR #10376
No additional updates identified for the page. Closing the issue.

**Closed by FaithOmbongi** 2021-02-11 20:49 UTC
Labels: area: groups
