### ISSUE TITLE
Missing left menu sidebar all across graph.microsoft.io when site is viewed in English

### ISSUE THREAD

**Issue by panjkov** [microsoftgraph/microsoft-graph-docs#1790] opened 2017-10-08 07:50 UTC
Hi,

I just discovered today that the left sidebar with menu is missing all across graph.microsoft.io site when viewed in English. It is present when language is set to German. It was present last weekend. I’ve tested it on Edge and Chrome with resolution 1440x900

In my opinion, it should be there, as without it there is no other option to see different articles or to browse Graph API features/methods.

**Comment by Lauragra** [comment] 2017-10-08 14:40
Thanks for letting us know. We're looking into this now.

**Comment by mtillman** [comment] 2017-10-08 14:49
I'm checking this now.

**Comment by mtillman** [comment] 2017-10-08 15:12
@lauragra has opened a pr with a fix. Should be back to normal soon.

**Comment by mtillman** [comment] 2017-10-08 15:15
https://github.com/microsoftgraph/microsoft-graph-docs/pull/1791

**Comment by Lauragra** [comment] 2017-10-08 17:25
Looks like the issue is fixed now. Thanks again for bringing this to our attention.

**Closed by Lauragra** 2017-10-08 17:25 UTC
