### ISSUE TITLE
Navigation in the documentation is broken when using adblocker

### ISSUE THREAD

**Issue by fen4o** [microsoftgraph/microsoft-graph-docs#152] opened 2016-03-16 14:21 UTC
Hello,
Because most adblockers block http://c.microsoft.com/ms.js, when clicking on a link in the documentation, there is a Reference error and the user is navigated to the error page, making all navigation on the documentation page impossible:

`Uncaught ReferenceError: MscomCustomEvent is not defined`

This bug relates to the whole http://graph.microsoft.io/ site, and not to the documentation, so feel free to forward it to the team handling the website.

As a workaround I would suggest, that you wrap the 2 places, where MscomCustomEvent is called in try catch block.

**Comment by keyur32** [comment] 2016-03-18 22:21
Hello,

Sorry for any inconvenience this has caused.  Also, thank you for reporting the issue and recommending a fix. Our engineering team is on it and we'll report back when the issue is fixed.

thanks!

**Comment by keyur32** [comment] 2016-03-21 18:45
Hi there,  we are trying to reproduce this issue. Is there a particular ad blocker/browser that you are using?

**Comment by iambmelt** [comment] 2016-03-23 20:35
Just to jump in on this one with some extra information -- I was able to repro a break in the documentation by loading http://graph.microsoft.io and blocking [mixed content](https://developer.mozilla.org/en-US/docs/Security/Mixed_content) in my browser

![screen shot 2016-03-23 at 1 28 49 pm](https://cloud.githubusercontent.com/assets/990063/13999939/104a919e-f0fc-11e5-840c-2f053aac2743.png)
![screen shot 2016-03-23 at 1 29 28 pm](https://cloud.githubusercontent.com/assets/990063/13999944/14232ab0-f0fc-11e5-966c-cd28de9cddc9.png)

**Comment by iambmelt** [comment] 2016-03-23 20:38
Demo of break

![screen shot 2016-03-23 at 1 36 27 pm](https://cloud.githubusercontent.com/assets/990063/14000048/8e5e8bee-f0fc-11e5-956b-9b3c1de6a07d.png)

**Comment by rgregg** [comment] 2016-03-24 05:09
I hit this today as well, manifested slightly differently. When I click on the V1.0 header in the navigation bar (left side) I get redirected to a 404 page. On a browser without an ad blocker extension, the page loads normally. The error is the same: `Uncaught ReferenceError: MscomCustomEvent is not defined`

**Comment by fen4o** [comment] 2016-03-28 11:41
Hello, I'm running adblock origin and https://easylist-downloads.adblockplus.org/easyprivacy.txt - you see that c.microsoft.com is blocked there

**Comment by keyur32** [comment] 2017-01-13 21:27
Hi folks, verified with our team that this was fixed a while back. Closing this issue but let us know if you still see it.

**Closed by keyur32** 2017-01-13 21:27 UTC
