### ISSUE TITLE
Creating a subscription for a SharePoint List fails with 403 Forbidden when using application-only permissions

### ISSUE THREAD

**Issue by johnnycardy** [microsoftgraph/microsoft-graph-docs#7786] opened 2020-04-16 20:45 UTC
Under the `application` column, the permission `Sites.ReadWrite.All` is specified. But attempting to create a subscription with application-only permissions returns a 403 Forbidden error. Creating the subscription with the same request, but using Graph Explorer (delegated permissions) works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dannnnnnnnnnnnn** [comment] 2020-04-27 09:18
Any updates on that? I´m having the same issue.

**Comment by baywet** [comment] 2020-04-27 12:00
While we're waiting for the owner to respond, I do have a question for you. How are you obtaining the access token? Using client id + secret or using client id + certificate?

**Comment by johnnycardy** [comment] 2020-04-27 12:12
Good question 🙂
In my case, I can confirm I am using a certificate. In fact, I have never generated a client secret for this app.

**Comment by baywet** [comment] 2020-04-27 12:20
ok thanks! Because I know that SharePoint APIs do require a certificate authentication for some operations when using an app-only flow. I'll let @JeremyKelley take it from here.

**Comment by dannnnnnnnnnnnn** [comment] 2020-04-27 13:42
I'm using client id + secret, if it matters.

**Comment by simondevries** [comment] 2020-04-28 20:52
I get the same error. I've add Site.ReadWrite.All to my app registration and I am accessing my graph api via client secret. I have not yet tried using a certificate

**Comment by johnnycardy** [comment] 2020-04-28 21:32
@simondevries details for configuring a certificate are [here](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread), although it's unnecessarily complex since you can use keyvault to generate a certificate for you.

**Comment by ejalbertinfoej** [comment] 2020-06-18 13:57
Same exact problem here, no answer anywhere?  someone have a workaround?

**Comment by martinvillysson** [comment] 2020-06-25 09:52
I'm also experiencing the same issue

**Comment by chackman** [comment] 2020-07-08 18:50
Could you please provide the following response headers corresponding to your request(s):
> - Date (in UTC, please)
> - request-id
> - SPRequestGuid (for requests made to OneDrive for Business)

**Comment by JeremyKelley** [comment] 2020-07-24 18:16
Bumping the discussion here, are there request IDs available for the failing operations?  We are unable to reproduce internally and without this information we can't really investigate further.

Thanks!

**Comment by johnnycardy** [comment] 2020-07-24 19:16
Thanks @JeremyKelley for the reminder. I had actually parked this project but I've got the old code up and running to get some output.

Request Uri:
`https://graph.microsoft.com/v1.0/subscriptions`

Request body:
`
{"changeType":"updated","notificationUrl":"https://<redacted>.azurewebsites.net/Trigger/ListSubscriptionNotify","resource":"sites/<redacted>.sharepoint.com,4ff19269-f6b0-41d1-b961-024d0a9bb212,8437e6b9-45f4-4e7b-804d-0c921eca79ba/lists/2c014d6d-7e3e-4841-a159-a04baa102434","expirationDateTime":"2020-07-25T19:07:27.9028664Z","clientState":"{\"ListSubscriptionId\":0}"}
`
Request headers:
`Authorization: Bearer eyJ0eXAiO....<redacted>`

Response body:
```
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access denied. You do not have permission to perform this action or access this resource.]",
    "innerError": {
      "date": "2020-07-24T19:07:37",
      "request-id": "4b29703e-f6b9-4c77-9b9a-30f6d6143e44"
    }
  }
}

```

Response status code: `403 Forbidden`

Response headers:
```
Cache-Control: private,
request-id: 4b29703e-f6b9-4c77-9b9a-30f6d6143e44,
client-request-id: 4b29703e-f6b9-4c77-9b9a-30f6d6143e44,
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"4","ScaleUnit":"005","RoleInstance":"AGSFE_IN_5"}},
Strict-Transport-Security: max-age=31536000,
Date: Fri, 24 Jul 2020 19:07:36 GMT
```

**Comment by stefanheimann** [comment] 2020-08-05 12:41
Any updates on this? I've exactly the same problem using client secret to create the token.

Thats the decoded token:
```
{
  "typ": "JWT",
  "nonce": "",
  "alg": "RS256",
  "x5t": "",
  "kid": ""
}.{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/606f4517-9cad-43bb-973f-2647f76724be/",
  "iat": 1596630507,
  "nbf": 1596630507,
  "exp": 1596634407,
  "aio": "",
  "app_displayname": "",
  "appid": "",
  "appidacr": "",
  "idp": "",
  "oid": "",
  "roles": [
    "Sites.ReadWrite.All",
    "Files.ReadWrite.All"
  ],
  "sub": "",
  "tenant_region_scope": "",
  "tid": "",
  "uti": "",
  "ver": "1.0",
  "xms_tcdt": 1593517741
}
```

**Comment by chackman** [comment] 2020-08-05 17:11
@baywet the failures appear to be in the Graph webhooks service; should investigation continue on the Graph side?

**Comment by baywet** [comment] 2020-08-05 17:41
@chackman I looked into it and I'm indeed getting the same error in subscription creation.
However, if with the same token (app-only, w/ Sites.ReadWrite.All) on `GET /drive/root` and I'm getting the following error. My guess is that this is what's making subscription service fail, but subscription service is not translating the error properly. Can you look into it please?
```json
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "CompactToken parsing failed with error code: 80049217",
    "innerError": {
      "date": "2020-08-05T17:37:05",
      "request-id": "2e2ea5f2-ada1-400e-a0ec-325cb6a460d1"
    }
  }
}
```

**Comment by chackman** [comment] 2020-08-05 17:52
@baywet this looks like Graph rejected the token (so probably an auth question as opposed to webhooks); this was a request to the Graph service right?

**Comment by baywet** [comment] 2020-08-05 17:55
this is `GET https://graph.microsoft.com/v1.0/drive/root`

**Comment by chackman** [comment] 2020-08-05 17:58
Given the information that we have, this looks like a more general auth issue with Graph and does not appear to be a webhooks or SharePoint issue. Can someone on the Graph side pick up the investigation?

**Comment by johnnycardy** [comment] 2020-08-05 18:09
@chackman @baywet this may or may not be useful information, but I'll add it anyway:

My workaround was to create an app-only token for SharePoint, and create a webhook directly via the SharePoint API. Which worked fine.

**Comment by baywet** [comment] 2020-08-05 18:19
@chackman do we already have an ICM for that?

**Comment by chackman** [comment] 2020-08-05 19:25
@baywet no we do not currently have an ICM

**Comment by baywet** [comment] 2020-08-05 19:26
do you mind opening it? since it's a SharePoint permission issue on MS Graph? I think it'll be better if you drive the conversation here.

**Comment by stefanheimann** [comment] 2020-08-06 14:37
Here's a simplified code snippet of what I'm trying to achive using Laravel and Microsoft Graph SDK for PHP, maybe it helps

```
$response = Http::asForm()
    ->withHeaders([
        'Host' => 'login.microsoftonline.com',
        'Content-Type' => 'application/x-www-form-urlencoded'
    ])
    ->post("https://login.microsoftonline.com/" . config('oauth.microsoft.tenantId') . "/oauth2/v2.0/token",
        [
            'client_id' => config('oauth.microsoft.clientId'),
            'scope' => 'https://graph.microsoft.com/.default',
            'client_secret' => config('oauth.microsoft.clientSecret'),
            'grant_type' => 'client_credentials'
        ]);

$token = $response->json()['access_token'];

try {
    $graphResponse = (new Graph)
        ->setAccessToken($token)
        ->createRequest('POST', '/subscriptions')
        ->attachBody([
            'changeType' => 'updated',
            'notificationUrl' => 'https://xxx.ngrok.io/api/webhook/microsoft',
            'resource' => '/drive/root',
            'expirationDateTime' => Carbon::now('UTC')->addMinutes(4200)->toISOString()
        ])
        ->execute();
} catch (Exception $e) {
    ...
}
```

**Comment by johnnycardy** [comment] 2020-08-06 14:39
@stefanheimann you're using a client secret, not a certificate, so an error would be expected I think.

**Comment by stefanheimann** [comment] 2020-08-06 14:47
As I'm building a multi-tenancy application I don't think it's appropriate to use a certificate here. The app should also be usable for accounts outside of the organization I'm in. As far as I understood the concept, this wouldn't be possible using a certificate, right?

**Comment by johnnycardy** [comment] 2020-08-06 14:51
Certificates vs secret isn't related to multi tenant vs single tenant.

All graph operations support tokens generated using a certificate but some sharepoint operations don't support app tokens generated using a secret.

You should try to switch to using a certificate but I don't know how complex that is in PHP.

**Comment by baywet** [comment] 2020-08-10 12:04
@chackman FYI another customer impacted by this https://stackoverflow.com/q/63261811/3808675

**Comment by chackman** [comment] 2020-08-10 20:04
@baywet created an IcM

**Comment by aneeshbhat23** [comment] 2020-08-17 08:49
Even I get   **`Operation: Create; Exception: [Status Code: Forbidden; Reason: Access denied]`**   while trying to subscribe to `/me/drive/root/` resource. I tried this in Graph Explorer.

```
{
    "changeType": "updated",
    "notificationUrl": "https://my.notification.webhook/",
    "resource": "/me/drive/root/",
    "expirationDateTime": "2020-08-17T08:45:56.397732Z",
    "clientState": "CLIENT_STATE"
}
```


I was able to subscribe to **Outlook message** and it worked as expected...

**Comment by mwiedemeyer** [comment] 2020-09-08 12:47
Any chance that this will be fixed soon? Or should we prepare to build a workaround?

**Comment by johnnycardy** [comment] 2020-09-08 14:03
@mwiedemeyer a potential workaround is to subscribe with SharePoint directly. It's very similar, but bypassing Graph: https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/lists/create-subscription

**Comment by mwiedemeyer** [comment] 2020-09-08 14:21
Yes, I know. However I'm trying to use the new EventHubs feature (https://docs.microsoft.com/en-us/graph/change-notifications-delivery) and SharePoint does not support `EventHub:` notification urls. So that is not an option. Maybe I could switch to delegated permissions, but that will require to add an account to a lot of sites.

**Comment by gricey92** [comment] 2020-09-17 16:03
Azure Support have confirmed this should now be fixed. It began working in our tenant at 21:00 UTC yesterday.

**Comment by lsnider** [comment] 2020-11-03 17:13
Although it says fixed, I'm having this issue now too.  Tried both in code and graph explorer.  Ensured the scopes were correct.  Any debugging I can provide to help troubleshoot?

**Closed** 2021-11-03 01:01 UTC
Labels: area: sharepoint, bug: product, needs more info, area: webhooks, no recent activity
