### ISSUE TITLE
Got "ErrorQuotaExceeded" for HTTP GET request. Is it normal?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2927] opened 2018-07-31 07:53 UTC
Hello.

I requested messages for some mailbox with Microsoft Graph API. Request (I removed userId for privacy reason): `GET https://graph.microsoft.com/beta/Users/userId/MailFolders%28%27RecoverableItemsPurges%27%29/messages/delta?%24expand=attachments `

For this request I got as response this:
`ReplyBodyError: { ErrorCode: "ErrorQuotaExceeded", ErrorMessage: "Mailbox has exceeded maximum mailbox size." }"`

Is it normal that for `GET` request we can got quota exceeded error?

Thank you.

**Comment by jthake-msft** [comment] 2018-07-31 15:49
@ArunMSFT @angelgolfer-ms  I couldnt' see anything in our docs here on this . Is there any guidance here?

**Comment by jthake-msft** [comment] 2018-08-01 17:30
From an internal discussion, this is expected. If you would like read access to mailboxes that have exceeded quota, please raise that as a feature request. https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis

**Comment by ZaMaZaN4iK** [comment] 2018-08-01 17:49
Can you add please information about this behavior to the documentation?

**Comment by jthake-msft** [comment] 2018-08-01 17:59
@angelgolfer-ms  would we normally put this in the API ref or somewhere else in docs?

**Comment by angelgolfer-ms** [comment] 2018-08-02 23:07
@jthake-msft , replied you offline. :-)

**Comment by baywet** [comment] 2020-01-27 17:08
closing in favor of #5730 where the issue is already tracked by the team responsible for it

**Closed by baywet** 2020-01-27 17:08 UTC
Labels: area: outlook
