### ISSUE TITLE
List conversationMembers endpoint sometimes gives 504 Gateway Timeout

### ISSUE THREAD

**Issue by CaptainIanOnDuty** [microsoftgraph/microsoft-graph-docs#9908] opened 2020-09-14 02:32 UTC
### Bug
When requesting for this endpoint, sometimes it keeps pending for around 20 seconds.
Then it gives 504 response with the following body :
```
"error":{
         "code":"UnknownError",
         "message":"",
         "innerError":{
            "date":"2020-09-10T05:44:41",
            "request-id":"11467dbe-3096-492f-9e8c-16fa32730047",
            "client-request-id":"11467dbe-3096-492f-9e8c-16fa32730047" 
         }
      }
```

### Frequency

In average, 2/40 chats

### Noticed Behaviors

1. It doesn't always happen to specific chat, but more like random
2. Wait for some time and send the request again usually will give the expected response with 200

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment] 2020-09-15 06:56
We are  not able to reproduce it at our end. Could you please share request URL and Body?

**Comment by CaptainIanOnDuty** [comment] 2020-09-15 09:23
@Nikitha-MSFT 
Here is an curl command and its results which reproduced the issue.


```
curl -v -k -X GET 'https://graph.microsoft.com/beta/chats/19:0164dcd9-e664-4efa-9279-27775be1df15_440a0a47-9930-495e-a7bc-05fb60655dac@unq.gbl.spaces/members' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjNFNHZMbXQ0U09sREtXaWVlcDh0OVcxVzVPMkxDb3kxMmR0Q2lHSkZsd0UiLCJhbGciOiJSUzI1NiIsIng1dCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81MWFlZTBmMi0wODhkLTRkNjItYWE2Yi1lOGJjNTc3NTdjNDkvIiwiaWF0IjoxNjAwMTU3MzYzLCJuYmYiOjE2MDAxNTczNjMsImV4cCI6MTYwMDE2MTI2MywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyQmdZSmpJZnlOWGZYblR4MWZ5eTZzNk9IT09MenFSa0ZmUnA2NWhwZkRvUjlucDlJY0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6ImRldi10ZWFtcyIsImFwcGlkIjoiNDNjNjI2ZDItZGI1Yy00YzNhLTg0ZTQtZGY4NDNjZGRiNTE2IiwiYXBwaWRhY3IiOiIxIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTIyLjIxMi4xNTQuMTk0IiwibmFtZSI6IumdkuWxseS4gOmDjiIsIm9pZCI6IjAxNjRkY2Q5LWU2NjQtNGVmYS05Mjc5LTI3Nzc1YmUxZGYxNSIsInBsYXRmIjoiMTQiLCJwdWlkIjoiMTAwMzAwMDA5RDcxNzQzRiIsInJoIjoiMC5BQUFBOHVDdVVZMElZazJxYS1pOFYzVjhTZElteGtOYzJ6cE1oT1RmaER6ZHRSWldBR2suIiwic2NwIjoiQWNjZXNzUmV2aWV3LlJlYWQuQWxsIEFjY2Vzc1Jldmlldy5SZWFkV3JpdGUuQWxsIEFkbWluaXN0cmF0aXZlVW5pdC5SZWFkLkFsbCBBZG1pbmlzdHJhdGl2ZVVuaXQuUmVhZFdyaXRlLkFsbCBBZ3JlZW1lbnQuUmVhZC5BbGwgQWdyZWVtZW50LlJlYWRXcml0ZS5BbGwgQWdyZWVtZW50QWNjZXB0YW5jZS5SZWFkIEFncmVlbWVudEFjY2VwdGFuY2UuUmVhZC5BbGwgQW5hbHl0aWNzLlJlYWQgQXBwQ2F0YWxvZy5SZWFkV3JpdGUuQWxsIEF1ZGl0TG9nLlJlYWQuQWxsIEJvb2tpbmdzLk1hbmFnZS5BbGwgQm9va2luZ3MuUmVhZC5BbGwgQm9va2luZ3MuUmVhZFdyaXRlLkFsbCBCb29raW5nc0FwcG9pbnRtZW50LlJlYWRXcml0ZS5BbGwgQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ2hhdC5SZWFkIENoYXQuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWQgQ29udGFjdHMuUmVhZC5TaGFyZWQgQ29udGFjdHMuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWRXcml0ZS5TaGFyZWQgRGV2aWNlLkNvbW1hbmQgRGV2aWNlLlJlYWQgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZFdyaXRlLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5Qcml2aWxlZ2VkT3BlcmF0aW9ucy5BbGwgRGV2aWNlTWFuYWdlbWVudE1hbmFnZWREZXZpY2VzLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWRXcml0ZS5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZFdyaXRlLkFsbCBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRUFTLkFjY2Vzc0FzVXNlci5BbGwgRWR1QWRtaW5pc3RyYXRpb24uUmVhZCBFZHVBZG1pbmlzdHJhdGlvbi5SZWFkV3JpdGUgRWR1QXNzaWdubWVudHMuUmVhZCBFZHVBc3NpZ25tZW50cy5SZWFkQmFzaWMgRWR1QXNzaWdubWVudHMuUmVhZFdyaXRlIEVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZUJhc2ljIEVkdVJvc3Rlci5SZWFkIEVkdVJvc3Rlci5SZWFkQmFzaWMgRWR1Um9zdGVyLlJlYWRXcml0ZSBlbWFpbCBFV1MuQWNjZXNzQXNVc2VyLkFsbCBGYW1pbHkuUmVhZCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgRmluYW5jaWFscy5SZWFkV3JpdGUuQWxsIEdyb3VwLlJlYWQuQWxsIEdyb3VwLlJlYWRXcml0ZS5BbGwgSWRlbnRpdHlQcm92aWRlci5SZWFkLkFsbCBJZGVudGl0eVByb3ZpZGVyLlJlYWRXcml0ZS5BbGwgSWRlbnRpdHlSaXNrRXZlbnQuUmVhZC5BbGwgSWRlbnRpdHlSaXNrRXZlbnQuUmVhZFdyaXRlLkFsbCBJZGVudGl0eVJpc2t5VXNlci5SZWFkLkFsbCBJZGVudGl0eVJpc2t5VXNlci5SZWFkV3JpdGUuQWxsIEluZm9ybWF0aW9uUHJvdGVjdGlvblBvbGljeS5SZWFkIE1haWwuUmVhZCBNYWlsLlJlYWQuU2hhcmVkIE1haWwuUmVhZEJhc2ljIE1haWwuUmVhZFdyaXRlIE1haWwuUmVhZFdyaXRlLlNoYXJlZCBNYWlsLlNlbmQgTWFpbC5TZW5kLlNoYXJlZCBNYWlsYm94U2V0dGluZ3MuUmVhZCBNYWlsYm94U2V0dGluZ3MuUmVhZFdyaXRlIE1lbWJlci5SZWFkLkhpZGRlbiBOb3Rlcy5DcmVhdGUgTm90ZXMuUmVhZCBOb3Rlcy5SZWFkLkFsbCBOb3Rlcy5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBOb3Rlcy5SZWFkV3JpdGUuQ3JlYXRlZEJ5QXBwIE5vdGlmaWNhdGlvbnMuUmVhZFdyaXRlLkNyZWF0ZWRCeUFwcCBvZmZsaW5lX2FjY2VzcyBPblByZW1pc2VzUHVibGlzaGluZ1Byb2ZpbGVzLlJlYWRXcml0ZS5BbGwgb3BlbmlkIFBlb3BsZS5SZWFkIFBlb3BsZS5SZWFkLkFsbCBQb2xpY3kuUmVhZC5BbGwgUG9saWN5LlJlYWRXcml0ZS5Db25kaXRpb25hbEFjY2VzcyBQb2xpY3kuUmVhZFdyaXRlLlRydXN0RnJhbWV3b3JrIFByaXZpbGVnZWRBY2Nlc3MuUmVhZFdyaXRlLkF6dXJlQUQgUHJpdmlsZWdlZEFjY2Vzcy5SZWFkV3JpdGUuQXp1cmVSZXNvdXJjZXMgcHJvZmlsZSBQcm9ncmFtQ29udHJvbC5SZWFkLkFsbCBQcm9ncmFtQ29udHJvbC5SZWFkV3JpdGUuQWxsIFJlcG9ydHMuUmVhZC5BbGwgU2VjdXJpdHlBY3Rpb25zLlJlYWQuQWxsIFNlY3VyaXR5QWN0aW9ucy5SZWFkV3JpdGUuQWxsIFNlY3VyaXR5RXZlbnRzLlJlYWQuQWxsIFNlY3VyaXR5RXZlbnRzLlJlYWRXcml0ZS5BbGwgU2l0ZXMuRnVsbENvbnRyb2wuQWxsIFNpdGVzLk1hbmFnZS5BbGwgU2l0ZXMuUmVhZC5BbGwgU2l0ZXMuUmVhZFdyaXRlLkFsbCBTdWJzY3JpcHRpb24uUmVhZC5BbGwgVGFza3MuUmVhZCBUYXNrcy5SZWFkLlNoYXJlZCBUYXNrcy5SZWFkV3JpdGUgVGFza3MuUmVhZFdyaXRlLlNoYXJlZCBUaHJlYXRJbmRpY2F0b3JzLlJlYWRXcml0ZS5Pd25lZEJ5IFRydXN0RnJhbWV3b3JrS2V5U2V0LlJlYWQuQWxsIFRydXN0RnJhbWV3b3JrS2V5U2V0LlJlYWRXcml0ZS5BbGwgVXNlci5FeHBvcnQuQWxsIFVzZXIuSW52aXRlLkFsbCBVc2VyLlJlYWQgVXNlci5SZWFkLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgVXNlci5SZWFkV3JpdGUuQWxsIFVzZXJBY3Rpdml0eS5SZWFkV3JpdGUuQ3JlYXRlZEJ5QXBwIFVzZXJUaW1lbGluZUFjdGl2aXR5LldyaXRlLkNyZWF0ZWRCeUFwcCBXb3JrZm9yY2VJbnRlZ3JhdGlvbi5SZWFkLkFsbCBXb3JrZm9yY2VJbnRlZ3JhdGlvbi5SZWFkV3JpdGUuQWxsIiwic3ViIjoiSUVJajZjbVBtUERaVmZTd2liZTJmU09jYmk0QjhpRUxWMDR6M01RV1daTSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6IjUxYWVlMGYyLTA4OGQtNGQ2Mi1hYTZiLWU4YmM1Nzc1N2M0OSIsInVuaXF1ZV9uYW1lIjoidGVzdDAxQGVqYW50ZXN0Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InRlc3QwMUBlamFudGVzdC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiI5d0cxRUxJS2NFR2Z0d1c0TVhnZEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjEzMTQ2NzA1Mjl9.VV7AFBZ3lZap9DtL7P1yRv6RehI-RWrBK1VtGa4RbwrHt4QrYqX6GpVq5D3r48UbPa1ZU23eLsOuGAHjbl_qmyn0Xl_a6e4bov7jXbL4uRD22onau6U3CrR-hEmbYlRFAdx76wrdGOai8h5oZpSdTwkw_VNk6o1hPquIuSWmYjd2KPqDMZ3NaNqJIUkwIc6Z3_Pw01FD2cIiiAoY27STcsfd7L5wTKHZzzHRdNOcE3Y_3pbNZ3tHa6s8oP1Wa1hUFZKd-n6D1Hw_w8FY6yrE1aOC0Cg2O4h0k_zbwTVrNABZUmS4n-1TEOOY3M9I4PlyQekKBv6I7qumd7ClIiU2qQ'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 20.190.141.179...
* TCP_NODELAY set
* Connected to graph.microsoft.com (20.190.141.179) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=graph.microsoft.com
*  start date: Jul  1 21:47:19 2020 GMT
*  expire date: Jul  1 21:47:19 2022 GMT
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 5
*  SSL certificate verify ok.
> GET /beta/chats/19:0164dcd9-e664-4efa-9279-27775be1df15_440a0a47-9930-495e-a7bc-05fb60655dac@unq.gbl.spaces/members HTTP/1.1
> Host: graph.microsoft.com
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjNFNHZMbXQ0U09sREtXaWVlcDh0OVcxVzVPMkxDb3kxMmR0Q2lHSkZsd0UiLCJhbGciOiJSUzI1NiIsIng1dCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0ZxUms0SzRndyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81MWFlZTBmMi0wODhkLTRkNjItYWE2Yi1lOGJjNTc3NTdjNDkvIiwiaWF0IjoxNjAwMTU3MzYzLCJuYmYiOjE2MDAxNTczNjMsImV4cCI6MTYwMDE2MTI2MywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyQmdZSmpJZnlOWGZYblR4MWZ5eTZzNk9IT09MenFSa0ZmUnA2NWhwZkRvUjlucDlJY0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6ImRldi10ZWFtcyIsImFwcGlkIjoiNDNjNjI2ZDItZGI1Yy00YzNhLTg0ZTQtZGY4NDNjZGRiNTE2IiwiYXBwaWRhY3IiOiIxIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTIyLjIxMi4xNTQuMTk0IiwibmFtZSI6IumdkuWxseS4gOmDjiIsIm9pZCI6IjAxNjRkY2Q5LWU2NjQtNGVmYS05Mjc5LTI3Nzc1YmUxZGYxNSIsInBsYXRmIjoiMTQiLCJwdWlkIjoiMTAwMzAwMDA5RDcxNzQzRiIsInJoIjoiMC5BQUFBOHVDdVVZMElZazJxYS1pOFYzVjhTZElteGtOYzJ6cE1oT1RmaER6ZHRSWldBR2suIiwic2NwIjoiQWNjZXNzUmV2aWV3LlJlYWQuQWxsIEFjY2Vzc1Jldmlldy5SZWFkV3JpdGUuQWxsIEFkbWluaXN0cmF0aXZlVW5pdC5SZWFkLkFsbCBBZG1pbmlzdHJhdGl2ZVVuaXQuUmVhZFdyaXRlLkFsbCBBZ3JlZW1lbnQuUmVhZC5BbGwgQWdyZWVtZW50LlJlYWRXcml0ZS5BbGwgQWdyZWVtZW50QWNjZXB0YW5jZS5SZWFkIEFncmVlbWVudEFjY2VwdGFuY2UuUmVhZC5BbGwgQW5hbHl0aWNzLlJlYWQgQXBwQ2F0YWxvZy5SZWFkV3JpdGUuQWxsIEF1ZGl0TG9nLlJlYWQuQWxsIEJvb2tpbmdzLk1hbmFnZS5BbGwgQm9va2luZ3MuUmVhZC5BbGwgQm9va2luZ3MuUmVhZFdyaXRlLkFsbCBCb29raW5nc0FwcG9pbnRtZW50LlJlYWRXcml0ZS5BbGwgQ2FsZW5kYXJzLlJlYWQgQ2FsZW5kYXJzLlJlYWQuU2hhcmVkIENhbGVuZGFycy5SZWFkV3JpdGUgQ2FsZW5kYXJzLlJlYWRXcml0ZS5TaGFyZWQgQ2hhdC5SZWFkIENoYXQuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWQgQ29udGFjdHMuUmVhZC5TaGFyZWQgQ29udGFjdHMuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWRXcml0ZS5TaGFyZWQgRGV2aWNlLkNvbW1hbmQgRGV2aWNlLlJlYWQgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudEFwcHMuUmVhZFdyaXRlLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkLkFsbCBEZXZpY2VNYW5hZ2VtZW50Q29uZmlndXJhdGlvbi5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5Qcml2aWxlZ2VkT3BlcmF0aW9ucy5BbGwgRGV2aWNlTWFuYWdlbWVudE1hbmFnZWREZXZpY2VzLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRNYW5hZ2VkRGV2aWNlcy5SZWFkV3JpdGUuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWQuQWxsIERldmljZU1hbmFnZW1lbnRSQkFDLlJlYWRXcml0ZS5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZC5BbGwgRGV2aWNlTWFuYWdlbWVudFNlcnZpY2VDb25maWcuUmVhZFdyaXRlLkFsbCBEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgRUFTLkFjY2Vzc0FzVXNlci5BbGwgRWR1QWRtaW5pc3RyYXRpb24uUmVhZCBFZHVBZG1pbmlzdHJhdGlvbi5SZWFkV3JpdGUgRWR1QXNzaWdubWVudHMuUmVhZCBFZHVBc3NpZ25tZW50cy5SZWFkQmFzaWMgRWR1QXNzaWdubWVudHMuUmVhZFdyaXRlIEVkdUFzc2lnbm1lbnRzLlJlYWRXcml0ZUJhc2ljIEVkdVJvc3Rlci5SZWFkIEVkdVJvc3Rlci5SZWFkQmFzaWMgRWR1Um9zdGVyLlJlYWRXcml0ZSBlbWFpbCBFV1MuQWNjZXNzQXNVc2VyLkFsbCBGYW1pbHkuUmVhZCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgRmluYW5jaWFscy5SZWFkV3JpdGUuQWxsIEdyb3VwLlJlYWQuQWxsIEdyb3VwLlJlYWRXcml0ZS5BbGwgSWRlbnRpdHlQcm92aWRlci5SZWFkLkFsbCBJZGVudGl0eVByb3ZpZGVyLlJlYWRXcml0ZS5BbGwgSWRlbnRpdHlSaXNrRXZlbnQuUmVhZC5BbGwgSWRlbnRpdHlSaXNrRXZlbnQuUmVhZFdyaXRlLkFsbCBJZGVudGl0eVJpc2t5VXNlci5SZWFkLkFsbCBJZGVudGl0eVJpc2t5VXNlci5SZWFkV3JpdGUuQWxsIEluZm9ybWF0aW9uUHJvdGVjdGlvblBvbGljeS5SZWFkIE1haWwuUmVhZCBNYWlsLlJlYWQuU2hhcmVkIE1haWwuUmVhZEJhc2ljIE1haWwuUmVhZFdyaXRlIE1haWwuUmVhZFdyaXRlLlNoYXJlZCBNYWlsLlNlbmQgTWFpbC5TZW5kLlNoYXJlZCBNYWlsYm94U2V0dGluZ3MuUmVhZCBNYWlsYm94U2V0dGluZ3MuUmVhZFdyaXRlIE1lbWJlci5SZWFkLkhpZGRlbiBOb3Rlcy5DcmVhdGUgTm90ZXMuUmVhZCBOb3Rlcy5SZWFkLkFsbCBOb3Rlcy5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBOb3Rlcy5SZWFkV3JpdGUuQ3JlYXRlZEJ5QXBwIE5vdGlmaWNhdGlvbnMuUmVhZFdyaXRlLkNyZWF0ZWRCeUFwcCBvZmZsaW5lX2FjY2VzcyBPblByZW1pc2VzUHVibGlzaGluZ1Byb2ZpbGVzLlJlYWRXcml0ZS5BbGwgb3BlbmlkIFBlb3BsZS5SZWFkIFBlb3BsZS5SZWFkLkFsbCBQb2xpY3kuUmVhZC5BbGwgUG9saWN5LlJlYWRXcml0ZS5Db25kaXRpb25hbEFjY2VzcyBQb2xpY3kuUmVhZFdyaXRlLlRydXN0RnJhbWV3b3JrIFByaXZpbGVnZWRBY2Nlc3MuUmVhZFdyaXRlLkF6dXJlQUQgUHJpdmlsZWdlZEFjY2Vzcy5SZWFkV3JpdGUuQXp1cmVSZXNvdXJjZXMgcHJvZmlsZSBQcm9ncmFtQ29udHJvbC5SZWFkLkFsbCBQcm9ncmFtQ29udHJvbC5SZWFkV3JpdGUuQWxsIFJlcG9ydHMuUmVhZC5BbGwgU2VjdXJpdHlBY3Rpb25zLlJlYWQuQWxsIFNlY3VyaXR5QWN0aW9ucy5SZWFkV3JpdGUuQWxsIFNlY3VyaXR5RXZlbnRzLlJlYWQuQWxsIFNlY3VyaXR5RXZlbnRzLlJlYWRXcml0ZS5BbGwgU2l0ZXMuRnVsbENvbnRyb2wuQWxsIFNpdGVzLk1hbmFnZS5BbGwgU2l0ZXMuUmVhZC5BbGwgU2l0ZXMuUmVhZFdyaXRlLkFsbCBTdWJzY3JpcHRpb24uUmVhZC5BbGwgVGFza3MuUmVhZCBUYXNrcy5SZWFkLlNoYXJlZCBUYXNrcy5SZWFkV3JpdGUgVGFza3MuUmVhZFdyaXRlLlNoYXJlZCBUaHJlYXRJbmRpY2F0b3JzLlJlYWRXcml0ZS5Pd25lZEJ5IFRydXN0RnJhbWV3b3JrS2V5U2V0LlJlYWQuQWxsIFRydXN0RnJhbWV3b3JrS2V5U2V0LlJlYWRXcml0ZS5BbGwgVXNlci5FeHBvcnQuQWxsIFVzZXIuSW52aXRlLkFsbCBVc2VyLlJlYWQgVXNlci5SZWFkLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgVXNlci5SZWFkV3JpdGUuQWxsIFVzZXJBY3Rpdml0eS5SZWFkV3JpdGUuQ3JlYXRlZEJ5QXBwIFVzZXJUaW1lbGluZUFjdGl2aXR5LldyaXRlLkNyZWF0ZWRCeUFwcCBXb3JrZm9yY2VJbnRlZ3JhdGlvbi5SZWFkLkFsbCBXb3JrZm9yY2VJbnRlZ3JhdGlvbi5SZWFkV3JpdGUuQWxsIiwic3ViIjoiSUVJajZjbVBtUERaVmZTd2liZTJmU09jYmk0QjhpRUxWMDR6M01RV1daTSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6IjUxYWVlMGYyLTA4OGQtNGQ2Mi1hYTZiLWU4YmM1Nzc1N2M0OSIsInVuaXF1ZV9uYW1lIjoidGVzdDAxQGVqYW50ZXN0Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InRlc3QwMUBlamFudGVzdC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiI5d0cxRUxJS2NFR2Z0d1c0TVhnZEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjEzMTQ2NzA1Mjl9.VV7AFBZ3lZap9DtL7P1yRv6RehI-RWrBK1VtGa4RbwrHt4QrYqX6GpVq5D3r48UbPa1ZU23eLsOuGAHjbl_qmyn0Xl_a6e4bov7jXbL4uRD22onau6U3CrR-hEmbYlRFAdx76wrdGOai8h5oZpSdTwkw_VNk6o1hPquIuSWmYjd2KPqDMZ3NaNqJIUkwIc6Z3_Pw01FD2cIiiAoY27STcsfd7L5wTKHZzzHRdNOcE3Y_3pbNZ3tHa6s8oP1Wa1hUFZKd-n6D1Hw_w8FY6yrE1aOC0Cg2O4h0k_zbwTVrNABZUmS4n-1TEOOY3M9I4PlyQekKBv6I7qumd7ClIiU2qQ
> 
< HTTP/1.1 504 Gateway Timeout
< Cache-Control: private
< Content-Type: application/json
< request-id: 173ca8ed-98ef-428a-b856-790b39f955c1
< client-request-id: 173ca8ed-98ef-428a-b856-790b39f955c1
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Japan East","Slice":"SliceC","Ring":"2","ScaleUnit":"002","RoleInstance":"AGSFE_IN_16"}}
< Strict-Transport-Security: max-age=31536000
< Date: Tue, 15 Sep 2020 08:41:49 GMT
< Content-Length: 266
< 
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-09-15T08:41:50",
      "request-id": "173ca8ed-98ef-428a-b856-790b39f955c1",
      "client-request-id": "173ca8ed-98ef-428a-b856-790b39f955c1"
    }
  }
* Connection #0 to host graph.microsoft.com left intact
```

**Comment by clearab** [comment] 2020-09-15 18:22
Are you sending this request against a very large team?

**Comment by CaptainIanOnDuty** [comment] 2020-09-16 01:19
@clearab 

The chat I used to reproduce response with 504 above has 2 members and around 20 messages only.

The organization owns around 250 users.
Only 20 of them are actively used in Teams.

The user is joined in :
15 chats
- 2 chats has 3 members
- The rest 13 chats have 2 members only
9 teams

**Comment by RamjotSingh** [comment] 2020-10-29 20:24
This should be fixed now.

**Closed by RamjotSingh** 2020-10-29 20:24 UTC
Labels: MSTeams-Developer-Support, area: teams

**Comment by akudhingra** [comment] 2020-11-10 20:02
@RamjotSingh can you please give some details on what the problem was and how it was fixed? I had the same problem for days and somehow this was magically fixed around October 28, 2020.

**Comment by Nikitha-MSFT** [comment] 2020-11-11 09:39
I issue is fixed. we Don't have ETA to share when it will be available.
