### ISSUE TITLE
Reactions have null value for displayName

### ISSUE THREAD

**Issue by ShaneOss** [microsoftgraph/microsoft-graph-docs#11164] opened 2021-01-04 09:40 UTC
User reactions to messages in conversations have null value for displayName.

E.g.
"reactions": [
                {
                    "reactionType": "like",
                    "createdDateTime": "2021-01-02T10:21:26.975Z",
                    "user": {
                        "application": null,
                        "device": null,
                        "conversation": null,
                        "user": {
                            "id": "4f53324c-0316-48eb-a0a5-804465b74b87",
                            **"displayName": null,**
                            "userIdentityType": "aadUser"
                        }
                    }
                }
            ]

Expected value would be displayName from the user object https://graph.microsoft.com/v1.0/users/4f53324c-0316-48eb-a0a5-804465b74b87
    "displayName": "Shane Morgan",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9f246d-9ee2-b7db-44a2-b92ae3cf9b65
* Version Independent ID: 4df830f9-3363-acf0-ba8b-f2290e1a4559
* Content: [Get a reply to a channel message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-get-messagereply.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jagadeesh-MSFT** [comment] 2021-03-24 09:16
Hi @ShaneOss, I am unable to repro your issue. I have tried the same query  https://graph.microsoft.com/v1.0/users/userid and I'm getting values for that. could you please refer below screenshots.
![image](https://user-images.githubusercontent.com/73812940/112284404-374eab00-8caf-11eb-9aaf-dd44b14066f5.png)
![image](https://user-images.githubusercontent.com/73812940/112284867-b5ab4d00-8caf-11eb-81d6-fcabe4386224.png)

**Comment by ShaneOss** [comment] 2021-03-24 11:02
Hi @Jagadeesh-MSFT ,
Sorry maybe I wasn't clear. When a reaction is provided for a message, the user who provided the action, their displayname has null value.

Example call: https://graph.microsoft.com/beta/chats/{conversationID}/messages/{MessageID}
Update your conversation ID and message ID.

![Reaction_User_null_displayname](https://user-images.githubusercontent.com/721254/112300111-9f6fb200-8cec-11eb-9d6f-3b44db24161c.png)

**Comment by Jagadeesh-MSFT** [comment] 2021-04-02 11:52
Hi @ShaneOss , thank for the insights, I am able to repro the issue and taking this for internal discussion with team.

**Comment by Jagadeesh-MSFT** [comment] 2021-04-05 10:02
Hi @ShaneOss, I have created [bug](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/1677733), our team is working on it. At present we don't have any ETA to share with you.

**Comment by ShaneOss** [comment] 2021-04-05 10:13
Thanks @Jagadeesh-MSFT

**Comment by ShaneOss** [comment] 2021-04-12 11:04
Hi @Jagadeesh-MSFT,

Would the same issue also affect a federated message being sent to another user? The federated user who sent the message has a blank value for displayname.

{
    "client-request-id": "27df38ca-c4fd-e11b-a29c-61b28e795c71",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "539eaa4c-d480-4055-b960-44e900781a24"
}


        {
            "id": "1618224277724",
            "replyToId": null,
            "etag": "1618224277724",
            "messageType": "message",
            "createdDateTime": "2021-04-12T10:44:37.724Z",
            "lastModifiedDateTime": "2021-04-12T10:44:37.724Z",
            "lastEditedDateTime": null,
            "deletedDateTime": null,
            "subject": null,
            "summary": null,
            "chatId": "19:internaluserid_federateduserid@fed.unq.gbl.spaces",
            "importance": "normal",
            "locale": "en-us",
            "webUrl": null,
            "channelIdentity": null,
            "policyViolation": null,
            "from": {
                "application": null,
                "device": null,
                "conversation": null,
                "user": {
                    "id": "5ad07744-fc83-4fe6-a3cc-10844fb7e253",
                    **"displayName": ""**,
                    "userIdentityType": "aadUser"
                }
            },
            "body": {
                "contentType": "text",
                "content": "21321323213"
            },
            "attachments": [],
            "mentions": [],
            "reactions": []
        }

**Comment by Jagadeesh-MSFT** [comment] 2021-04-15 15:07
Hi @ShaneOss, our team is working on it. At present we don't have any ETA to share with you.

**Comment by dshhh** [comment] 2021-06-01 08:46
Having the same problem. User value in "reactions" is empty when getting messages from a channel. Too bad :( I really wanted to use this for an internal Q/A service.

"reactions":  [
                          "@{reactionType=like; createdDateTime=2021-03-03T10:49:48.065Z; user=}"
                      ]

**Comment by sebastianmanger** [comment] 2022-07-14 13:26
We are currently facing the same problem, any hints regarding the status would be much appreciated.

**Comment by ChetanSharma-msft** [comment] 2022-07-18 07:00
@sebastianmanger - Thanks for reporting this issue.
We will check on it from our end and get back to you.

**Comment by Prasad-MSFT** [comment] 2022-07-18 07:33
Hi @sebastianmanger - We got update from engineering team that, this is as designed. User Id is the only required field.

**Comment by sebastianmanger** [comment] 2022-07-21 07:58
I am not the author, but if it's by design you can close it in my opinion.

**Comment by ChetanSharma-msft** [comment] 2022-07-21 07:59
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2022-07-21 07:59 UTC
Labels: bug, area: teams, MSTeams-Developer-Support, needs author feedback
