### ISSUE TITLE
Create call sample for Java outdated

### ISSUE THREAD

**Issue by wimvanhouts** [microsoftgraph/microsoft-graph-docs#7078] opened 2020-02-13 12:57 UTC
The Java sample that is provided for the create call functionality is outdated in a couple of aspects.

Modalities are no longer string based in Java SDK, but, also work with enumerations already. ParticipantInfo must also be used for the list of participants, not any of the derived types. Reworked sample looks like below. Note that I set the odata.type manually since in current version of the Java SDK this is not set, which results in error response.

    Call call = new Call();
    call.callbackUri = callBackUrl;
    LinkedList&lt;ParticipantInfo&gt; targetsList = new LinkedList&lt;&gt;();
    InvitationParticipantInfo targets = new InvitationParticipantInfo();
    IdentitySet identity = new IdentitySet();
    Identity user = new Identity();
    user.displayName = "&lt;put display name here&gt;";
    user.id = "&lt;put your user id here&gt;";
    identity.user = user;
    targets.identity = identity;
    targetsList.add(targets);
    call.targets = targetsList;
    
    MediaConfig mediaConfig = new ServiceHostedMediaConfig();
    mediaConfig.oDataType = "#microsoft.graph.serviceHostedMediaConfig";
    call.mediaConfig = mediaConfig;
    
    List&lt;Modality&gt; modalities = new ArrayList&lt;&gt;();
    modalities.add(Modality.AUDIO);
    call.requestedModalities = modalities;
    
    
    graphClient.communications().calls()
      .buildRequest()
      .post(call);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776d5045-0abc-cdf9-f6c0-a2242c63ad42
* Version Independent ID: 7aa5b80a-5565-b702-20ae-8d550357980a
* Content: [Create call - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-calls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by wimvanhouts** [comment] 2020-02-14 09:45
As mentioned in #7080, also the tenantId property is missing in the Java example

**Comment by baywet** [comment] 2020-11-05 21:05
Hi @wimvanhouts 
Thanks for reaching out and thanks for the patience.
This was caused by a bug in our sample generation process which has been addressed and the samples will be updated soon.
https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/366
Closing.

**Closed by baywet** 2020-11-05 21:05 UTC
