### ISSUE TITLE
mismatch in number of types of Azure AD activity reports

### ISSUE THREAD

**Issue by loosely-coupled** [microsoftgraph/microsoft-graph-docs#9945] opened 2020-09-16 14:16 UTC
Hi,

I noticed under the section [What are Azure AD activity logs](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-1.0#what-are-azure-ad-activity-logs) it mentions that there are three types of Azure AD Activity reports but only two are listed. Would just like to find out if there is a type missing, or if the number of types should have been two? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a74bbc-2a8b-1ff6-78e3-e33f143e41db
* Version Independent ID: b9f3185c-1406-e1eb-99b8-edbc84c4e58a
* Content: [Activity reports API overview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/azure-ad-auditlog-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/azure-ad-auditlog-overview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2020-12-01 23:18
Closing as duplicate of #10622 , since resolved #10842

**Closed by FaithOmbongi** 2020-12-01 23:18 UTC
