### ISSUE TITLE
filesFolder of newly created Channel does not exist 

### ISSUE THREAD

**Issue by jojocode77** [microsoftgraph/microsoft-graph-docs#8300] opened 2020-05-19 15:19 UTC
After creating a Channel, the filesFolder is not available until a user interacts with the Files tab in the Channel in the Teams UI:
POST https://graph.microsoft.com/beta/teams/{teamId}/channels
Body: {
  "displayName": "Test Channel",
  "description": "This channel is where we debate all future architecture plans",
  "membershipType": "standard",
  "isFavoriteByDefault": true
}

GET https://graph.microsoft.com/beta/teams/{teamId}/channels/{newChannelId}/filesFolder

The call to the filesFolder gives a 404 error, "Sharepoint folder not found". The folder for the channel is not available in the Sharepoint site if you navigate to it. The folder only appears when a user clicks on to the Files tab of the Channel. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce77c63d-12f7-828d-f0a9-2b72835412f0
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HaojieZheng** [comment] 2020-05-27 02:13
Does anyone know any automated work-around for this? E.g. any PS commands I can call or any Graph API endpoint I can use to trigger the provisioning of the SharePoint site?

**Comment by chowdarymygang** [comment] 2020-06-22 20:45
@clearab @jojocode77 I am having the same problem where I am using Graph Api to create a private channel and we wanted to copy files using Graph API but the underlying SharePoint Site is only created if a user clicks on the files tab. Is there a way to create the underlying site automatically ?

**Comment by Subhasish-msft** [comment] 2020-06-24 03:18
Currently there is no endpoint to trigger the provisioning of SharePoint site. We have added it to backlog

**Comment by webdreams32** [comment] 2020-06-24 14:09
@Subhasish-msft Thank you for the reply, approximately when could we have that available which could trigger the provisioning of SharePoint site ? Currently when I create a private channel using Graph, I sometime see it was able to create the SharePoint site after a couple of hours but not every time. Could you please explain when it creates the SharePoint site and when it does not ?

**Comment by Subhasish-msft** [comment] 2020-06-25 05:24
Currently there is no ETA on this.

**Comment by BrianTJackett** [comment] 2020-09-09 20:16
Pinging this thread to see if any update or ETA to share?

**Comment by gkumra** [comment] 2021-01-10 23:36
Following up on this for an update!
On the other hand, I read somewhere that if the site is created using delegated permissions instead of application permissions then filefolder works, is that correct?

**Comment by Nikitha-MSFT** [comment] 2021-01-25 09:16
We are tracking it internally, Currently there is no ETA on this.

**Comment by maeddeg** [comment] 2021-01-29 08:20
Amy Update? Wer still need this! Or what is the link to upvote the issue?

**Comment by Suxsem** [comment] 2021-04-08 13:28
@Nikitha-MSFT dear Nikitha, we have a large project in standby due to this issue, can you provide us with an update about the status of the issue?
Sometimes it doesn't work also if the user manually goes to the tab files.
![Cattura - Copia](https://user-images.githubusercontent.com/830773/114035067-107f9f80-987f-11eb-925c-6277a903ea16.PNG)


Thank you.

**Comment by Nikitha-MSFT** [comment] 2021-05-14 16:01
@Suxsem - Are you still facing the issue. Could you please conform?

**Comment by webdreams32** [comment] 2021-05-14 16:46
@Nikitha-MSFT : yes, we are still having this problem where we have to manually click on the files tab after we create a private channel using graph.

**Comment by Suxsem** [comment] 2021-05-14 17:51
@Nikitha-MSFT yes I can confirm that the bug is still there

**Comment by maeddeg** [comment] 2021-05-14 17:58
@Nikitha-MSFT yes I can confirm as well

**Comment by acolom** [comment] 2021-05-15 05:19
@Nikitha-MSFT  yes we are

**Comment by Nikitha-MSFT** [comment] 2021-05-17 08:40
Currently, When you craete a channel using graph API the files folder is not created in the sharepoint. Teams create the folder in share point on demand. You need to redirect to the channel and click on the files folder. You have to manually click on the files tab after you create a private channel using graph. This is by design

**Comment by Suxsem** [comment] 2021-05-17 09:27
@Nikitha-MSFT this is clearly _not by design_,
The purpose of APIs is to automate tasks. Asking users to manually click on the file tab is just ridiculous. Very disappointed

**Comment by maeddeg** [comment] 2021-05-18 14:08
@Nikitha-MSFT can please then explain to me, why a channel created by hand automatically gets a Document library and the same channel created by an API not? Either a channel always gets a library or never. Everything else can not be by design!

**Comment by Nikitha-MSFT** [comment] 2021-05-20 09:35
We have Riased a bug. We are Tracking it internally.

**Comment by Suxsem** [comment] 2021-05-20 09:45
@Nikitha-MSFT good thank you. Can you please reopen the issue to track it also publicly?

**Comment by Nikitha-MSFT** [comment] 2021-06-08 08:49
Bug is Resolved now, we have tested this at our end,Hence, we are closing this question for now. If you still face any issue please feel free to reopen the issue

**Closed by Nikitha-MSFT** 2021-06-08 08:49 UTC
Labels: MSTeams-Developer-Support, area: teams

**Comment by BobbyKaruturi** [comment] 2021-06-08 18:50
@Nikitha-MSFT : Thank you for fixing the bug. Did the fix got deployed to graph api beta production ? approximately how much time does it take to create the underlying sharepoint site once the private channel is created ?

The process that we have ran this morning (at 2:15 EST) created the private channel but we didn't see the underlying sharepoint site for it. We can wait if the fix has to get deploy to prod.

**Comment by ianjof-cxp** [comment] 2021-06-09 15:12
Hi, I worked with other parties in MS that helped push this through for a project, and there was no significant delay in creating the associated site for the private channel. We are not using the beta graph API, and this is a fix to functionality in the 1.0 endpoint, and in the initial test carried out, the site was created at 07:51:49 and the site was available in the next API call at 07:51:56

**Comment by Nikitha-MSFT** [comment] 2021-06-10 06:57
Issue is fixed on both v1.0 and beta version. Could you please check and if you still face the issue could you please share requestid and time stamp
