### ISSUE TITLE
Permission for user: revokeSignInSessions

### ISSUE THREAD

**Issue by thikon** [microsoftgraph/microsoft-graph-docs#5795] opened 2019-09-25 07:58 UTC
I allowed permission from list below already, but the graph return '405' status from response. 

Required permissions &gt; Microsoft Graph &gt;
# Application Permission
1. Read and write directory data
2. Read directory data
3. Read and write all groups
4. Read and write all users' full profiles

# Delegated permissions
1. Access directory as the signed in user.
2. Read and write directory data.
3. Read and write all groups.
4. Read and write all user' full profiles.
5. Read all users's full profiles.
6. Read all users's basic profiles.
7. Read and write access to user profile.
8. Sign in and read user profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4662c3f7-8566-09b3-962c-2cfcccfcfc2f
* Version Independent ID: 1cdc7db2-7c2c-9b23-16f7-05e76f588f6c
* Content: [user: revokeSignInSessions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-revokesigninsessions.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thikon** [comment] 2019-10-15 06:36
May i have any update from these issue? :'(

**Comment by davidmu1** [comment] 2020-09-01 23:01
Cannot reproduce the error. No change identified for the page. Closing the issue.

**Closed by davidmu1** 2020-09-01 23:01 UTC
Labels: area: azure/AAD
