### ISSUE TITLE
Add owner to application request sample is incorrect

### ISSUE THREAD

**Issue by markdstafford** [microsoftgraph/microsoft-graph-docs#1645] opened 2017-08-30 21:45 UTC
Issue: The sample request in add owner to application is broken. It should follow the add owner to group pattern documented here: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_post_owners.md#http-request.

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application_post_owners.md#request

**Comment by bachoang** [comment] 2018-10-22 20:45
add Application owner should be something like this:
POST https://graph.microsoft.com/beta/applications/<ApplicationObjectId>/owners/$ref
POST body:
{
    "@odata.id": "https://graph.microsoft.com/beta/users/<UserObjectId>"
}

**Comment by davidmu1** [comment] 2020-09-03 17:55
Not able to reproduce the issue. Was successful using:

POST https://graph.microsoft.com/beta/applications/{id}/owners/$ref
Content-type: application/json
Content-length: 30

{
"@odata.id": "https://graph.microsoft.com/beta/directoryObjects/{id}"
}

Closing the issue.

**Closed by davidmu1** 2020-09-03 17:55 UTC
Labels: area: app model, area: azure/AAD, bug: documentation
