### ISSUE TITLE
Create group and files

### ISSUE THREAD

**Issue by ofer1111** [microsoftgraph/microsoft-graph-docs#8442] opened 2020-05-27 06:17 UTC
The API for creating group and team stopped working well in the last couple of days from some reason. I can't get into the root DriveItem of each channel and even if I click on the Files tab on a specific channel, I have a message "We can't get your files" "We're working on getting them back"
And it's not a matter of time. I was waiting for an hour or so and still got it.
Also, if I create a team from the UI, it's OK
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment] 2020-05-27 14:41
dupe of #8441

**Closed** 2021-02-12 16:26 UTC
