### ISSUE TITLE
Filter all chats based on a specific member's email returns invalid filter clause

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#11370] opened 2021-01-21 09:12 UTC
Filter all the chats based on a specific member's display name works fine
`GET https://graph.microsoft.com/beta/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats?$expand=members&$filter=members/any(o: o/displayname eq 'Peter Parker')`

Filter all the chats based on a specific member's display name doesn't work
`GET https://graph.microsoft.com/beta/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats?$expand=members&$filter=members/any(o: o/email eq 'starkt@teamsgraph.onmicrosoft.com')`

returns:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "xxx",
            "request-id": "xxx",
            "client-request-id": "xxx"
        }
    }
}
```
Resource type for members is [aadUserConversationMember](https://docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-1.0) which is inherited from [conversationMember](https://docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0).
It looks like that filter is applied on conversationMember which doesn't have `email` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment] 2021-03-19 12:18
We are not able to repro the issue. Could you please try again and share the client-request-id and time stamp?

**Comment by MartinM85** [comment] 2021-03-19 14:45
The client-request-id and time stamp:
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2021-03-19T14:43:50",
            "request-id": "1028e40d-db93-491f-ac87-fbb9a36b3b6c",
            "client-request-id": "a432f6d6-c51a-8a2c-4dd5-34828b824120"
        }
    }
}

**Comment by Nikitha-MSFT** [comment] 2021-03-26 12:04
are you still facing the issue if yes could you please share new request id and time stamp? also could you please try using another user's mail id?

**Comment by MartinM85** [comment] 2021-03-26 12:17
I'm still facing the issue. Details:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2021-03-26T12:15:05",
            "request-id": "3f4d99bf-7101-4066-a2fe-b885ddb48262",
            "client-request-id": "8d45b958-de65-4671-5010-f4fd6909cddb"
        }
    }
}
```

**Comment by Nikitha-MSFT** [comment] 2021-03-31 18:28
Are you facing issue only with one user or with all the users? Is user is part of the tenant or you are trying to get the user details of other tenant user? Could you please conform?

**Comment by MartinM85** [comment] 2021-04-01 12:38
When calling `https://graph.microsoft.com/beta/users/{user_id}/chats?$expand=members&$filter=members/any(o: o/email eq '{user_email}')` `user_id` is my id and `user_email` can be either an email of a user from my tenant or from the other tenant.

**Comment by Nikitha-MSFT** [comment] 2021-04-05 08:39
it should be from your tenant, or the user user should have the guest account in your tenant.

**Comment by MartinM85** [comment] 2021-04-05 08:52
It explains why the query is not working for users from another tenant. Those users do not have guest account in our tenant. But the query is still not working for users from our tenant.

**Comment by Nikitha-MSFT** [comment] 2021-04-06 11:17
Could you please share the affected user mail id and the client request id and timestamp for the same query?

**Comment by MartinM85** [comment] 2021-04-06 11:25
The response:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2021-04-06T11:21:35",
            "request-id": "8e040f1f-8742-42a0-8db1-e87fbf14fe39",
            "client-request-id": "aaba65f4-5188-274b-a4f5-4e61bd7240c9"
        }
    }
}
```

User id: 68d3df7a-f8d8-47c9-adb9-7f52e557ba7b
User mail id: b6f8371d-6fb7-4143-a5e3-0ac820f4c606

**Comment by Nikitha-MSFT** [comment] 2021-04-09 07:55
checking internally get back to you soon.

**Comment by Nikitha-MSFT** [comment] 2021-04-15 11:14
We are able to repro the issue. Raised a bug. We don't have ETA to share when it will be fixed.

**Comment by Nikitha-MSFT** [comment] 2021-05-06 05:02
Currently filter chat based on specific member's email does not support. This is by design.

**Closed by Nikitha-MSFT** 2021-05-06 05:02 UTC
Labels: MSTeams-Developer-Support, area: teams, bug
