### ISSUE TITLE
List all teams - just doesn't work - errors with bad gateway

### ISSUE THREAD

**Issue by gavsto** [microsoftgraph/microsoft-graph-docs#7869] opened 2020-04-22 13:56 UTC
When hitting beta/teams/{id} 

When hitting /teams/{id} on the beta graph API I just get an error about Bad Gateway

Invoke-RestMethod : {
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "29b777b9-4e1c-4760-a404-3e9a29509aba",
      "date": "2020-04-22T13:50:52"
    }
  }
}

My delegated permissions have Group.ReadAll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3bc78b-b078-5b95-6ae5-11551d1b852d
* Version Independent ID: fb69519b-3e4a-2279-cf1d-8e9c082fafd6
* Content: [Get team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment] 2020-04-22 20:23
Closing as a duplicate of #7868

**Closed by baywet** 2020-04-22 20:23 UTC
