### ISSUE TITLE
Update Device page lacks info on required Admin role

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#16951] opened 2022-05-18 18:51 UTC
Please specify the required AAD Administrative role for this update request to work.  In my testing it looks like the user will need to be in the folloiwing Admin role (on top of the MS Graph permission)

Global Administrator or Intune Administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2823c35-1b67-2d65-1585-0c6d6162ef8e
* Version Independent ID: c10ea5e9-24d2-910c-5c10-58cc2188fc1f
* Content: [Update device - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=powershell)
* Content Source: [api-reference/v1.0/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-update.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SanDeo-MSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2022-05-18 18:57
Thank you @bachoang for raising this issue. Let me get back to you.

Flagging as a possible duplicate of #16933

**Comment by FaithOmbongi** [comment] 2022-05-19 10:31
Hi @bachoang - I've confirmed your findings that global administrators and intune administrators can update devices. Also allowed are Windows 365 admins. Cloud device admins can only enable or disable using this API. I've raised a PR to indicate these role requirements in the docs.

**Closed by FaithOmbongi** 2022-05-19 10:31 UTC
Labels: area: Azure AD, area: directory management

**Comment by bachoang** [comment] 2022-05-19 14:10
Hi @FaithOmbongi please clarify in the revised docs that Windows 365 Admin can only update device's basic properties while Intuen and Global Admins can update all device properties.
