### ISSUE TITLE
Incorrect Attendee Status

### ISSUE THREAD

**Issue by Milosz7z** [microsoftgraph/microsoft-graph-docs#5281] opened 2019-07-25 07:23 UTC
On calling the endpoint every attendee has None status even if it has another status on Office 365 calendar e.g. Accepted/Declined/Not Responded. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbb79fa-9dde-94ab-2b74-cbfbbc49d331
* Version Independent ID: 442e73df-fce2-8db5-81a8-bb3a225fa773
* Content: [Get event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get-event?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-get-event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get-event.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment] 2019-07-28 18:51
@angelgolfer-ms Can you assign to the right owner?
@jthake-msft This is an outlook API.  Not sure why my name is on this.

**Comment by angelgolfer-ms** [comment] 2019-08-15 05:12
@Milosz7z , can you clarify what you mean by "even if it has another status on Office 365 calendar"?

Do you mean an Office 365 group invites attendees A, B, C to an event, and say attendee A accepts the meeting request, when you GET the event in the _group_ calendar, attendee A shows a responseStatus of "none"?

I verified the following behavior for an example described above:
(A) In the _group_ calendar as well as in A's _user_ calendar, for that event, attendee A's responseStatus shows "accepted".

(B) On the other hand, if attendee B doesn't respond to the event, then when you GET that event in the _group_ calendar, attendee B shows a responseStatus of "none". By default, B's own _user_ calendar does not include that event, so one cannot do a GET for that event _in B's calendar_ to check B's responseStatus.

BTW, I apologize it's been a few weeks since you posted this issue. FYI Github Issues in the Microsoft Graph docs repo (here) are only monitored for documentation issues. If you have an API behavior question, posting the question on stackoverflow and tagging it with "microsoftgraph" may get the community's attention sooner?

**Comment by LMajoros** [comment] 2019-09-17 09:24
@angelgolfer-ms maybe i can answer your question since i'm facing the same issue in user calendar (not group).
There seems to be a difference between the state of the Event (Event.ResponseState) and the state of the attendee (attendee.status.response) for the same user.

Example: 

- User A invites User B to a meeting. 
- When you GET that event in the user's calendar (B) response state of B is set to "none", (Event.ResponseState and attendees.status.response of B) which is correct. 
- B accepts the meeting then. When you GET that event in the user's calendar (B) response state of B is set to "accepted", (Event.ResponseState) but **attendees.status.response of B is still set to "none"** which seems to be not correct. 
Please see the attached screenshot. 

Thanks a lot for investigating here.

![image](https://user-images.githubusercontent.com/55434897/65029233-ad958300-d93d-11e9-89f5-e274bc702907.png)

**Comment by LMajoros** [comment] 2019-11-05 14:03
Is there any update on this issue? 
Can we provide any additional information?

**Comment by louisl** [comment] 2020-09-29 17:03
I've run into the same issue with a job I'm working on, was hoping to use the status to ensure clients that had accepted the invite were not sent the attendee invite again when/if the event content gets updated.

Anyone find a fix/workaround?

**Comment by kmccoyCREA** [comment] 2020-12-08 22:03
Any updates on this one yet? My company has also run into this issue when trying to pull the attendees for an event created programmatically.

**Comment by jsaveljevs** [comment] 2021-01-26 07:29
I'm having this issue too. The only workaround I can think of is to get multiple events by iCalUid from calendars of all attendees individually (assuming you have app access) and combine the results. Is there a better way?

**Comment by comeback-kid** [comment] 2021-02-05 16:27
Same here, after user accepts meeting, it still comes back as "none" from the API when retrieving calendar events. Is there a workaround for this?

**Comment by jasonjoh** [comment] 2021-02-05 19:28
I just tried this myself and do not reproduce it (this was with the organizer and attendee both using OWA to send and accept the meeting, respectively). However, I believe when you're looking at an attendee's calendar (not the organizer), you should only look at `responseStatus` on the event, not `status` on each attendee. Only the organizer's copy would be updated with all of the response statuses of all of the attendees.

So if you're looking on the organizer's calendar, you can see the response status of all attendees by checking the `status` property on each one.

If you're looking at an attendee's calendar, `responseStatus` tells you the state of your response. You don't have any visibility into the response status of any other attendee.

With all that said, I may not be understanding your scenario :D. It's easy to lose the thread when talking about meeting invites - are we looking at the organizer, the attendee, etc.?

**Comment by hbulens** [comment] 2021-02-10 12:59
Well spotted @jasonjoh. It's not the first place you'd look when there's a collection of attendees with a response status property. It makes sense though, but it makes things slightly more complex as - correct me if I'm wrong - there is not a single place to have an overview of all attendees with their response status.

**Comment by jasonjoh** [comment] 2021-02-10 14:34
There isn't a single place to have an overview **for attendees**, but there never has been. You can see the same behavior in Outlook. Only the **organizer** has access to that information. If you think about it, it makes sense: accept/decline notifications are sent to the organizer, not to the entire attendee list. Also consider that an attendee can accept/decline and choose to not send a response, in which case the organizer doesn't even know their real status.

**Comment by Harini84** [comment] 2021-06-25 10:26
Documentation PR under review to clarify none vs not responded

**Closed by Harini84** 2021-06-25 10:26 UTC
Labels: high viewership
