### ISSUE TITLE
credentialuserregistrationdetails Missing API Permission 

### ISSUE THREAD

**Issue by PsychoData** [microsoftgraph/microsoft-graph-docs#9269] opened 2020-07-27 14:54 UTC
When I went to Graph API Explorer and tried running this, I was getting the below error

```
{
    "error": {
        "code": "Authentication_ApplicationHasNoDirectoryReadAccess",
        "message": "Failed to do premium license check from ADGraph",
        "innerError": {
            "date": "2020-07-27T14:47:55",
            "request-id": "336d3a5d-8652-4831-8073-3cd0a0082855"
        }
    }
}
```

The page only says that Reports.Read.All is required, but if I added Directory.Read.All then the query works

Seems like Directory.Read.All is required (at least for some contexts) so that it can confirm the premium license. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2021-02-05 16:52
Calling the API with only `Reports.Read.All` permission returns the expected results. Unable to reproduce the issue for now.

No updates identified for the page. Closing the issue.

**Closed by FaithOmbongi** 2021-02-05 16:52 UTC

**Comment by PsychoData** [comment] 2021-02-05 17:43
It is worth noting, though, that it looks like GraphExplorer might be using ALL of it's authorized scopes to make the query, not just the ones mentioned on the Modify permissions tab, so if you have authorized it for Directory.Read.All or .ReadWrite.All before, you might still be persisting those extra perms it needs 

![image](https://user-images.githubusercontent.com/3719116/107068745-fc4ff100-67ae-11eb-8c8b-3d7ddb26d78f.png)

If you go look at the Access Token tab, and open it in jwt.ms you can see it has me requesting with MANY scopes, some of which I have not been using in the last several weeks or months

![image](https://user-images.githubusercontent.com/3719116/107068586-d0347000-67ae-11eb-80c7-15b3ab32aca1.png)

![image](https://user-images.githubusercontent.com/3719116/107068975-46d16d80-67af-11eb-99fa-1ec2a650005e.png)

**Comment by FaithOmbongi** [comment] 2021-02-09 19:10
Hello @PsychoData ,

Thank you for highlighting this. I re-ran the query starting with a clean permission slate and verified your initial findings. 

I'll get additional verification for this and update the page accordingly. Thank you again.

**Comment by PsychoData** [comment] 2021-02-09 19:24
Thank you very much! 

It would also probably be a good idea for Graph to not keep using all of the old previously acquired tokens permissions without them being explicitly turned on, but that's a discussion for another issue :) 

Did you open one about that, or should I throw up a new Issue as a Bug Report?

**Comment by FaithOmbongi** [comment] 2021-02-09 19:55
For that, I recommend that you open up an issue on the [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) channel. That forum is closely monitored for functionality issues.

**Comment by PsychoData** [comment] 2021-02-10 01:25
Thanks! I sent it in [here](https://docs.microsoft.com/en-us/answers/questions/266261/bug-graphexplorer-using-too-much-permissions-from.html)
