### ISSUE TITLE
Missing information in demo with mgt and Teams Provider for redirect back to main page after authpopup

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#5980] opened 2019-10-16 09:26 UTC
Missing information demo with mgt and Teams Provider for redirect back to the main page after auth popup

Please provide a way to redirect back to [msft team mgt landing page](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/master/samples/teams-tab/index.html) after successful authentication from [ mgt teams tab auth](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/master/samples/teams-tab/auth.html)
It is in infinite loop redirecttion on **`auth.html`** page
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba43c9fd-7426-ffed-8aa7-b1be41e739b5
* Version Independent ID: e4d0bfa9-78ac-561f-3ad7-3d741477f474
* Content: [Microsoft Teams provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/providers/teams)
* Content Source: [concepts/toolkit/providers/teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/providers/teams.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @nmetulev
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmetulev** [comment] 2019-10-16 17:39
Closing this as duplicate of https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/178

**Closed by nmetulev** 2019-10-16 17:39 UTC
