### ISSUE TITLE
$select didn't work

### ISSUE THREAD

**Issue by JieNiGui06** [microsoftgraph/microsoft-graph-docs#22278] opened 2023-07-30 10:03 UTC
get https://graph.microsoft.com/v1.0/me?$select=displayName,mail,id
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(displayName,mail,id)/$entity",
    "userPrincipalName": "329125460@qq.com",
    "id": "ed0938580c56e5e3",
    "displayName": "尼龟 杰",
    "surname": "杰",
    "givenName": "尼龟",
    "preferredLanguage": "zh-CN",
    "mail": "329125460@qq.com",
    "mobilePhone": null,
    "jobTitle": null,
    "officeLocation": null,
    "businessPhones": [],
    "ageGroup": "4"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2023-07-31 09:15
Thank you @JieNiGui06 for raising this issue. Unfortunately, I'm unable to reproduce it as the same request succeeds in my tenant.
<img width="509" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/87893533-acba-4df8-b027-d2d9fe54707c">

Please retry the query - it might have been an intermittent issue that has been resolved. 

However, if the request is still failing, please post the issue with the corresponding request ID at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/266/microsoft-graph-users-api). Microsoft Graph Q&A is the forum where functionality issues are investigated. Closing this issue here.

**Closed by FaithOmbongi** 2023-07-31 09:15 UTC
Labels: area: Entra, area: users, area: query parameters
