### ISSUE TITLE
Misleading description of return value

### ISSUE THREAD

**Issue by silmer** [microsoftgraph/microsoft-graph-docs#4442] opened 2019-04-22 11:14 UTC
Using this API endpoint does not return team resource as hinted in the team resource link at the top of the article ("Get the teams in Microsoft Teams ..."), but rather an object (a group object with extra properties?) containing only displayName, description, id and isArchived.

Attempts to expand other team specific properties such as "webUrl" results in the following 400 error: "Could not find a property named 'webUrl' on type 'microsoft.graph.group'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4878b58-31d9-f8e1-ed30-2316c5f9ca15
* Version Independent ID: 1dcb5dda-2a45-77e1-bbe1-46ec24b33eec
* Content: [List joinedTeams - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-joinedteams.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vman** [comment] 2019-08-20 10:23
Can confirm, it seems the object returned via /joinedTeams is neither the complete Team object nor the complete Group object.

**Comment by Varuuna** [comment] 2020-02-17 09:05
Came here after talking to MS Support due to a custom solution of ours using this endpoint stopped working for us. But now I'm mystified since this issue was originally opened in April.

We've used /joinedTeams for the past 6 months or so and using the 'webUrl' property to provide links to the teams for the users, but suddenly, as of recent all properties return 'null' with a few exceptions (mentioned in the original post)

Why did this happen?

**Comment by joakimhogberg** [comment] 2020-02-20 09:29
Same, I only get id, displayName and description. All other properties are null. Is this expected behavior?

**Comment by bubbleswap** [comment] 2020-12-15 19:08
Any updates on this? We're still getting null for webUrl and all other fields, using the /joinedTeams endpoint
![image](https://user-images.githubusercontent.com/27218932/102260937-fcceb880-3ede-11eb-93e0-1acb97569501.png)

**Comment by matsmagnem** [comment] 2021-06-17 10:22
I stumbled over this as I experience the same problem. Did anyone find the solution?
Could it be diff on Application vs Delegated access tokens?

**Comment by v-chetsh** [comment] 2021-09-27 10:25
@silmer, @bubbleswap -  Just wanted to inform you that **"List joinedTeams"** give only basic information where webUrl is always null due to permissions levels.
EndPoint:
GET https://graph.microsoft.com/beta/me/joinedTeams

Refer below URL:
https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&tabs=http#feedback

Also above API call does not support OData query parameter, please refer below docs:
https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&tabs=http#optional-query-parameters

If you want to get webUrl, you need to call below endpoint:
GET https://graph.microsoft.com/beta/teams/{Team Id}

Reference docs:
https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&tabs=http

Please let us know if you still need and input or help.

**Comment by v-chetsh** [comment] 2021-10-01 06:26
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-10-01 06:26 UTC
Labels: area: teams, bug: documentation, teams: TACO, MSTeams-Developer-Support
