### ISSUE TITLE
Parts to clone ('members')

### ISSUE THREAD

**Issue by DavySmets** [microsoftgraph/microsoft-graph-docs#10313] opened 2020-10-16 08:50 UTC
[Enter feedback here]
Hi, 

In the documentation it says if you reference 'members' in the 'partsToClone' it copies the members and the Owners.

We have 3 owners in the teams environment that we clone. But only one of the owners is copied as a Owner the rest are made members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c92597-b0ca-9dcc-1c46-27da5659f622
* Version Independent ID: 4a00105a-9208-9197-8231-ba1353224fd6
* Content: [Clone a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamaMohanaChary** [comment] 2020-10-27 14:08
@DavySmets:

We are able to reproduce your query, we are checking internally, will update you soon.

**Comment by JimmyHang** [comment] 2020-12-04 13:43
Hi, any update on this issue?

I'm experiencing the opposite, in 'partsToClone', we excluded members/owners because we want a blank team, but the API is copying the members/owners anyway. but only 1 account it seems.??

**Comment by petepuu** [comment] 2020-12-17 13:10
Hi 

I am having same issue, so just want to check when this will be fixed. Thanks!

**Comment by RamaMohanaChary** [comment] 2020-12-28 06:50
We have raised a bug, we will get back to you soon, at present we don't have any ETA.

**Comment by Lee-Myhre** [comment] 2021-07-22 23:12
Any updates?

This is still happening, I just edited out "members" from the PartsToClone value for a cloning flow I'm working on yesterday.

**Comment by Meghana-MSFT** [comment] 2021-09-14 07:24
We are enquiring this internally, We will get back to you once we have an update.

**Comment by Wajeed-msft** [comment] 2021-09-29 10:59
This is by design and has been this way for some time. Currently there is no ETA to share on this. However, we will update this post once we have updates to share.

**Comment by OskarNet** [comment] 2022-03-29 15:49
Perhaps I should create an separate issue but I was just trying this and in my case no members where copied.
Only the user creating the team gets set as the owner of the team and there are no members. Channels for example get copied fine.
Example body to the clone endpoint:
{
  "displayName": "Bekkur med 10 nemendum 5",
  "mailNickName": "bekkurOJF_5",
  "partsToClone": "apps,tabs,settings,channels,members",
  "visibility": "public"
}

**Comment by Meghana-MSFT** [comment] 2022-12-27 07:44
We are closing this issue, please feel free to reach out to us if you have any questions. Thank you.

**Closed by Meghana-MSFT** 2022-12-27 07:44 UTC
Labels: bug, area: teams, MSTeams-Developer-Support, potential known issue
