### ISSUE TITLE
Is Token Lifetime Policy the only type of policy which will be fetched from the /policies graph-api?

### ISSUE THREAD

**Issue by adi928** [microsoftgraph/microsoft-graph-docs#5413] opened 2019-08-10 00:48 UTC
The page says, currently only Token Lifetime Policy is supported. Does that mean only that type of token will be returned when queried for /policies and if it does not exist, none other policies will be returned? Also, after the line "This policy is described in further detail below.", the document goes on to enlist the properties of the api, before actually describing the Token Lifetime Policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4988bd4-95cb-7eb4-ecc8-0226291a5846
* Version Independent ID: 39e21377-15b2-d4ee-5e99-cad948be8a91
* Content: [policy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/policy?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/policy.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @viv-liu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xom-pschiess** [comment] 2020-02-01 15:41
I think this info is probably outdated. I'm able to return all types from this endpoint.

**Comment by FaithOmbongi** [comment] 2021-06-03 07:43
Can't trace this issue back to the Azure AD Policy overview page. If the issue is still present and on another page, kindly reopen the issue from the subject page. Closing for now.

**Closed by FaithOmbongi** 2021-06-03 07:43 UTC
Labels: area: azure/AAD
