### ISSUE TITLE
Error when registering a governanceResource in PIM

### ISSUE THREAD

**Issue by ttunstall07** [microsoftgraph/microsoft-graph-docs#9044] opened 2020-07-09 14:53 UTC
I've noticed that calling the referenced endpoint always throws the error below even when it's actually successful:

```
{
  "error": {
    "code": "InternalServerError",
    "message": "Error while processing response.",
    "innerError": {
      "date": "2020-07-09T14:28:31",
      "request-id": "a95846fa-72ea-4807-9541-7f061fa1212e"
    }
  }
}
```

I've verified both the **onboardDateTime** and **registeredDateTime** properties of the associated resource (a subscription in this case) are updated each time a request is made and even though the documentation shows only [delegated permissions](https://docs.microsoft.com/en-us/graph/api/governanceresource-register?view=graph-rest-beta#permissions) are supported, I can confirm this works with application permissions as well (even though the above error message is returned in either case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff46d9cc-0523-d47e-8856-dea4a53f0c8e
* Version Independent ID: 0a39faf3-7d2e-b605-0fa2-3cf9cd28e1c5
* Content: [governanceResource: register - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceresource-register?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governanceresource-register.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceresource-register.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by venkat1017** [comment] 2020-07-19 17:07
I am also getting the same error  while the unmanaged resources are successfully discovered as managed resources

```
Invoke-RestMethod : {
  "error": {
    "code": "InternalServerError",
    "message": "Error while processing response.",
    "innerError": {
      "date": "2020-07-19T17:07:01",
      "request-id": "f3c99233-cb39-405a-b730-ac64987e5bf6"
    }
  }
}
At line:1 char:11
+ $result = Invoke-RestMethod -Uri "https://graph.microsoft.com/beta/pr ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
   pWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
   ll.Commands.InvokeRestMethodCommand
```

**Comment by ttunstall07** [comment] 2020-09-29 12:53
@shauliu hello, following up to see if there have been any updates in regards to this issue. Thanks!

**Comment by PirteaAdrian** [comment] 2020-10-12 12:46
I receive the same error this error when i try to register resources:
ERROR: Invoke-WebRequest : { "error": { "code": "UnknownError", "message": "", "innerError": { "date": "2020-10-12T12:11:33", "request-id": "e024f36e-7dca-401d-9aeb-f88f83bb25f1", "client-request-id": "e024f36e-7dca-401d-9aeb-f88f83bb25f1" } } }

Before July i haven't received that error. The resource is successfully register in PIM, but with this error

**Comment by shauliu** [comment] 2020-10-12 17:01
I believe we have an issue at the moment where its returning a 500 but the resource is actually registered correctly. We should be looking at fixing this with the graph team.

@anujchaudhary might be able to give the latest.

**Comment by venkat1017** [comment] 2020-11-12 08:25
@anujchaudhary can you update with the latest just checking if the issue is fixed?

**Comment by anujchaudhary** [comment] 2020-11-16 18:21
This should already be fixed.

________________________________

**Comment by davidmu1** [comment] 2021-02-01 23:57
No change identified for the page. Closing the issue.

**Closed by davidmu1** 2021-02-01 23:57 UTC
