### ISSUE TITLE
Shared channels endpoint does not return channel information

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#18895] opened 2022-10-17 13:18 UTC
Hello,
I was verifying the documentation, and I noticed a different behavior between the provisioning of channels.

I am getting back from the Graph endpoint the channel information if I am creating a standard and private channel. On the other hand, the shared channel does not return any values.

Is this behavior intended or going to change to stay consistent with the API standard behavior?

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment] 2022-10-18 05:22
We are looking into the issue.

**Comment by Prasad-MSFT** [comment] 2022-10-18 06:06
**Creating Standard channel:**
```
POST https://graph.microsoft.com/v1.0/teams/f158aa4b-c762-4758-bebe-f4f1c8ab429f/channels 
{
    "displayName": "Architecture Discussion1",
    "description": "This channel is where we debate all future architecture plans1",
    "membershipType": "standard"
}
```
Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('f158aa4b-c762-4758-bebe-f4f1c8ab429f')/channels/$entity",
    "id": "19:6be2f9c2bb634931bd6b1f7795b73503@thread.tacv2",
    "createdDateTime": "2022-10-18T05:57:25.3399269Z",
    "displayName": "Architecture Discussion1",
    "description": "This channel is where we debate all future architecture plans1",
    "isFavoriteByDefault": false,
    "email": "",
    "webUrl": "https://teams.microsoft.com/l/channel/19%3a6be2f9c2bb634931bd6b1f7795b73503%40thread.tacv2/Architecture+Discussion1?groupId=f158aa4b-c762-4758-bebe-f4f1c8ab429f&tenantId=b3cdf1c8-024a-49e2-a994-f67f830b02f3",
    "membershipType": "standard"
}
```

**Creating Private channel:**
```
POST https://graph.microsoft.com/v1.0/teams/f158aa4b-c762-4758-bebe-f4f1c8ab429f/channels 

{
    "@odata.type": "#Microsoft.Graph.channel",
    "membershipType": "private",
    "displayName": "My First Private Channel1",
    "description": "This is my first private channels1",
    "members": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "user@odata.bind": "https://graph.microsoft.com/v1.0/users('64af9a58-8030-46fb-8388-c2417b8b252a')",
            "roles": [
                "owner"
            ]
        }
    ]
}
```

Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('f158aa4b-c762-4758-bebe-f4f1c8ab429f')/channels/$entity",
    "id": "19:9ebe8c645a4f4a838fe881fe1159865b@thread.tacv2",
    "createdDateTime": "2022-10-18T06:00:45.9406413Z",
    "displayName": "My First Private Channel1",
    "description": "This is my first private channels1",
    "isFavoriteByDefault": null,
    "email": "",
    "webUrl": "https://teams.microsoft.com/l/channel/19%3a9ebe8c645a4f4a838fe881fe1159865b%40thread.tacv2/My+First+Private+Channel1?groupId=f158aa4b-c762-4758-bebe-f4f1c8ab429f&tenantId=b3cdf1c8-024a-49e2-a994-f67f830b02f3",
    "membershipType": "private"
}
```

**Creating Shared channel:**

```
POST https://graph.microsoft.com/v1.0/teams/f158aa4b-c762-4758-bebe-f4f1c8ab429f/channels 
{
    "displayName": "My First Shared Channel1",
    "description": "This is my first shared channel1",
    "membershipType": "shared",
    "members": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "user@odata.bind": "https://graph.microsoft.com/v1.0/users('64af9a58-8030-46fb-8388-c2417b8b252a')",
            "roles": [
                "owner"
            ]
        }
    ]
}
```

Response:
![image](https://user-images.githubusercontent.com/62237649/196348213-82b01b1d-6f1d-4c54-9db3-b1156231f1e1.png)

@plamber - This behaviour seems to be by design only.

**Comment by plamber** [comment] 2022-10-18 06:14
Hi @Prasad-MSFT,
From a developer's perspective, the behavior seems wrong. 

Let me elaborate on this. When working with the SDK (e.g., .NET SDK) I am calling the endpoint '.Teams[teamId].Channels.Request().AddAsync(request)'. The SDK expects a return value of a Channel object when calling the AddAsync method. This is working as expected for "normal" and "private" channels while the "shared" channels do not return anything.

At first glance, this seems to be a bug. If it is by design, it might be an idea to add this to the documentation as a hint.

Cheers,
Patrick

**Comment by plamber** [comment] 2022-10-18 11:54
Hi @Prasad-MSFT,
I would like to add another reason why the channel as output might be helpful.

Imagine you want to add conversationmembers to the channel. As far as I can see, you can't add multiple conversation members while creating a shared channel. This means I have to fall back to a separate endpoint to add a conversationmember to an existing channel.

I can do it easily if I get back the channel information after creation. Otherwise, I must get all channels and look up the shared channel by Displayname.

Cheers,
Patrick

**Comment by Prasad-MSFT** [comment] 2022-10-18 12:00
I agree @plamber. We will bring this to notice of engineering team and will take appropriate actions.
Thanks!

**Comment by Prasad-MSFT** [comment] 2022-12-26 10:53
@plamber - We got update from engineering team that "The Shared Channel creation call should be returning a value in the response header. The user is supposed to use that value to uniquely address the shared channel."

**Comment by lramosvea** [comment] 2023-02-16 20:04
Closing as this issue seems to be resolved. Please feel to reopen otherwise.

**Closed by lramosvea** 2023-02-16 20:04 UTC
Labels: area: teams, MSTeams-Developer-Support, needs author feedback, doc: enhancement
