### ISSUE TITLE
Channels are always created as 'hidden', users are not able to find them

### ISSUE THREAD

**Issue by wolskis** [microsoftgraph/microsoft-graph-docs#6885] opened 2020-01-23 05:32 UTC
POST /teams/{id}/channels appears to accept 
```
{
  "displayName": "Architecture Discussion",
  "description": "This channel is where we debate all future architecture plans",
   isFavoriteByDefault:  true
}
```
But does not honour this attribute, so all channels are created in a hidden state.  You can find this attribute supported in the Create Team endpoint using channel templates.
https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta#request-2

This discrepancy was also acknowledged by a MSFT staff member on SO https://stackoverflow.com/questions/55136212/microsoft-graph-beta-add-microsoft-teams-channel-with-isfavoritebydefault

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kepeter** [comment] 2020-08-16 09:17
I'm creating channel using this (C#) code, and it seems to work correctly (channels are not hidden)...

```
Channel oChannel = await _Client.Teams[TeamId].Channels.Request().AddAsync(new Channel()
{
    DisplayName = Name,
    Description = Description,
    IsFavoriteByDefault = true,
    MembershipType = Private ? ChannelMembershipType.Private : ChannelMembershipType.Standard,
    Members = (oMember == null) ? null : new ChannelMembersCollectionPage()
    {
        new AadUserConversationMember
        {
            Roles = new List<string> { "owner" },
            AdditionalData = new Dictionary<string, object>
            {
                ["user@odata.bind"] = string.Format("https://graph.microsoft.com/beta/users('{0}')", oMember.Id)
            }
        }
    }
});
```

...using beta site (https://graph.microsoft.com/beta) with version 0.19 of the (beta) library

**Comment by anandab-msft** [comment] 2021-01-04 07:18
setting  isFavoriteByDefault:  true in create channel will make channel visible for everyone.

**Comment by anandab-msft** [comment] 2021-01-04 07:18
closing this issue, in case you feel the issue is not resolved either reopen this issue or create a new issue.

**Closed** 2021-01-19 18:51 UTC
Labels: bug: product, teams: TACO
