### ISSUE TITLE
This example (Add team to the group) doesn't work

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoftgraph/microsoft-graph-docs#6037] opened 2019-10-21 08:52 UTC
I get statuscode 400 and:
{
    "error": {
        "code": "BadRequest",
        "message": "Empty Payload. JSON content expected.",
        "innerError": {
            "request-id": "95f36737-07ae-44ca-a4d0-31beb307dbeb",
            "date": "2019-10-21T08:47:26"
        }
    }
}
when trying in Graph Explorer...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed58b36a-1416-fcc0-4dd7-39d2a9f48b7c
* Version Independent ID: 438b361c-d067-4027-6a7d-3988c7028837
* Content: [Creating a group with a Microsoft Teams team - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team)
* Content Source: [concepts/teams-create-group-and-team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-create-group-and-team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anomepani** [comment] 2019-11-01 18:32
@EsaHeikkiPoutanen If you are creating a team from the existing team it requires empty JSON as payload.

```
PUT /groups/{id}/team
{ }
```

**_{ }_** is an empty json payload that must require in body to create team.

**Comment by EsaHeikkiPoutanen** [comment] 2019-11-04 08:39
okay, how do I put it in here:

graphClient.Groups[myGroup.Id].Team
                            .Request()
                            .PutAsync(team); ???

**Comment by EsaHeikkiPoutanen** [comment] 2019-11-04 08:42
and I'm not creating a team from the existing team, I'm trying to create a team from existing AD group, 
Should work fine according to documentation...

**Comment by anomepani** [comment] 2019-11-04 10:11
@EsaHeikkiPoutanen This might work for you. Can you try this link: https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=csharp

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var team = new Team
{
	MemberSettings = new TeamMemberSettings
	{
		AllowCreateUpdateChannels = true
	},
	MessagingSettings = new TeamMessagingSettings
	{
		AllowUserEditMessages = true,
		AllowUserDeleteMessages = true
	},
	FunSettings = new TeamFunSettings
	{
		AllowGiphy = true,
		GiphyContentRating = GiphyRatingType.Strict
	}
};

await graphClient.Groups["{id}"].Team
	.Request()
	.PutAsync(team);
```

You can pass the setting or it will set the default setting if you pass an empty Setting. I am afraid if you are passing requests like below and you are getting the exception or bad request then it can be a bug in Graph SDK.

```
var team = new Team();

await graphClient.Groups["{id}"].Team
	.Request()
	.PutAsync(team);
```

**Comment by EsaHeikkiPoutanen** [comment] 2019-11-04 10:14
That's excactly what my code is doing, the last I tested (couple of weeks) it didn't work, will test again...

**Comment by EsaHeikkiPoutanen** [comment] 2019-11-05 07:24
still don't work, updated Microsoft. Graph to v1.19.0 (and Graph.Auth got updated too). I get:
Code: InvalidRequest
Message: Could not find member '@odata.type' on object of type 'TeamMemberSettings'. Path 'memberSettings['@odata.type']', line 1, position 66.,Could not find member '@odata.type' on object of type 'TeamMessagingSettings'. Path 'messagingSettings['@odata.type']', line 1, position 205.,Could not find member '@odata.type' on object of type 'TeamFunSettings'. Path 'funSettings['@odata.type']', line 1, position 329.,Could not find member '@odata.type' on object of type 'Team'. Path '['@odata.type']', line 1, position 384.

Any advice ?

**Comment by anomepani** [comment] 2019-11-05 08:38
@EsaHeikkiPoutanen 

Can you look at this sample which might be helpful to you which is using graph SDK
https://github.com/microsoftgraph/contoso-airlines-teams-sample
Specifically this file

https://github.com/microsoftgraph/contoso-airlines-teams-sample/blob/b1ca69869ac883318525e45c08e7f5666302685f/project/Models/GraphService.cs

**Comment by spplante** [comment] 2020-11-23 14:40
Same thing here, was working flawlessly for weeks so this is definitely a production breaking change

**Comment by anandab-msft** [comment] 2021-01-04 08:49
As mentioned by others pass an empty json object "{}" in request.
Closing this issue, in case you feel this is not resolved either re-open this issue or create a new issue.

**Comment by AlyaKoni** [comment] 2021-01-16 19:23
anandab-msft solution does not work. At least in graphClient not. You have to set the ODataType property from all classes to null:

Team newTeam = new Team()
{
    GuestSettings = new TeamGuestSettings
    {
        AllowCreateUpdateChannels = false,
        AllowDeleteChannels = false,
        ODataType = null
    },
    MemberSettings = new TeamMemberSettings
    {
        AllowCreateUpdateChannels = false,
        ODataType = null
    },
    MessagingSettings = new TeamMessagingSettings
    {
        AllowUserEditMessages = true,
        AllowUserDeleteMessages = true,
        ODataType = null
    },
    FunSettings = new TeamFunSettings
    {
        AllowGiphy = true,
        GiphyContentRating = GiphyRatingType.Strict,
        ODataType = null
    },
    ODataType = null
};

Please see: https://stackoverflow.com/questions/58420993/could-not-find-member-odata-type-on-object-of-type-teammembersettings

**Comment by anandab-msft** [comment] 2021-01-19 05:36
@AlyaKoni - did you try this in graph explorer, i tested and it worked for me , both with empty payload and with mentioned example.
![image](https://user-images.githubusercontent.com/71336636/104992053-30ed4a00-5a46-11eb-9829-595add08e898.png)
![image](https://user-images.githubusercontent.com/71336636/104992092-45314700-5a46-11eb-815b-866cc64db3b4.png)

**Comment by AlyaKoni** [comment] 2021-01-19 06:43
@anandab-msft Ah ok. The initial question was related to graph explorer. So you are fully right. In Graph client, you are not able to specifiy an empty payload. So in Graph explorer you have to set the ODataType to null to generate an empty payload:

var team = new Team(){ODataType=null};
await graphClient.Groups["{id}"].Team
	.Request()
	.PutAsync(team);

**Comment by anandab-msft** [comment] 2021-01-19 07:18
@AlyaKoni - hope the issue is resolved, closing this issue.

**Closed** 2021-01-19 18:47 UTC
Labels: area: teams, bug: documentation, teams: TACO
