### ISSUE TITLE
Removing from Team doesn't appear to remove from Team's channels

### ISSUE THREAD

**Issue by brian-rose-sp** [microsoftgraph/microsoft-graph-docs#8526] opened 2020-06-02 16:17 UTC
[Enter feedback here]

When using the API to remove a member from a team, it doesn't remove them from the channels that are part of the team. 

Notice "User One" is not part of the "Engineering" team.

![image](https://user-images.githubusercontent.com/10223273/83543407-f2f4e300-a4c1-11ea-80e6-fcac47f32b23.png)

Notice "User One" is part of the "General" channel under the "Engineering" team

![image](https://user-images.githubusercontent.com/10223273/83544075-f6d53500-a4c2-11ea-8411-03b364a290b8.png)

I know that when I attempt to add a member to a channel and they aren't part of the team, I get an API response back indicating that they aren't a member of the team.  I assume therefore that you can't be a member of a channel without being in the team?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment] 2020-06-24 11:05
We could not reproduce the issue on our side. May be it sync issue. Could you see the issue now only. Could you please conform

**Comment by Nikitha-MSFT** [comment] 2021-05-27 10:20
@brian-rose-sp - Are you still facing the issue, if yes please reopen the issue with the required details. Closing the issue for now.

**Closed by Nikitha-MSFT** 2021-05-27 10:20 UTC
Labels: MSTeams-Developer-Support
