### ISSUE TITLE
What if I create team using a group id already has team created?

### ISSUE THREAD

**Issue by jonnyguo1988** [microsoftgraph/microsoft-graph-docs#6551] opened 2019-12-11 03:12 UTC
it is unstable when I try to create a team using a group id already has team created, I thought it should response with "Conflict", but it sometime response with "ServiceUnavailable", sometime response with "BadGateway", it difficult to handle the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-msft** [comment] 2021-01-19 07:11
closing this issue as it is duplicate of #6448 which is resolved.

**Closed** 2021-01-19 18:49 UTC
Labels: area: teams, bug: documentation, teams: TACO
