### ISSUE TITLE
lastUpdatedDateTime not correct

### ISSUE THREAD

**Issue by ShaneOss** [microsoftgraph/microsoft-graph-docs#8888] opened 2020-06-27 23:49 UTC
The "lastUpdatedDateTime" is not correct based on the last message in the chat thread. Is it supposed to be?
What would constitute as an update to lastUpdatedDateTime?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment] 2020-06-29 11:13
@ShaneOss , Thanks for reporting this issue. We have created a bug for this

**Comment by simon-gillespie-acrinax-com** [comment] 2020-09-22 13:38
I think this was originally marked as a bug in April, is this still outstanding? (I am using Microsoft.Grah.Beta 0.27.0-preview)

**Comment by jussmi** [comment] 2020-10-12 15:39
This and https://github.com/microsoftgraph/microsoft-graph-docs/issues/6083 were originally marked as bugs.
However, this pull request https://github.com/microsoftgraph/microsoft-graph-docs/pull/9221 indicates there is no plan to resolve this field to reflect the latest chat message, and the field is working as intended. Would it be possible to get clarity on this issue?
Being able to query and filter on the latest chat message seems more pertinent to an API than a rename or membership change.

**Closed** 2021-05-27 10:38 UTC
Labels: MSTeams-Developer-Support
