### ISSUE TITLE
Doesn't work for federated chat conversations

### ISSUE THREAD

**Issue by ShaneOss** [microsoftgraph/microsoft-graph-docs#9094] opened 2020-07-14 10:58 UTC
This doesn't work for federated chat conversations.

Posting a message to e.g. 
https://graph.microsoft.com/beta/me/chats/19:myuserid_federateduserid@fed.unq.gbl.spaces/messages
results in BadRequest. :( How do you send a message to a federated user?
{
  "error": {
    "code": "BadRequest",
    "message": "Bad Request",
    "innerError": {
      "date": "2020-07-14T10:52:18",
      "request-id": "4277150f-59bf-4aa3-864c-afb044420052"
    }
  }
}

Can retrieve messages from the same federated chat conversation fine. Just can't post new.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c26fc-a47b-9f84-9d55-68cb48aad3fc
* Version Independent ID: 27b8eca1-ad6a-2881-a029-8d392c470b78
* Content: [Create chatMessage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment] 2020-08-04 09:19
We could not reproduce the issue on our side. Could you please check chat id? Also could you please share request body what you  are trying?

**Comment by ShaneOss** [comment] 2020-08-04 09:54
GET (works fine, chat ID is correct and retrieves messages from conversation). Can PM you the user guids.

POST (to same endpoint) https://graph.microsoft.com/beta/me/chats/chatid...@fed.unq.gbl.spaces/messages
Request body
{
  "body": {
    "contentType": "html",
    "content": "<div style=\"font-size:12pt;font-family:&quot;Segoe UI&quot;;\"><p style=\"font-size:11pt;margin:0;\">Hello</p></div>"
  }
}

Request respone
{
  "error": {
    "code": "BadRequest",
    "message": "Bad Request",
    "innerError": {
      "date": "2020-08-04T09:45:20",
      "request-id": "4a65cb83-418a-436a-beac-a4750a4d0d8c"
    }
  }
}

**Comment by Nikitha-MSFT** [comment] 2020-08-13 14:26
Could you please share repro steps How we can get an id with @fed.unq.gbl.spaces?

**Comment by ShaneOss** [comment] 2020-08-14 11:07
If you initiate a conversation in Teams with a federated user. Then check via Graph https://graph.microsoft.com/beta/me/chats and view the most recent chat conversation ID. It would be the most recent item.
You can then GET the messages within the conversation via Graph using that chat id, you just can't send messages back via Graph.

You can also see the chat ID via Fiddler and the Teams Web Client when chatting with a federated user.
e.g (guids hav been changed). https://apac.ng.msg.teams.microsoft.com/v1/users/ME/conversations/19%3A4f53324c-0316-48eb-a0a5-803465b94b87_8f446def-c946-45e7-9e93-39d6caf1ba88%40fed.unq.gbl.spaces

**Comment by Nikitha-MSFT** [comment] 2020-08-17 05:48
we have followed the same steps but we didn't get the chat id with @fed and renaming are same. Could you please share the steps how we can get chat id with @fed?

**Comment by ShaneOss** [comment] 2020-08-17 08:24
Hi Nikitha,
Please reach out and I'd be happy to go through it. You can get me via Teams at shane.morgan@tafensw.edu.au
Thanks.

**Comment by Nikitha-MSFT** [comment] 2020-08-28 11:32
We are able to reproduce it. Raised a bug.

**Comment by ShaneOss** [comment] 2021-01-05 06:01
Hey Team, 
Just wondering if there were any updates on this?
Thanks!

**Comment by Nikitha-MSFT** [comment] 2021-01-05 10:55
We are looking into it. we don't have ETA to share when it will be fixed.

**Closed** 2022-12-27 07:37 UTC
Labels: area: teams, request: feature, MSTeams-Developer-Support, potential known issue
