### ISSUE TITLE
Conditional Access Policy get request not returning baseline policies

### ISSUE THREAD

**Issue by combodev1** [microsoftgraph/microsoft-graph-docs#6379] opened 2019-11-21 17:48 UTC
When issuing a get request to "https://graph.microsoft.com/beta/conditionalAccess/policies", the baseline policies are not returned, regardless of if they are enabled or not. Only custom policies are returned. Is there any way to have the baseline policies returned by this API call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2f4938-7d09-1888-5d89-15cdaa9bf6dd
* Version Independent ID: 601266a3-affe-e167-d643-5de314b0bfd9
* Content: [conditionalAccessPolicy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/conditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/conditionalaccesspolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment] 2019-11-27 18:37
The expected behavior is to not return baseline policies and there are no other APIs or plans to do so. No change required to the page, closing the issue.

**Closed by davidmu1** 2019-11-27 18:37 UTC

**Comment by TmJr75** [comment] 2019-12-14 19:49
This is something that would be very helpful if were listed out as well. 
If you have several tenants you manage, you do not wish to go in on each tenant manually to check for the baselinepolicies. It would be very helpful to have them returned by these calls.

**Comment by TmJr75** [comment] 2019-12-14 21:40
Since these policies will be deprecated 29th february 2020, I guess there will be no point having them returned by this API call.

**Comment by Rincey** [comment] 2020-04-16 22:42
Here we are in the middle of April, and I can see 4 baseline (preview) in the GUI, but I cannot get them from the Graph API.... To be Deprecated, Preview, or whatever, the Baseline policies should be returned by the API endpoint to give a true picture of the Conditional Access Policies.
