### ISSUE TITLE
Double-check authorize and token URLs in examples

### ISSUE THREAD

**Issue by noahadler** [microsoftgraph/microsoft-graph-docs#7561] opened 2020-03-31 20:09 UTC
The examples in this page reference /common/oauth2/v2.0/authorize and /common/oauth2/v2.0/token but in my testing I could only get the API to work by omitting the /v2.0 section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user#feedback)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment] 2021-04-27 23:07
Closing this issue, as I have been unable to reproduce the issue (probably because the article has been updated since this issue was raised). Thank you for your feedback!

**Closed by psignoret** 2021-04-27 23:07 UTC
Labels: area: azure/AAD
