### ISSUE TITLE
How can a Chat associated to a meeting have a created date (much) later than the equivalent event entity created date

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#16694] opened 2022-04-27 15:31 UTC
Hello lovely friendly Microsoft people :) 

looking at GET: Chats/[id] I get the following:

![image](https://user-images.githubusercontent.com/30351641/165551118-a8c9eb6f-c152-4090-88bb-479adff11780.png)

if I then look at the event associated to this chat, I get;

![image](https://user-images.githubusercontent.com/30351641/165553250-db4411a9-68b4-4d4e-9367-f5b8ce423277.png)

my question is; how does the event here have a created timestamp that is approx 4 hours earlier than the chat that is related. 

this is affecting us because we are doing some fuzzy matching in some code to associate a users chat with an event and it's harder when the created timestamps don't match up. When I try to recreate this scenario I cannot for the life of me get it to come out like this example. 

all that I can say is that I believe these are Teams meetings set up via Outlook client. It's possible that they were created as appt's only and then subsequently converted in to a Teams meeting (again via the Outlook client) but whatever I try, even when I get any sort of discrepancy, I cannot recreate a scenario where the event is showing as having created earlier than the chat (certainly not in orders of magnitude of hours)

would be so helpful if I could get a handle on why these examples keep popping up for us and breaking my fuzzy matching (I know you have recently introduced a field "calendarEventId" and that would take out the need for fuzzy matching - but that's already been confirmed to only be populated if the meeting was set up via the Teams client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b47b99-078f-a85a-fc92-d262b29a991a
* Version Independent ID: faaa6ab2-be92-05fc-9adb-34dcf8fee7cb
* Content: [Get chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment] 2022-04-29 00:05
@zhengni-msft Can you take a look at this one?

**Comment by Nivedipa-MSFT** [comment] 2022-05-04 06:12
@AlexSapple - We are investigating your query. We will inform you once we have any update.

**Comment by Nivedipa-MSFT** [comment] 2022-05-12 13:04
@AlexSapple - We have tested this but we are not able to repro this issue.
@zhengni-msft - Could you please share your input on this

**Comment by AlexSapple** [comment] 2022-05-12 13:16
so I've had this happen to me once that I can tell from our insights, but it's happening more often than I'd like in our user base (which is small - therefore I'd be inclined to think it's actually relatively common) 

- My only best guess is that it's occurring when Teams is added to an existing calendar appointment some (long) time after the original appt - for example, a user puts a calendar appt in their diary via Outlook and does not immediately include Teams - then perhaps a few weeks later as the appt comes up, they add Teams to the appt via Outlook - (so an old appt, with Teams added later) - that really is my best guess as I do not have reliable recreation steps 

aside from whatever the discrepancy is - is it at least fair to say that under normal circumstances, we would ultimately expect the event created stamp to be roughly aligned to the chat stamp? (perhaps assuming a small eventual consistency delay etc)

**Comment by Nivedipa-MSFT** [comment] 2022-05-20 09:43
@AlexSapple - We have checked this with engineering team. We got the reply that **This is by design. Chat doesnt get created at the same time as the meeting event**

**Comment by AlexSapple** [comment] 2022-05-20 09:48
ok, thanks @Nivedipa-MSFT - so you are saying it's completely normal for a chat to be created much later than the underlying event. I only wish there was some consistency - or that the field "calendarEventId" was actually useable (it's not because there is no guarantee of it being populated) - this is a massive problem in our org because we are really struggling to marry up the data we get back from our custom Teams app context (chatId) to our users calendar (events). It's almost as if someone at your end has thought about this by adding the  "calendarEventId" field... but with the caveat that it's only populated if the meeting was set up in the Teams client.... :(

**Comment by Nivedipa-MSFT** [comment] 2022-05-25 07:57
@AlexSapple - Could you please raise an user voice for this feature request.
[Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by AlexSapple** [comment] 2022-05-25 10:05
ok I've done that - I put it in the Graph community rather than the Teams community (just felt slightly more appropriate). I suppose this ticket is ready to be closed (all be it without a solution)

**Comment by v-chetsh** [comment] 2022-05-27 11:25
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2022-05-27 11:25 UTC
Labels: area: teams, MSTeams-Developer-Support
