### ISSUE TITLE
Query option is not allowed

### ISSUE THREAD

**Issue by TonyLi2013** [microsoftgraph/microsoft-graph-docs#11446] opened 2021-01-28 08:09 UTC
Hi team,

Error occurred while retrieving channel messages using nextLink, the error response is:
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.",
        "innerError": {
            "message": "Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.",
            "date": "2021-01-28T08:05:16",
            "request-id": "0ec366a0-7744-470a-8fb7-d8e68452e8e3",
            "client-request-id": "0ec366a0-7744-470a-8fb7-d8e68452e8e3"
        }
    }
}

This api worked last week, so looks like something wrong in this week's update.
Please have a look, thanks in advance.
![image](https://user-images.githubusercontent.com/3928402/106108488-4b7c9d00-6183-11eb-99a8-84738ac9fb18.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bea46ed-94e0-6648-0293-8c50639ab4d7
* Version Independent ID: 139a2723-2b4b-21a2-a11b-ff5a77a61d42
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by CalvinQuark** [comment] 2021-01-30 04:35
This week, I started encountering this same issue with the `https://graph.microsoft.com/v1.0/teams/{teamId}/schedule/shifts` API.

**Comment by Hazza1985** [comment] 2021-02-01 15:03
Me too... trying to access https://graph.microsoft.com/beta/teams/{teamId} #schedule through OData power query in excel, tried in PowerBI, same result.

Tables load if they are less than 100 rows, but anything over and I get:

"COM error: Microsoft.Mashup.ProviderShared; [DataSource.Error] OData: Request failed: The remote server returned an error: (400) Bad Request. (The query specified in the URI is not valid. Query option 'SkipToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.).
The current operation was cancelled because another operation in the transaction failed.
"
Connection worked fine of Friday, Now Monday and broken...

Any help will be appreciated.

**Comment by TonyLi2013** [comment] 2021-02-03 05:46
Issue resolved today

**Comment by petrovnikitamai** [comment] 2021-02-03 09:27
same problem

$skiptoken work's fine with
 https://graph.microsoft.com/v1.0/groups
 https://graph.microsoft.com/v1.0/users

access to teams data using '@odata.nextLink'  return error
https://graph.microsoft.com/v1.0/teams/{groupId}/schedule/shifts

**Comment by edevillers** [comment] 2021-02-06 22:28
I have the same issue on /shifts/   right now.

Is it working for anyone ?  It's also used  to retrieve scheduling data automatically from Shifts.

**Comment by Hazza1985** [comment] 2021-02-08 11:16
> I have the same issue on /shifts/ right now.
> 
> Is it working for anyone ? It's used to retrieve scheduling data automatically from Shifts.

I use this to grab Holiday data from shifts.

Still not working for me, had to put in a manual workaround.

Works in excel (process may work for other environments)

- Load preview of data
    - This still works, just seems to be an issue with loading the data afterwards
- Copy data into new sheet
- Set that sheet up as data source
- Add data source to data model
- Connect this new source to the rest of my queries

bit of a pain but at least I can get the data where it is needed until MS fix it.

**Comment by edevillers** [comment] 2021-02-09 04:05
Thank you for your suggestion. Unfortunately I have more than the 1000 rows limit in the preview data. I ended up coding a custom Python extraction script that iterates over dates.

**Comment by RikVercauteren** [comment] 2021-02-09 14:31
Same Problem here.  My problem started one week ago.  
Will try the workarround.

**Comment by Hazza1985** [comment] 2021-02-15 07:31
Works for my original setup as of this morning.

**Comment by RikVercauteren** [comment] 2021-02-15 07:45
Hazza1985, I can confirm this.  My synchronisation agent is running again.

**Comment by Mamatha-MSFT** [comment] 2021-03-23 13:28
Hi @edevillers When I tried to list shifts using `https://graph.microsoft.com/v1.0/teams/{groupId}/schedule/shifts`, there is no @odata.nextLink in the response. 
![image](https://user-images.githubusercontent.com/78795357/112153574-69a5cd00-8c09-11eb-9af4-37f83012275d.png)

**Comment by edevillers** [comment] 2021-03-23 15:44
I broke it down in a daily extraction so It never needs paging, but this makes the extraction a bit more cumbersome than it has to be.  I may leave it as it is. 

You can probably force the @data.nextLink to appear by adding a `top=1` to your query ?

**Comment by edevillers** [comment] 2021-03-23 15:45
> 
> 
> Hi @edevillers When I tried to list shifts using `https://graph.microsoft.com/v1.0/teams/{groupId}/schedule/shifts`, there is no @odata.nextLink in the response.
> ![image](https://user-images.githubusercontent.com/78795357/112153574-69a5cd00-8c09-11eb-9af4-37f83012275d.png)

![image](https://user-images.githubusercontent.com/6540408/112174941-32192f80-8bcd-11eb-9352-a94abeba35ad.png)

**Comment by edevillers** [comment] 2021-03-23 15:46
> 
> 
> Hi @edevillers When I tried to list shifts using `https://graph.microsoft.com/v1.0/teams/{groupId}/schedule/shifts`, there is no @odata.nextLink in the response.
> ![image](https://user-images.githubusercontent.com/78795357/112153574-69a5cd00-8c09-11eb-9af4-37f83012275d.png)

I broke it down in a daily extraction so that I never bust  the max that triggers paging.

You can probably force it on your side by adding a `top=1` to your request ?

**Comment by Mamatha-MSFT** [comment] 2021-03-24 10:04
Thank you@edevillers. I am unable to repro your issue. The @odata.nextLink is working fine for list shifts. I think the issue got fixed now. Could you please check once at your end and let me know if the issue still persists.   
![image](https://user-images.githubusercontent.com/78795357/112291471-27869500-8cb6-11eb-986f-d7cc5ad85519.png)

**Comment by Kay-Yuan** [comment] 2021-05-16 02:55
> I have the same issue on /shifts/ right now.
> 
> Is it working for anyone? It's used to retrieve scheduling data automatically from Shifts.
 Same problem here, tried to use '$select' and  '$orderby' but didn't work as expected. It's said those two querey options not allowed.

**Comment by Mamatha-MSFT** [comment] 2021-05-17 10:20
@Kay-Yuan As mentioned in documentation only $filter  is currently supported. 
![image](https://user-images.githubusercontent.com/78795357/118473434-9963e380-b727-11eb-978c-d5b8f7380922.png)

**Comment by Kay-Yuan** [comment] 2021-05-17 11:04
> @Kay-Yuan As mentioned in documentation only $filter is currently supported.
> ![image](https://user-images.githubusercontent.com/78795357/118473434-9963e380-b727-11eb-978c-d5b8f7380922.png)

Thank you for notifying me, btw, it's awesome if others are also available.

**Closed** 2021-05-18 07:22 UTC
Labels: MSTeams-Developer-Support, area: teams
