### ISSUE TITLE
/insights/used api doesnt provide as resourceReference  when type web

### ISSUE THREAD

**Issue by harshdamaniahd** [microsoftgraph/microsoft-graph-docs#4258] opened 2019-03-27 08:13 UTC
![image](https://user-images.githubusercontent.com/11780473/55059867-5985a200-5070-11e9-961b-dbd6ed4ebf1e.png)

When used with documents
![image](https://user-images.githubusercontent.com/11780473/55059931-8afe6d80-5070-11e9-8d2d-4a1f8f255b1c.png)

Basically i am trying to find the most recently visited pages by end user, so when we use type web in the query , we dont get the weburl

https://graph.microsoft.com/v1.0/me/insights/used?$filter=ResourceVisualization/Type eq 'Web'&top=99&orderby=lastUsed/lastAccessedDateTime%20desc

**Comment by jthake-msft** [comment] 2019-03-27 15:54
DUPE issue #4263

**Comment by gunfus** [comment] 2019-03-31 21:38
@jthake-msft 
Perhaps I am missing something but how is this a dupe of #4263?

**Comment by harshdamaniahd** [comment] 2019-04-01 06:05
Yes you are right this is a different issue..I can explain more in details if required @jthake-msft

**Comment by jthake-msft** [comment] 2019-04-12 20:31
I would love more information on this... sorry for closing..

**Comment by harshdamaniahd** [comment] 2019-04-15 10:44
I just wrote a blog to explain my requirement in details @jthake-msft .
https://sharepointhd.wordpress.com/2019/04/15/get-the-recent-pages-visited-by-user/
Thanks.

**Comment by harshdamaniahd** [comment] 2019-05-24 16:06
any update ?

**Comment by mbice** [comment] 2021-07-30 17:43
Hi,

We're seeing something very similar that was working up until a few weeks ago. We have a Graph query that pulls most recently viewed items. It seems that when we add the sorting for LastUsed/LastAccessedDateTime it results in the resourceReference being empty for pages (documents are fine).

e.g. 
https://graph.microsoft.com/v1.0/me/insights/used?$orderby=LastUsed/LastAccessedDateTime%20desc&$top=500

This was working for us up until recently.. Thoughts?

**Closed** 2021-10-12 16:30 UTC
Labels: subarea: sites and lists, Q&A
