### ISSUE TITLE
List Groups Example 7 does not work with Java SDK

### ISSUE THREAD

**Issue by tim93422** [microsoftgraph/microsoft-graph-docs#15115] opened 2021-12-02 18:13 UTC
I'm attempting to filter groups using the code in example 7. I kept receiving HTTP 400. Finally, I copy and pasted the code from the example into my application and it received HTTP 400 as well.

10:00:04.593 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.scaledsoftware.demo.azuread.group.lister.GroupLister.main(GroupLister.java:33)
Caused by: com.microsoft.graph.http.GraphServiceException: Error code: Request_UnsupportedQuery
Error message: Unsupported Query.

GET https://graph.microsoft.com/v1.0/groups?%24filter=mailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true%20and%20NOT%28groupTypes%2Fany%28s%3As%20eq%20%27Unified%27%29%29%20and%20membershipRuleProcessingState%20eq%20%27On%27
ConsistencyLevel : eventual
SdkVersion : graph-java/v3.9.0

400 : Bad Request
Cache-Control : no-cache
client-request-id : <redacted-is-this-a-security-risk?>
Content-Type : application/json
Date : Thu, 02 Dec 2021 18:00:04 GMT
request-id : <redacted-is-this-a-security-risk-to-share?>
Strict-Transport-Security : max-age=31536000
Transfer-Encoding : chunked
Vary : Accept-Encoding
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US","Slice":"E","Ring":"4","ScaleUnit":"001","RoleInstance":"BY1PEPF000023C0"}}
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Unsupported Query.",
    "innerError": {
      "date": "2021-12-02T18:00:04",
      "request-id": "<redacted-is-this-a-security-risk-to-share?>",
      "client-request-id": "<redacted-is-this-a-security-risk?>"
    }
  }
}

	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:430)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:396)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:222)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:199)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
	at com.scaledsoftware.demo.azuread.group.lister.GroupLister.run(GroupLister.java:49)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5cd62a-5325-aeda-c1ae-33b6157eb04c
* Version Independent ID: c9b14f46-af37-3520-450c-3ed4d5f54f46
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2021-12-02 19:13
Hi @ramsessanchez, could you assist the customer to resolve this issue?

**Comment by ramsessanchez** [comment] 2021-12-03 00:28
Hi @tim93422 Can you try updating the sdk version to the latest if your application supports it. According to your request you are using v3.9. The latest released version is v5.9. Please reach out again if this issue persists.

**Comment by ramsessanchez** [comment] 2021-12-03 00:30
Also, please ensure you are using the latest version of the java-core library as we have moved to azure identity for authentication, which I don't believe versions 4.0 and below support.

**Comment by tim93422** [comment] 2021-12-07 23:46
I don't see v5.9 in maven central or a tag for it in github. So I used microsoft-graph 5.8.0  and azure-identity 1.4.2 and it still didn't work. If I do not include the ".filter(...)" line it works. With the filter it does not.

  	<properties>
		<java.version>11</java.version>
		
		<azure-identity.identity>1.4.2</azure-identity.identity>
		<microsoft-graph.version>5.8.0</microsoft-graph.version>
		<commons-collections4.version>4.4</commons-collections4.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-collections4</artifactId>
		    <version>${commons-collections4.version}</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>${azure-identity.identity}</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph</artifactId>
			<version>${microsoft-graph.version}</version>
		</dependency>
		
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		</dependency>
				
		<dependency>
		    <groupId>junit</groupId>
		    <artifactId>junit</artifactId>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.hamcrest</groupId>
		    <artifactId>hamcrest</artifactId>
		    <scope>test</scope>
		</dependency>
	</dependencies>

**Comment by tim93422** [comment] 2021-12-08 00:04
GET https://graph.microsoft.com/v1.0/groups/microsoft.graph.delta?%24deltaToken=latest&%24filter=mailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true%20and%20NOT%28groupTypes%2Fany%28s%3As%20eq%20%27Unified%27%29%29%20and%20membershipRuleProcessingState%20eq%20%27On%27&%24select=displayName
ConsistencyLevel : eventual
Prefer : return=minimal
SdkVersion : graph-java/v5.8.0


400 : Bad Request
client-request-id : REDACTED
Content-Type : application/json
Date : Wed, 08 Dec 2021 00:01:23 GMT
request-id : REDACTED
Strict-Transport-Security : max-age=31536000
Transfer-Encoding : chunked
Vary : Accept-Encoding
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US","Slice":"E","Ring":"4","ScaleUnit":"005","RoleInstance":"SJ1PEPF00000A87"}}
{
  "error": {
    "code": "BadRequest",
    "message": "Filter not supported.",
    "innerError": {
      "date": "2021-12-08T00:01:24",
      "request-id": "REDACTED",
      "client-request-id": "REDACTED"
    }
  }
}

**Comment by FaithOmbongi** [comment] 2021-12-08 05:53
Hi @tim93422 , the cause of this error on `$filter` is because you are trying to filter on properties other than **id**. The only supported `$filter` expression on delta queries is by `id`. Example: `https://graph.microsoft.com/v1.0/groups/microsoft.graph.delta?$deltaToken=latest&$filter=id eq 'the ID'`

Please see the [OData query parameters](https://docs.microsoft.com/en-us/graph/api/group-delta?view=graph-rest-1.0&tabs=http#odata-query-parameters) section for information about limited support for `$filter`.

**Comment by tim93422** [comment] 2021-12-08 17:05
I see. Then your 7th example should be removed from https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list.md where I see the following:

```
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new HeaderOption("ConsistencyLevel", "eventual"));

GroupCollectionPage groups = graphClient.groups()
	.buildRequest( requestOptions )
	**.filter("mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and membershipRuleProcessingState eq 'On'")**
	.select("id,membershipRule,membershipRuleProcessingState")
	.get();
```

Since the error is "because you are trying to filter on properties other than id", then the example is wrong. This is what I initially reported! My issue title is "List Groups Example 7 does not work with Java SDK #1672"

**Comment by tim93422** [comment] 2021-12-08 17:23
I guess that brings up the question: can the example #7 filter be used with any SDK or pure HTTP? If not, I suppose the entire section should be removed.

Same with Example 2?
GET https://graph.microsoft.com/v1.0/groups?$count=true&$filter=hasMembersWithLicenseErrors+eq+true&$select=id,displayName
ConsistencyLevel: eventual

Same with Example 4?
GET https://graph.microsoft.com/v1.0/groups?$filter=startswith(displayName, 'a')&$count=true&$top=1&$orderby=displayName
ConsistencyLevel: eventual

**Comment by tim93422** [comment] 2021-12-08 17:29
BTW, same result for groups query without delta. This is literally a cut-and-paste of the example, just like the initial report had. (I see the run result yesterday in comment 988358939 was using delta. This one doesn't, and it doesn't work either)

GET https://graph.microsoft.com/v1.0/groups?%24filter=mailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true%20and%20NOT%28groupTypes%2Fany%28s%3As%20eq%20%27Unified%27%29%29%20and%20membershipRuleProcessingState%20eq%20%27On%27&%24select=id%2CmembershipRule%2CmembershipRuleProcessingState
ConsistencyLevel : eventual
SdkVersion : graph-java/v5.8.0


400 : Bad Request
Cache-Control : no-cache
client-request-id : REDACTED
Content-Type : application/json
Date : Wed, 08 Dec 2021 17:27:08 GMT
request-id : REDACTED
Strict-Transport-Security : max-age=31536000
Transfer-Encoding : chunked
Vary : Accept-Encoding
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US","Slice":"E","Ring":"4","ScaleUnit":"005","RoleInstance":"SJ1PEPF00000BB4"}}
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Unsupported Query.",
    "innerError": {
      "date": "2021-12-08T17:27:08",
      "request-id": "REDACTED,
      "client-request-id": "REDACTED"
    }
  }
}

**Comment by FaithOmbongi** [comment] 2021-12-08 17:30
Hi @tim93422 , [Example 7](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#example-7-list-dynamic-security-groups) is different from the example you shared [here](https://github.com/microsoftgraph/microsoft-graph-docs/issues/15115#issuecomment-988358939).

Example 7:
```
GET https://graph.microsoft.com/v1.0/groups?$filter=mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and membershipRuleProcessingState eq 'On'&$count=true&$select=id,membershipRule,membershipRuleProcessingState
ConsistencyLevel: eventual
```
This [follow-up request](https://github.com/microsoftgraph/microsoft-graph-docs/issues/15115#issuecomment-988358939) you shared...
```
https://graph.microsoft.com/v1.0/groups/microsoft.graph.delta?$deltaToken=latest&$filter=mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and membershipRuleProcessingState eq 'On'&$select=displayName
ConsistencyLevel: eventual
```

So, it's trying to filter on the delta (microsoft.graph.delta cast) that isn't supported. Filtering on /groups is supported as per [Example 7](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#example-7-list-dynamic-security-groups).

Could you try Example 7 with the new library? If that still doesn't work, then @ramsessanchez can help troubleshoot.

**Comment by tim93422** [comment] 2021-12-08 17:32
@FaithOmbongi, yes, I made a mistake when I sent the delta query result. Sorry about that. However, the example 7 code returns an error as well.

**Comment by FaithOmbongi** [comment] 2021-12-08 17:35
> BTW, same result for groups query without delta. This is literally a cut-and-paste of the example, just like the initial report had. (I see the run result yesterday in comment 988358939 was using delta. This one doesn't, and it doesn't work either)
> 
> GET https://graph.microsoft.com/v1.0/groups?%24filter=mailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true%20and%20NOT%28groupTypes%2Fany%28s%3As%20eq%20%27Unified%27%29%29%20and%20membershipRuleProcessingState%20eq%20%27On%27&%24select=id%2CmembershipRule%2CmembershipRuleProcessingState ConsistencyLevel : eventual SdkVersion : graph-java/v5.8.0
> 
> 400 : Bad Request Cache-Control : no-cache client-request-id : REDACTED Content-Type : application/json Date : Wed, 08 Dec 2021 17:27:08 GMT request-id : REDACTED Strict-Transport-Security : max-age=31536000 Transfer-Encoding : chunked Vary : Accept-Encoding x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US","Slice":"E","Ring":"4","ScaleUnit":"005","RoleInstance":"SJ1PEPF00000BB4"}} { "error": { "code": "Request_UnsupportedQuery", "message": "Unsupported Query.", "innerError": { "date": "2021-12-08T17:27:08", "request-id": "REDACTED, "client-request-id": "REDACTED" } } }

Seems our responses crossed each other's paths :)

So, Example 7 does work as a direct the HTTP request -> [Test in Graph Explorer.](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3DmailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true%20and%20NOT(groupTypes%2Fany(s%3As%20eq%20'Unified'))%20and%20membershipRuleProcessingState%20eq%20'On'%26%24count%3Dtrue%26%24select%3Did%2CmembershipRule%2CmembershipRuleProcessingState&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

If it doesn't work using the Java SDK, @ramsessanchez , kindly assist to look into this. @tim93422 confirms that he's now using the microsoft-graph 5.8.0 and azure-identity 1.4.2

**Comment by tim93422** [comment] 2021-12-08 17:46
@FaithOmbongi It seems adding count() fixes the issue. However, it seems the example still needs to be updated (I think) to add .count().

This fails:
			LinkedList<Option> requestOptions = new LinkedList<Option>();
			requestOptions.add(new HeaderOption("ConsistencyLevel", "eventual"));

			GroupCollectionPage groupPage = graphClient.groups()
				.buildRequest( requestOptions )
				.filter("mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and membershipRuleProcessingState eq 'On'")
				.select("id,membershipRule,membershipRuleProcessingState")
//				.count()
				.get();


This works:

			LinkedList<Option> requestOptions = new LinkedList<Option>();
			requestOptions.add(new HeaderOption("ConsistencyLevel", "eventual"));

			GroupCollectionPage groupPage = graphClient.groups()
				.buildRequest( requestOptions )
				.filter("mailEnabled eq false and securityEnabled eq true and NOT(groupTypes/any(s:s eq 'Unified')) and membershipRuleProcessingState eq 'On'")
				.select("id,membershipRule,membershipRuleProcessingState")
				.count()
				.get();


In both cases I'm sending ConsistencyLevel: eventual so unless that is a typo in the example, then it looks like .count() is required.

BTW, I got an error as a guest user in the "Test in Graph Explorer" link you sent.

**Comment by ramsessanchez** [comment] 2021-12-08 17:54
Hi @tim93422, It seems you're right, as it states in example #7 "This request requires the ConsistencyLevel header set to eventual and the **$count=true** query string because the request uses the not operator of the $filter query parameter." Apologies for not catching it sooner, I falsely assumed the example code to have covered the count issue, since the HTTP query provided in the example works on the graph explorer, which it does not. This is an issue with our documentation and will be fixed ASAP. Thanks for your help!

**Comment by FaithOmbongi** [comment] 2021-12-08 17:57
Thank you for the feedback @tim93422. Glad that's now resolved.

> However, it seems the example still needs to be updated (I think) to add .count().

Unfortunately, we have an issue with requests that use the [advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries), esp. `$count` and `$search`. The code snippets might fail to include the **ConsistencyLevel** header and `$count`. An open issue tracking this: [#818](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/818).
So for now, you have to manually add  `.Count()` where required before using the snippet.

>BTW, I got an error as a guest user in the "Test in Graph Explorer" link you sent.

Yes. Advanced querying requires an authenticated session. It doesn't work on the sandbox data when you run without logging in.

Thanks for helping out @ramsessanchez !

Closing this issue now. We're tracking the issue with `$count` missing in code snippets and hope to resolve soon.

cc @Licantrop0

**Closed by FaithOmbongi** 2021-12-08 17:57 UTC
Labels: area: azure/AAD, area: groups, needs author feedback, area: SDKs

**Comment by tim93422** [comment] 2021-12-08 18:04
I'm glad the issue is known and hopefully can be resolved quickly. Thank you for your time working on this.

I suspect we could have resolved this more quickly if someone had copy-and-pasted the code into their IDE and run this when I first reported that the example was wrong. That said:

- I imagine you have loads of work and if you are like me, you look for the first thing that doesn't look right, comment on it and move one.
- I should have noticed the note in the documentation that $count() was required. 
- **Perhaps the .filter() method could automatically add .count()?**

Thanks again for your help. I hope you have a good day.

**Comment by Licantrop0** [comment] 2021-12-09 19:24
Hi @tim93422, I'm the Program Manager for the Advanced Query Capabilities in Microsoft Graph. Thanks for your patience and for reporting this issue. You made the Graph documentation clearer for everyone!  

I agree that we should have been more careful while reviewing the code you posted and would have saved a few days of back and forth. We will be better next time.  
To learn more about the advanced queries, here is the [dedicated article](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).  

On your suggestion for the automatic inclusion of the required parameters/headers (count and eventual consistency), we are working toward simplifying the developer experience, but this requires some architectural changes, and it may take some time.

**Comment by tim93422** [comment] 2021-12-21 05:15
Thanks @Licantrop0. I am glad to hear my suggestion had an impact!
