### ISSUE TITLE
objectId is not mentioned on this page

### ISSUE THREAD

**Issue by leniel** [microsoftgraph/microsoft-graph-docs#6597] opened 2019-12-13 13:31 UTC
I was trying a Microsoft Graph API call like this:

```
B2CService.BuildUrl("/users", $"$filter=signInNames/any(x:x/value%20eq%20%27{encodedEmail}%27)%20or%20otherMails/any(y:y%20eq%20%27{encodedEmail}%27)&$select=id,displayName,{extensionAttribute}");
```

`id` was not returning... the correct property name is `objectId`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment] 2019-12-17 11:36
Appears to be a dupe of issue #6598.

**Comment by dkershaw10** [comment] 2020-01-20 22:29
And it was answered in #6598. searching for signInNames is now also supported in Microsoft Graph v1.0, but the syntax is a little different.  Check out example 3 in https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#examples

**Closed by dkershaw10** 2020-01-20 22:29 UTC
