### ISSUE TITLE
Using Graph API to add users to Group is also removing users from the Group after few millisec. !!!BUG!!!

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#9759] opened 2020-09-02 16:42 UTC
[Enter feedback here
So whenever I am using dummy user account's token to add users to the team. It is pointing at another owner of the team that they have added the users instead of the dummy account. Also today I found out that while adding users using batch call to the (group) it is also automatically removing some members. Pointing at different owner of the team for adding users was fine but removing members while adding is a major bug on your side. Please assist Please look at the attached image

![image](https://user-images.githubusercontent.com/24376864/92011578-1f5a0e80-ed00-11ea-89e7-26507e569e96.png)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61853a9-0289-d23d-5bf2-74b626daf953
* Version Independent ID: 162ab6a6-eab6-6f70-1660-bc0eaffab06b
* Content: [Add a member - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/administrativeunit-post-members.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandyadavMSFT** [comment] 2020-10-05 21:51
@ashoksubedi1 : Can you please clarify the issue a little more? The content you have referred is for adding members to an administrative unit. In your issue description though, you are mentioning irregular behavior while adding members to a M365 group. Am I understanding the issue correctly that the issue is actually around adding members in a M365 group?

**Comment by ashoksubedi1** [comment] 2020-10-05 23:47
Yes sir,
Here it goes: Although I have seen those case less this week. As we know that now we can add members to Teams directly using Teams endpoints of adding members(released recently). For longest time, I was using Group endpoint to add members to Teams but all those members did not show up in Teams right away;  took about half hour for some group members to show up in Teams. Therefore I started using Teams endpoint to add members directly to Teams to assure all members are in Teams right away. May be because now I am adding members using both Group endpoint and TEams endpoint to a team...."Microsoft Ad sync" Account started removing members from Teams instead. Weird part is teams endpoint of adding members does not give me error that members are part of the group already; it lets me add the same member multiple times which ultimately result of removal some how...

**Comment by FaithOmbongi** [comment] 2021-02-24 08:49
Hello @ashoksubedi1 ,
Thank you for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Please ask your question there and they'll troubleshoot this issue with you.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Closed by FaithOmbongi** 2021-02-24 08:49 UTC
