### ISSUE TITLE
ageGroup enum values returned do not match what is documented

### ISSUE THREAD

**Issue by chwarr** [microsoftgraph/microsoft-graph-docs#15745] opened 2022-02-04 02:52 UTC
The documented enum values for the ageGroup property do not match what the Microsoft Graph is returning in practice.

* <strike>For AAD users, the ageGroup values return are capitalized, but the documentation says that they will be lower case. E.g., "Adult" is returned, not the documented "adult".</strike> (Resolved in commit [7a59879c](https://github.com/microsoftgraph/microsoft-graph-docs/commit/7a59879cca1f50a45214478677a596322abe1410))
* For MSA users, the ageGroup value is a number not a string. How should these numbers be interpreted? E.g., for a user born in the 1908s, the ageGroup value is 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#legalagegroupclassification-values)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2022-02-04 18:42
Thank you @chwarr for catching the casing error in the docs for Azure AD users. I've raised a PR to fix that.

The team is investigating the issue on MSA accounts and I'll get back to you with a response.

**Comment by chwarr** [comment] 2022-02-08 03:17
The AAD vs. MSA difference (numbers vs. strings) hasn't been resolved yet. I've updated the original issue to reflect what's still outstanding.

**Comment by FaithOmbongi** [comment] 2022-02-08 06:53
@chwarr, reopening this issue so the issue with MSA is visible as pending resolution.

**Comment by FaithOmbongi** [comment] 2022-02-16 20:47
Hello @chwarr, I've checked in with the team and can't explain why. The API serving consumer users is returning the String values for **ageGroup**.

Unfortunately, this could be a functionality issue somewhere. I recommend that you reopen the 2nd issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html) and share your request ID and a sample response object for investigation.

**Closed by FaithOmbongi** 2022-02-16 20:47 UTC
Labels: area: Azure AD, area: users

**Comment by chwarr** [comment] 2022-02-16 21:10
Can we please leave this issue open until the problem is resolved?

Right now, documentation does not match the behavior. That is a bug.

If the behavior changes to match the documentation, then we can close this.

If the behavior does not change (e.g., back-compat), then the documentation will need to be updated.

**Comment by FaithOmbongi** [comment] 2022-02-17 18:11
Hi @chwarr, as I mentioned, the product team confirmed that what is returned for MSA is the String values. So, the issue is considered isolated to your case and therefore not a doc or product issue—for now. Only until the team can investigate using your request ID can we get the reason you're getting **Int** values instead of **String** member names. I recommend that you file that request at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html) where functionality issues are investigated and share your request ID and a sample response object for the investigation.

**Comment by chwarr** [comment] 2022-02-17 23:17
I have reported this is to the relevant product group inside of Microsoft. If I have additional details to share publicly, I will try to remember to post them here.
