### ISSUE TITLE
Error message: Invalid URL format specified in @odata.bind for owners (Java SDK)

### ISSUE THREAD

**Issue by haridusi** [microsoftgraph/microsoft-graph-docs#12705] opened 2021-05-12 17:11 UTC
When used the code example for java SDK getting below error, when changed it to JsonArray and added elements request was successful but owners weren't added to group. 

            group.additionalDataManager().put("owners@odata.bind", new JsonPrimitive("[  \"https://graph.microsoft.com/v1.0/users/xyz\",  \"https://graph.microsoft.com/v1.0/users/abc\"]"));

giving error : Error message: Invalid URL format specified in @odata.bind for owners

when tried 
            JsonArray owners = new JsonArray();
            owners.add("https://graph.microsoft.com/v1.0/users/xyz");
            owners.add("https://graph.microsoft.com/v1.0/users/abc");
            group.additionalDataManager().put("owners@odata.bind", owners);
group created with no owners.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7c37f6-ee5d-52a5-4db5-eee157bd3935
* Version Independent ID: 25cddb92-e198-16e9-635e-bc4dbd5587ac
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by haridusi** [comment] 2021-05-12 18:02
referring to example - https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=java

**Comment by FaithOmbongi** [comment] 2021-07-02 17:00
@baywet , could you assist to look into this customer issue? Thanks.

**Comment by baywet** [comment] 2021-07-05 14:41
Hi @haridusi 
Thanks for reaching out.
Can you tell us which version of the SDK and the core library you are using please?
If your application is not on 3.9.0 and 2.0.7, can you please upgrade and let us know whether you are still experiencing the issue?
@FaithOmbongi thanks for the ping.

**Comment by lucb31** [comment] 2021-07-07 08:34
Hello @baywet 
I am experiencing the same issue as @haridusi 
As suggested I just upgraded my **maven dependencies** to the newest versions:
```
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph</artifactId>
	<version>3.9.0</version>
</dependency>
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph-core</artifactId>
	<version>2.0.7</version>
</dependency>
```
The issue is not resolved. I am still getting the **error message**:
`SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: Invalid URL format specified in @odata.bind for owners`

Simple **Code snippet**:
```
group.additionalDataManager().put("owners@odata.bind", new JsonPrimitive("[\"https://graph.microsoft.com/v1.0/users/" + ownerIds.get(0) + "\"]"));
group.additionalDataManager().put("members@odata.bind", new JsonPrimitive("[\"https://graph.microsoft.com/v1.0/users/" + memberIds.get(0) + "\"]"));
Group groupResult = graphClient.groups().buildRequest().post(group);
```
Group **object properties** before post command:
![screenshot_invalid_url_format_group_data_manager](https://user-images.githubusercontent.com/40357884/124726183-d4a3b700-df0d-11eb-96b1-4c90a72648fe.png)

I created a **workaround** for the issue by adding members and owners via 
`graphClient.groups(group.id).owners().references().buildRequest().post(owner);` or 
`graphClient.groups(group.id).members().references().buildRequest().post(member);`

With this workaround I experience another **issue**, that there is no Drive Item initialized for the group, if it is initialized with no members and owners.

**Comment by baywet** [comment] 2021-07-07 11:53
Hey @lucb31 
Thanks for the additional details.
Can you try with Json arrays instead like in the second example shared by OP and let me know if you run into the same issue?
Thanks!

**Comment by lucb31** [comment] 2021-07-09 08:13
@baywet 
The example with the JSON array has worked. 
Thanks.

**Comment by baywet** [comment] 2021-07-09 12:00
thanks for confirming, closing

**Closed by baywet** 2021-07-09 12:00 UTC
Labels: area: azure/AAD, area: groups, needs author feedback, request: sample
