### ISSUE TITLE
Example 3 in C# seems wrong

### ISSUE THREAD

**Issue by chrisdbishop** [microsoftgraph/microsoft-graph-docs#7006] opened 2020-02-05 16:11 UTC
I am trying to send a message with attachments but in the example 3 it shows the property Attachments being an IEnumerable&lt;Attachment&gt; but in the SDK it is of type IMessageAttachmentsCollectionPage. I had to create MessageAttachmentsCollectionPage and then I could add the attachment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment] 2021-02-14 17:41
@andrueastman could you please check if the issue is resolved now? I see that Attachments = new MessageAttachmentsCollectionPage() in the generated C# code?

**Comment by andrueastman** [comment] 2021-02-15 07:35
@abheek-das Yes. This has now been resolved via the update to reflect this. 

`Attachments = new MessageAttachmentsCollectionPage()`

Thanks for bringing this to my attention.

**Closed by andrueastman** 2021-02-15 07:35 UTC
