### ISSUE TITLE
unable to get access token for delegated permissions for first time

### ISSUE THREAD

**Issue by vayinapurapu** [microsoftgraph/microsoft-graph-docs#16623] opened 2022-04-22 17:05 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vayinapurapu** [comment] 2022-04-22 17:09
from the step 3 while creating an azure AD application at #7, the redirect URI is incorrect i believe. It should be https://oauth.pstmn.io/v1/browser-callback instead https://oauth.pstmn.io/v1/callback. i have used https://oauth.pstmn.io/v1/browser-callback and after that i am able to get the access token.

**Comment by jasonjoh** [comment] 2022-04-28 13:05
Duplicate of #16435 

Thanks for reporting.

**Closed by jasonjoh** 2022-04-28 13:05 UTC
