### ISSUE TITLE
Fewer attributes in the delta URL response than requested

### ISSUE THREAD

**Issue by viveksk-clumio** [microsoftgraph/microsoft-graph-docs#7776] opened 2020-04-16 11:12 UTC
The Graph delta API for messages of a mail folder does not return all the expected attributes when there is a change in an emails state. 
Example: 
When I call the endpoint 
`/users/{userid}/mailfolders/{mailfolderID}/messages/delta$select=id,changekey,internetMessageId,subject,body,lastModifiedDateTime,parentFolderId,replyTo,from,toRecipients,ccRecipients,bccRecipients,receivedDateTime,sentDateTime,hasAttachments,internetMessageHeaders,isRead,isDraft,flag` , the response returns all attributes of the mails as described in the select query. 
However, when the read status of an email is toggled, the subsequent invocation of the deltaLink API only returns 3 attributes for a few mails namely  (id, isRead, parentFolderId). This is despite the select query containing all the attributes as above. This deviates from the expected behaviour as the official documentation too describes all attributes passed in the $select query parameter will be returned in the response

---
Responses:
First delta call response:
{
  "@odata.context”: ,
  "@odata.deltaLink": ,
  "value": [
    {
      "@odata.type": "#microsoft.graph.message",
      "@odata.etag": ,
      "lastModifiedDateTime": "2020-04-15T17:55:30Z",
      "changeKey": ,
      "receivedDateTime": "2020-04-06T06:21:28Z",
      "sentDateTime": "2020-04-06T06:21:28Z",
      "hasAttachments": false,
      "internetMessageId": ,
      "subject": ,
      "parentFolderId": ,
      "isRead": false,
      "isDraft": false,
      "id": ,
      "body": {
        "contentType": ,
        "content": 
      },
      "from": {
        "emailAddress": {
          "name": ,
          "address": 
        }
      },
      "toRecipients": [
        {
          "emailAddress": {
            "name": ,
            "address": 
          }
        }
      ],
      "ccRecipients": [],
      "bccRecipients": [],
      "replyTo": [],
      "flag": {
        "flagStatus": "flagged"
      }
    }
  ]
}

---
Subsequent delta call response:
{
    "@odata.context": ,
    "@odata.deltaLink”: ,
    "value": [
        {
            "@odata.type": ,
            "parentFolderId": ,
            "isRead": ,
            "id": 
        }
    ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab355c92-69ff-7b13-964a-9c3bc495e417
* Version Independent ID: 158fb540-d830-19fb-9c76-9db9a78c32fe
* Content: [Get incremental changes to messages in a folder - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-messages#feedback)
* Content Source: [concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-messages.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by manishaery** [comment] 2020-04-16 11:51
I'm experiencing this issue as well, not all attributes are returned when an email is marked as read in the subsequent delta API call.

**Comment by svpsiva** [comment] 2020-04-21 16:56
This is by design. We have optimized the delta sync functionality for these read items to reduce the amount of info that gets transferred.

Thanks for pointing out the issue in our docs and we will update the same. In the meantime, we recommend that you either store the item details from an earlier API call or make a new API call to fetch all properties.

**Closed** 2023-02-16 22:07 UTC
Labels: area: outlook, area: delta query, subarea: mail, potential known issue
