### ISSUE TITLE
How to determine which license in the assignedLicenses attribute is Direct or Inherited?

### ISSUE THREAD

**Issue by sarollins** [microsoftgraph/microsoft-graph-docs#18836] opened 2022-10-12 15:14 UTC
We're attempting to mimic what the user sees in O365 when they look at License assignments

In my test case, my user has the Microsoft Power Automate assigned as both Direct and Inherited and the Microsoft Teams Exploratory as an inherited license

When I query for the licenses in Graph, I get the following response

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(assignedLicenses)/$entity",
    "assignedLicenses": [
        {
            "disabledPlans": [],
            "skuId": "710779e8-3d4a-4c88-adb9-386c958d1fdf"
        },
        {
            "disabledPlans": [],
            "skuId": "f30db892-07e9-47e9-837c-80727f46fd3d"
        }
    ]
}

How can you tell the state of each of these assigned licenses?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jconley76** [comment] 2022-10-12 17:44
@sarollins Please use List licenseDetails to get additional information including status for assigned licenses. https://learn.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http

**Comment by sarollins** [comment] 2022-10-12 18:15
So, this license’s status in O365 shows that it is Direct and Inherited, what in the response indicates this?

            "id": "Qy3DpW9doUGj2hOQFThptpK4DfPpB-lHg3yAcn9G_T0",
            "skuId": "f30db892-07e9-47e9-837c-80727f46fd3d",
            "skuPartNumber": "FLOW_FREE",
            "servicePlans": [
                {
                    "servicePlanId": "113feb6c-3fe4-4440-bddc-54d774bf0318",
                    "servicePlanName": "EXCHANGE_S_FOUNDATION",
                    "provisioningStatus": "Success",
                    "appliesTo": "Company"
                },
                {
                    "servicePlanId": "17ab22cd-a0b3-4536-910a-cb6eb12696c0",
                    "servicePlanName": "DYN365_CDS_VIRAL",
                    "provisioningStatus": "Success",
                    "appliesTo": "User"
                },
                {
                    "servicePlanId": "50e68c76-46c6-4674-81f9-75456511b170",
                    "servicePlanName": "FLOW_P2_VIRAL",
                    "provisioningStatus": "Success",
                    "appliesTo": "User"
                }
            ]
        }

This is identical to what I get for a user that has this license with only a status of Direct

**Comment by jconley76** [comment] 2022-10-12 21:10
@sarollins I missed that you were looking specifically for whether a license was inherited or assigned directly, This resource type will provide that info: https://learn.microsoft.com/en-us/graph/api/resources/licenseassignmentstate?view=graph-rest-1.0

**Comment by FaithOmbongi** [comment] 2022-11-01 12:27
Hi @sarollins - I hope the answer that you received is satisfactory. 

I'll be closing this issue now. If the issue is still unresolved, please reply to this thread with more information and I will reopen the thread. Thank you.

**Closed by FaithOmbongi** 2022-11-01 12:27 UTC
Labels: area: Azure AD, area: users, needs author feedback
