### ISSUE TITLE
customer.displayName property returning null values

### ISSUE THREAD

**Issue by nxgxw** [microsoftgraph/microsoft-graph-docs#18620] opened 2022-09-23 20:27 UTC
Hello,
As recently as a few weeks ago the value.customer.displayName property for the customer name was being returned correctly when using 
**GET https://graph.microsoft.com/beta/tenantRelationships/delegatedAdminRelationships**

However, value.customer.displayName recently started returning null values instead of the customer name.. The documentation still leads me to believe this should work though. Would it be possible to find out if the property is broken, or if the customer name is available via another property? (note: value.displayName is the returning the name of the GDAP relationship as it should, but this is not the same as the customer name)

Thank you for your assistance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b064331c-6f2a-4407-84d9-dafeb1b669c3
* Version Independent ID: 94544d60-7d1c-1d77-5371-fcf3a7437825
* Content: [List delegatedAdminRelationships - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/tenantrelationship-list-delegatedadminrelationships?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/tenantrelationship-list-delegatedadminrelationships.md)
* Product: **customer-relationship-management**
* Technology: **microsoft-graph**
* GitHub Login: @adtangir
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adtangir** [comment] 2022-09-26 17:53
Assigning it @koravvams as they are the new owners of this feature.

**Closed** 2022-09-26 18:01 UTC

**Comment by nxgxw** [comment] 2022-09-26 18:22
Hello @adtangir, thank you for your help. Upon attempting your suggestion to switch to the v1 docs for delegatedAdminRelationship, I received the message: 

**_The requested page is not available for Microsoft Graph REST API v1.0. You have been redirected to the newest product version this page is available for._**

When searching for delegatedAdminRelationship in the top level site search I also only see results for beta API.

May I please get your help to investigate?

**Comment by adtangir** [comment] 2022-09-26 18:52
@nxgxw, Sure @koravvams will be able to assist you further as they are the new owners of this repository.

**Comment by koravvams** [comment] 2022-10-04 11:46
Hi @nxgxw, 

customer.displayName is not a mandatory field for partners while creating the GDAP relationship. The customer.displayName will be updated when the customer approves the relationship. For the relationships which are in created or approvalPending, customer.displayName can be null.

**Comment by nxgxw** [comment] 2022-10-04 18:42
Hello @koravvams, 

Yes, the issue is not that we are attempting to populate customer.displayName for creating a new GDAP relationship. It's that the GDAP relationships are already approved and customer.displayName is not populating the actual tenant name as it used to. For all the ~100 GDAP relationships that are approved the value of customer.displayName is null but shouldn't be.

In line with Microsoft's requirement to migrated from DAP to GDAP relationships, we recently completed the migration using the GDAP bulk migration tool https://docs.microsoft.com/en-us/partner-center/gdap-bulk-migration-tool).

Does customer.displayName have non-null values for you? The other issue we keep encountering is that the API is frequently unavailable. For many days now connecting attempts result with: (504) Gateway Timeout.

Thank you for your help!

**Comment by koravvams** [comment] 2022-10-07 05:43
Hi @nxgxw,

can you open a support ticket with the details of partner, customer tenants along with relationship name. We will look into the details and see what is missing. 

Gateway timeout issue is resolved now. 

Thanks.

**Comment by koravvams** [comment] 2022-10-11 05:56
Hi @nxgxw,

We are able to reproduce the customer display name coming null. We will fix the issue and update the details. 

Thanks.

**Comment by nxgxw** [comment] 2022-10-17 18:36
@koravvams, thank you very much! I am looking forward to the fix and appreciate your help.

**Comment by koravvams** [comment] 2022-10-26 14:54
Hi @nxgxw,

The issue is fixed now.

Thanks.

**Comment by nxgxw** [comment] 2022-10-26 15:12
@koravvams this is awesome!! Thank you! I would like to buy a beer for you and whoever else worked on the fix :-D
