### ISSUE TITLE
Clarify Request start/end DateTime timezone info

### ISSUE THREAD

**Issue by michael-hawker** [microsoftgraph/microsoft-graph-docs#4359] opened 2019-04-10 19:08 UTC
There's a lot about the response providing info on the timezone, but not for the request for filtering.  It appears if no timezone is given on the provided query element, that UTC is assumed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fec655-72d2-4bdf-9201-ccfc37848e1e
* Version Independent ID: 63536b57-171d-f44f-97db-78afa8b499ae
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendarview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bpedman** [comment] 2019-09-05 20:26
+1 same question

**Comment by shiweiwei114** [comment] 2019-09-25 02:45
@michael-hawker  Good question, I am in middle of testing this feature too. I don't see there is a way to set request timezone. It seems like it takes UTC time in the request. query params.

**Comment by jasonjoh** [comment] 2019-10-01 17:12
The values of `startDateTime` and `endDateTime` are interpreted as UTC by default. You can change this by:

- Adding an offset to those values (example: `2019-10-02T00:00:00-08:00`)
- Set the `Prefer: outlook.timezone=""` header, the values will be interpreted as the specified time zone.

Note: You **SHOULD NOT** add offsets in the `startDateTime` and `endDateTime` values if you are setting the `Prefer` header. The results are incorrect.

**Comment by tabinnorway** [comment] 2019-10-13 22:25
Trying these, and changing startDateTime and endDateTime as no effect on the data returned. What is returned is always around the time of the request, plus a few days (a week perhaps)? I do

https://graph.microsoft.com/v1.0/users/*****/calendar/events?startDateTime=2019-10-28T00:00:00.0000000&endDateTime=2019-11-03T23:59:59.0000000

My returned items have the following dates
"dateTime": "2019-10-14T13:00:00.0000000"
"dateTime": "2019-10-15T13:00:00.0000000"
"dateTime": "2019-10-16T13:00:00.0000000"
"dateTime": "2019-10-16T06:30:00.0000000",

and so on...

**Comment by tabinnorway** [comment] 2019-10-13 22:29
Never mind...

**Comment by aleybovich** [comment] 2019-11-23 18:00
@jasonjoh Jason, it looks like something changed in CalendarView API and what you stated above used to be true but no longer is. My application broke because of that actually. I used to just set `Prefer:outlook.timezone` header to `Eastern Standard Time` and send time range query without specifying timezones, e.g. `2019-11-08T19:00:00.0000000`

This stopped working sometime in the last couple of months, and now I absolutely do have to send dates with timezone attached, e.g. `2019-11-08T19:00:00.0000000-5` for the API to find the expected events. I confirmed by testing that adding or removing the Prefer doesn't affect the search results, it only affects the format the response dates are in - exactly as the current documentation states.

Could you please clarify if that behavior change is intended and would be kept.

**Comment by jasonjoh** [comment] 2020-01-07 14:45
@aleybovich let me see what I can find out.

**Comment by jasonjoh** [comment] 2020-01-09 15:17
@aleybovich I've discussed with our engineering team and yes, this was an intentional change to make the behavior consistent.

Before the change, as I noted above, having the `Prefer` header AND including a timezone offset in the query parameters caused wrong results. The decision was made that the `Prefer` header should not impact the query parameters and should only control the response (as documented). If you do not specify a timezone offset in the query parameters, they are interpreted as UTC.

I will be updating the docs to explain this.

**Closed** 2020-01-11 00:32 UTC

**Comment by rwahyudi** [comment] 2020-01-14 10:47
How to send query with plus timezone offest ? 
I think it will be simpler and more robust if query timezone is only UTC.

**Comment by jasonjoh** [comment] 2020-01-14 13:11
Have a look at the example queries in the docs. They use a `-08:00` offset for Pacific Standard Time.

```
GET https://graph.microsoft.com/v1.0/me/calendar/calendarView?startDateTime=2017-01-01T19:00:00-08:00&endDateTime=2017-01-07T19:00:00-08:00
```

**Comment by rwahyudi** [comment] 2020-01-16 09:38
Minus sign is not a special character so you can do -08:00. However, doing +08:00 transform the plus sign into space. Encoding it with %2b doesn't work. Am I missing something?

**Comment by rwahyudi** [comment] 2020-01-16 09:39
%

**Comment by jasonjoh** [comment] 2020-01-16 17:27
This works for me:

```
https://graph.microsoft.com/v1.0/me/calendarview?startdatetime=2020-01-16T17:22:35%2B01:00&enddatetime=2020-01-23T17:22:35%2B01:00
```

**Comment by rwahyudi** [comment] 2020-01-17 02:02
Thanks! Not sure what I did wrong but it's working now.
