### ISSUE TITLE
filter started failing

### ISSUE THREAD

**Issue by umutge** [microsoftgraph/microsoft-graph-docs#5405] opened 2019-08-09 13:37 UTC
500 Internal Server Error returns, if I use filter in GET request.

Filter worked up until last month in my MS Flow (filter used in URL: /accessReviews?$filter=businessFlowTemplateId eq '842169FE-E1B7-4CE9-98B6-6A9DB02EEC6B'). But now I get 500 internal server error when I run same workflow.

Retrievin single access review with reviewid (without filter) works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bd544d1-f5e6-a852-936f-4271d4ea21e2
* Version Independent ID: 420409fe-faea-a1b4-f4b0-5bf0530a6b87
* Content: [Get accessReview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreview-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accessreview-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreview-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment] 2019-09-26 21:23
The engineering team ran the call as documented and could not reproduce the issue.  Make sure that you have a valid AAD P2 license and that you’re onboarded to Identity Governance service. For more information, see https://docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta. 

No change identified for the referenced article. Closing the issue.

**Closed by davidmu1** 2019-09-26 21:23 UTC
