### ISSUE TITLE
Archive Team with private channels - error

### ISSUE THREAD

**Issue by TomekPi** [microsoftgraph/microsoft-graph-docs#6803] opened 2020-01-14 14:41 UTC
As Team Owner using API, I try to archive the Team which has private channels. When I'm **not** the Owner of some private channel, I got the error:

>     "code": "GeneralException",
>     "message": "Could not Archive team due to failure in updating channel thread property.",
>     "innerError": {
>       "request-id": "f16a5504-64d2-4f7e-9856-15cb5a72e087",
>       "date": "2019-11-27T10:01:09"
>     }

From UI it's working fine - no error, team is archived.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20088f1-c784-991b-952d-238b1b74fba5
* Version Independent ID: 5b72dce5-7cea-d2fd-327e-dd1d8860ccd8
* Content: [Archive team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-archive.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-gt** [comment] 2020-12-23 09:39
@TomekPi - i tried and was able to archive the team, can you share request id.

**Comment by anandab-msft** [comment] 2021-01-04 07:11
closing this issue, in case you feel the issue is not resolved either reopen this issue or create a new issue.

**Closed** 2021-01-19 18:51 UTC
Labels: bug: product, teams: TACO
