### ISSUE TITLE
Issue using a filter in deletedItems using c# graph sdk beta

### ISSUE THREAD

**Issue by tsp4axl** [microsoftgraph/microsoft-graph-docs#10080] opened 2020-09-28 21:03 UTC
Hi, the C# sample does not work in deletedItems. Pretty sure the resultant request url is missing the "microsoft.graph.group". Also trying to include a filter for displayName. It works fine in graph explorer but not in c#. Getting the error "Searches against this resource are not supported. Only specific instances can be queried." This is easily reproduced in graph explorer when leaving out the "microsoft.graph.group" (and including a filter for displayName). 

Code snippet: (Using Beta Graph SDK)

            String sFilter = String.Format("displayName eq '{0}'", DisplayName);
            var groups = await GraphClient.Directory.DeletedItems.Request().Filter(sFilter).GetAsync();

Exception Detail:

Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: Request_UnsupportedQuery
Message: Searches against this resource are not supported. Only specific instances can be queried.
Inner error:
	AdditionalData:
	date: 2020-09-28T19:57:05
	request-id: 13e4eef3-b9a6-491b-9434-dc25a7eb7a57
	client-request-id: 13e4eef3-b9a6-491b-9434-dc25a7eb7a57
ClientRequestId: 13e4eef3-b9a6-491b-9434-dc25a7eb7a57

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.DirectoryDeletedItemsCollectionRequest.<GetAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphAPICaller.Program.<MSGraphDeletedGroupSearch>d__18.MoveNext() in (MY CODE)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2b59abc-fd5a-c931-d18f-c3ca78b80282
* Version Independent ID: bd1c8f7b-f3f4-c86f-96e7-71e37406dbce
* Content: [List deleted items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by steftacc** [comment] 2020-10-02 09:56
Hello,
any news about this issue ?

**Comment by tsp4axl** [comment] 2020-10-02 14:56
I've worked around it by modifying the RequestUri of the HttpResponseMessage. It's just a little clumsy as now I have to get the content out the Http Response and serialize that JSON formatted OData into a Microsoft.Graph.Group object that I can then work with, actually to undelete. That was the whole purpose of searching for it in the deletedItems bucket first. The client of this "Undelete" API only knows the old displayName. So we search for it by displayName in deletedItems first so we can get the object Id to undelete it and bring it back to life.

HttpRequestMessage httpreq = GraphClient.Directory.DeletedItems.Request().GetHttpRequestMessage(); // Decent starting point
httpreq.RequestUri = new Uri (httpreq.RequestUri.ToString() + "/Microsoft.Graph.Group?$filter=" + sFilter); // Add the missing parts
HttpResponseMessage httpresp = await GraphClient.HttpProvider.SendAsync(httpreq);

Thanks,
Anthony

**Comment by SHAGGAR** [comment] 2020-10-10 05:36
This is also a problem in the non-beta c# sdk.  Theres no mechanism to provide the object type to form the full url path.  The C# example in this document is invalid:
```
var group = await graphClient.Directory.DeletedItems
	.Request()
	.GetAsync();`
```
And it produces a runtime error because the resulting endpoint in the url (/directory/deletedItems) doesnt support any kind of queries:
```
Microsoft.Graph.ServiceException : Code: Request_UnsupportedQuery
    Message: Searches against this resource are not supported. Only specific instances can be queried.
```
I also tried:
```
var deletedUsers = await _gsc.Directory.DeletedItems["microsoft.graph.user"]
				.Request()
```
which produces a valid request url, but the indexer on DeletedItems returns IDirectoryObjectRequestBuilder instead of IDirectoryDeletedItemsCollectionRequest so the result is not properly deserialized into a collection.  This is probably because the indexer on most graph queries is intended to get a specific object, and /directory/deletedItems/ just works differently from the other endpoints in the graph.

I would have 3 suggestions to fix this.
1) Add properties to DeletedItems for each data type ex:
```
var group = await graphClient.Directory.DeletedItems.Users
	.Request()
	.GetAsync();`
```
This would make it really easy to use from a user standpoint, but if the intention is to add other future data types and to make this somewhat dynamic with the datatype being provided as a string you could:

2) Change the indexer on IDirectoryDeletedItemsCollectionRequestBuilder to return IDirectoryDeletedItemsCollectionRequest instead of IDirectoryObjectRequestBuilder.  This would give you a collection of directory objects.  This is still not optimal, though, because the resulting directoryobjects are not what the user wants.  They're looking for the specific type like User, Group, or Application.  Without this nice static typing the developer has to take the resulting DirectoryObject collection and somehow convert it to their actual desired type.

3) Move deleted objects to their respective normal endpoints i.e. /Users, /Groups, /Applications.  This would make it super easy to deal with.  Like I want to get all users, not-deleted and deleted, and this change would allow me to get them all at once instead of making requests to two different endpoints.  If there is a worry that adding deleted entities to these endpoints would be a breaking change for consumers who didnt prepare for it, some form of query option could be added to include deleted.  It could be as simple as includeDeleted=true.  Without specifying this query option the endpoint would work as it does today.

Option 3 would be my personal preference, but idk whats under the hood there and how much of a pain it is to add custom odata query options in the graph.

**Comment by SHAGGAR** [comment] 2020-10-11 06:03
I was able to create a decent workaround for this:
```
var deletedUsersReq = await _gsc.Directory.DeletedItems["microsoft.graph.user"]
				.Request()
				.Select("UserPrincipalName,DeletedDateTime")
				.GetAsync();
var deletedUsers = _gsc.HttpProvider.Serializer.DeserializeObject<IGraphServiceUsersCollectionPage>(deletedUsersReq.AdditionalData["value"].ToString());
```
`
This returns a user collection which is nicely typed so you dont have to do a bunch of dumb stuff.  For groups something like this should work:

```
var deletedGroupReq = await _gsc.Directory.DeletedItems["microsoft.graph.group"]
				.Request()
				.Select("DisplayName,DeletedDateTime")
				.GetAsync();
var deletedGroups = _gsc.HttpProvider.Serializer.DeserializeObject<IGraphServiceGroupsCollectionPage>(deletedGroupReq.AdditionalData["value"].ToString());

```

This should still be fixed by Microsoft, but its a good enough workaround for what i need.

**Comment by FaithOmbongi** [comment] 2021-02-18 17:39
Closing as a duplicate of #10280. I'll raise the issue with the Engineering team.

**Closed by FaithOmbongi** 2021-02-18 17:39 UTC
