### ISSUE TITLE
Listing subscription stopped working

### ISSUE THREAD

**Issue by gustavargas** [microsoftgraph/microsoft-graph-docs#15648] opened 2022-01-26 14:32 UTC
Hi,

- I have an application (for a daemon app) with the permission Mail.Read.
- I created a new suscription with  
`{
    "changeType": "created",
    "notificationUrl": "https://xxxxxxxxxxxxxx",
    "resource": "/users/xxxxxxxxxxxxxxxxx/mailFolders('Inbox')/messages",
    "expirationDateTime": "2022-01-27T23:59:59Z"
}`
and is working ok.
- I tried to list with GET https://graph.microsoft.com/v1.0/subscriptions
![imagen](https://user-images.githubusercontent.com/42381335/151181127-b116c5a9-6311-43d0-b3e4-91949e848a11.png)
The response is always empty

- If I call: GET https://graph.microsoft.com/v1.0/subscriptions/{id} with the ID created by the previous POST, the method returned the subscription object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-list.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @Jumaodhiss
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SamNutkinsPM360** [comment] 2022-01-26 14:47
@Jumaodhiss - having this issue as well. More details here: https://docs.microsoft.com/en-us/answers/questions/708599/get-subscription-api-is-not-working.html

**Comment by gazben** [comment] 2022-01-27 10:07
Having the same problem also. Using the `@odata.nextLink` will sometimes return a result. We have to make 50+ queries to get to the end of the pagination, with ~2-3 subscriptions. This leads to `429 - Too Many requests` pretty quickly.

**Comment by rutbergphilip** [comment] 2022-01-27 12:31
Same issue, receive 201 Created + correct body from POST https://graph.microsoft.com/v1.0/subscriptions but unable to batch get them. I figured a temporary solution (for me) would be to just store the body given from Graph upon creation myself, however requesting each and every subscription through the specific endpoint would lead to the same as mentioned above, `429 - Too Many Requests`.

**Comment by timothyhoffmann** [comment] 2022-01-27 16:21
Ditto behavior.  Out of  ~30 calls only a couple of them had values but all had SkipTokens. Eventually all the expected Subs were returned though.

**Comment by timothyhoffmann** [comment] 2022-01-27 18:17
Yes, all the expected subs trickled in one or two per NextLink call.

**Comment by robward-ms** [comment] 2022-01-27 20:19
Thanks for all the reports!

On Monday 2022/1/24, we were seeing lots of “Invalid Continuation Tokens” from CosmosDB resulting in 500’s returned to the client. This lasted for about 24 hours then dissipated. We’re not seeing any occurrence of this issue currently. 

Zero results with a continuation token is not uncommon, historically our service returns these frequently. However, starting earlier this week (2022/1/24), we’ve had a sharp increase in the response, roughly 10x. As reported here, the tokens are valid and enumerating them will supply the full result sets but there are many more of them to process. 

We are investigating the issue with the help of the CosmosDB support team.

**Comment by ProgrammingWithDJ** [comment] 2022-01-27 21:15
When can we expect this to get fixed?

**Comment by robward-ms** [comment] 2022-01-28 01:22
We believe we understand the change that caused the issue, and it has been rolled back. It looks like the situation is improving but it's hard to tell how much is from the mitigation and how much is from natural traffic rolloff. We're continuing to monitor the issue.

**Comment by gazben** [comment] 2022-01-28 12:26
Can confirm, responses now seem to work properly

**Comment by rutbergphilip** [comment] 2022-01-28 13:26
I'm getting a fixed amount of ghost subscriptions in response from `GET /subscriptions`, they no longer exist when attempting to get them via specific ID `GET /subscriptions/id`.

**Comment by robward-ms** [comment] 2022-01-28 17:24
Thanks again for your reporting the issue! We are now seeing the issue mitigated in all regions. If you still see issues with GetList returning errors or invalid results, please let us know.

**Comment by robward-ms** [comment] 2022-01-28 17:25
@rutbergphilip  - Can you provide some additional information such as a subscription id/application id and timestamp?

**Comment by rutbergphilip** [comment] 2022-02-01 09:55
> @rutbergphilip - Can you provide some additional information such as a subscription id/application id and timestamp?

Sorry for late response. 

Subscription id: `db814c4c-8cf8-49f1-85f4-0251d76cb078`
Application id: `c96089a4-fb90-43f1-b266-7efce11fea12`
Timestamp when request and delete was made: 2022-02-01 ~10:47:00 CET

I made a get all request, could see the subscription, I then made a delete request that was successful with the 204 response, I then made another get all request, could still see the subscription and thereafter a get specific for the sub and got 404.

Not sure if I'm doing something wrong or not, appears to be a unique issue so I'd assume the first =)

**Comment by FaithOmbongi** [comment] 2022-02-04 18:58
Thank you all for bearing with us. The issue as initially reported has been confirmed as resolved. If you still encounter other problems with the API, please open a new issue and kindly share your correlation ID to assist with the investigation. Thank you. Closing this issue.

**Closed by FaithOmbongi** 2022-02-04 18:58 UTC
Labels: area: Azure AD, bug: product, area: change notifications
