### ISSUE TITLE
404 on Example HTTP Request

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#6996] opened 2020-02-04 21:24 UTC
I receive a 404 - Not Found on the Try It page as well as Graph Explorer for GET "https://graph.microsoft.com/beta/me/scopedAdministratorOf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00f58bb7-bd15-f287-7d69-c0cf247e750e
* Version Independent ID: 4f0fe72c-7668-52a0-f47e-de4ee8c91a30
* Content: [List scopedAdministratorOf - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-scopedrolememberof?view=graph-rest-beta&tabs=http#code-try-1)
* Content Source: [api-reference/beta/api/user-list-scopedrolememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-scopedrolememberof.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment] 2020-09-01 22:16
Not able to reproduce the error. No change identified for the page. Closing the issue.

**Closed by davidmu1** 2020-09-01 22:16 UTC
Labels: area: azure/AAD
