### ISSUE TITLE
Authorization_RequestDenied

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs#20254] opened 2023-02-15 10:52 UTC
Despite having Domain.ReadWrite.All permissions, I cannot update the federatedIdpMfaBehavior parameter. 
I have the same with PowerShell Graph. 
I have Global Admin role. 

{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "date": "2023-02-15T10:48:47",
            "request-id": "5ba27ecd-cc59-4a03-9966-4e40cb1c9566",
            "client-request-id": "8c2f3bea-f982-db33-0a3c-e1c897037c6b"
        }
    }
}

Tried both V1.0 and BETA, same result. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1c84fd3-1154-ae9f-ad85-eb0b1f4b1112
* Version Independent ID: 9d1f0e0b-b694-4157-996d-e46806df8ccc
* Content: [Update internalDomainFederation - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/internaldomainfederation-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/internaldomainfederation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/internaldomainfederation-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @rahul-nagraj
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment] 2023-02-15 16:16
Thank you @BakkerJan for raising this issue.

Can you try assigning your app the _Directory.AccessAsUser.All_ permission and let me know if it works?

**Comment by BakkerJan** [comment] 2023-02-21 07:31
@FaithOmbongi Thanks, I tried that. 

It now throws this error:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid value specified for property 'federatedIdpMfaBehavior' of resource 'InternalDomainFederation'.",
        "details": [
            {
                "code": "InvalidValue",
                "message": "Invalid value specified for property 'federatedIdpMfaBehavior' of resource 'InternalDomainFederation'.",
                "target": "federatedIdpMfaBehavior"
            }
        ],
        "innerError": {
            "date": "2023-02-21T07:27:48",
            "request-id": "19d38088-5f9b-46d2-8036-226f202556fc",
            "client-request-id": "a642a9a8-9ddf-84d2-5185-4f497668f6eb"
        }
    }
}

I used this as my request body:

{
    "federatedIdpMfaBehavior": "enforceMfaByFederatedIdP"
}

**Comment by FaithOmbongi** [comment] 2023-02-22 09:46
Hi @BakkerJan ,

The response from the team is that your request looks correct, but the issue needs further investigation to determine the root cause of the failure.

Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/271/microsoft-graph-identity-api). Please file this issue there and provide the contextual information such as the permission workaround and the request ID so it can be investigated. Closing this issue here.

**Closed** 2023-02-22 09:46 UTC
Labels: area: Azure AD, awaiting internal response, area: permissions, area: identity, Q&A
