### ISSUE TITLE
Incorrect return type in Java search example snippets

### ISSUE THREAD

**Issue by martinfrancois** [microsoftgraph/microsoft-graph-docs#8056] opened 2020-05-05 12:01 UTC
I noticed there is an error in the return type in the Java code examples.
In the section where it says: `Here is an example of the request searching the current user's OneDrive`
The return type as specified in the example below is `IDriveItemCollectionPage`, however the correct return type is `IDriveItemSearchCollectionPage`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by baywet** [comment] 2020-11-05 20:56
Hi @martinfrancois 
Thanks for reaching out and thanks for the patience.
This was caused by a bug in our code sample process which has been addressed.
https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/363
The sample itself will be updated soon.
Closing.

**Closed by baywet** 2020-11-05 20:56 UTC
